// Übersetzungen (en). Schlüssel = deutscher Satz aus dem Quelltext, siehe web/core/sprache.js.
// Nicht von Hand zusammenführen: scripts/sprachen-bauen.mjs. Prüfen: node scripts/sprachen-pruefen.mjs
export default {
  "„{name}\" hinzugefügt": "“{name}” added",
  "„{titel}\" ausgeblendet": "“{titel}” hidden",
  "„{titel}“ hat einen eigenen Gruppenchat mit allen, die dabei sind. Du verlässt dafür den Chat mit {name}.": "“{titel}” has its own group chat with everyone who’s in. You’ll leave your chat with {name}.",
  "„{titel}“ läuft in der Gruppe {gruppe}. Dort schreibt ihr alle zusammen — du verlässt dafür den Chat mit {name}.": "“{titel}” is happening in the group {gruppe}. Everyone chats there together — you’ll leave your chat with {name}.",
  "„Daheim\" hat keine Karte — es gibt dort nichts zu verorten.": "“At home” has no map — there's nothing to pin.",
  "{a} und {b} sind auch frei": "{a} and {b} are free too",
  "{a} und {b} warten auf Antwort": "{a} and {b} are waiting for a reply",
  "{a}, {b} und {n} weitere sind auch frei": "{a}, {b} and {n} more are free too",
  "{a}, {b} und {n} weitere warten auf Antwort": "{a}, {b} and {n} more are waiting for a reply",
  "{a}, {b} und eine weitere Person sind auch frei": "{a}, {b} and one more person are free too",
  "{aktion} hat nicht geklappt": "{aktion} didn't work",
  "{an}alle{aus}{rad}{an}Jahr{aus}": "{an}every{aus}{rad}{an}year{aus}",
  "{an}alle{aus}{rad}{an}Jahre{aus}": "{an}every{aus}{rad}{an}years{aus}",
  "{an}alle{aus}{rad}{an}Monat{aus}": "{an}every{aus}{rad}{an}month{aus}",
  "{an}alle{aus}{rad}{an}Monate{aus}": "{an}every{aus}{rad}{an}months{aus}",
  "{an}alle{aus}{rad}{an}Woche{aus}": "{an}every{aus}{rad}{an}week{aus}",
  "{an}alle{aus}{rad}{an}Wochen{aus}": "{an}every{aus}{rad}{an}weeks{aus}",
  "{antwort} — deine Stimme": "{antwort} — your vote",
  "{belegt} von {n} Platz": "{belegt} of {n} seat",
  "{belegt} von {n} Plätzen": "{belegt} of {n} seats",
  "{bereich} zuklappen": "Collapse {bereich}",
  "{frei}/{alle} frei": "{frei}/{alle} free",
  "{h} Uhr": "{h}:00",
  "{n} dabei": "{n} going",
  "{n} frei": "{n} free",
  "{n} Freund": "{n} friend",
  "{n} Freund:in gewählt": "{n} friend selected",
  "{n} Freund:innen gewählt": "{n} friends selected",
  "{n} Freunde": "{n} friends",
  "{n} gemeinsame Crew ›": "{n} shared Crew ›",
  "{n} gemeinsame Crews ›": "{n} shared Crews ›",
  "{n} gemeinsame Freunde · über {name}": "{n} mutual friends · via {name}",
  "{n} gewählt": "{n} selected",
  "{n} Idee": "{n} idea",
  "{n} Ideen": "{n} ideas",
  "{n} Loop": "{n} Loop",
  "{n} Loops": "{n} Loops",
  "{n} Meet": "{n} Meet",
  "{n} Meets": "{n} Meets",
  "{n} Min": "{n} min",
  "{n} Min.": "{n} min",
  "{n} Mitglied": "{n} member",
  "{n} Mitglied ›": "{n} member ›",
  "{n} Mitglieder": "{n} members",
  "{n} Mitglieder ›": "{n} members ›",
  "{n} neu — sie bekommen eine Einladung und denselben Meet-Chat.": "{n} new — they'll get an invitation and join the same Meet chat.",
  "{n} neu — sie bekommt eine Einladung und denselben Meet-Chat.": "{n} new — they'll get an invitation and join the same Meet chat.",
  "{n} neue Nachricht": "{n} new message",
  "{n} neue Nachrichten": "{n} new messages",
  "{n} offene Anfragen": "{n} open requests",
  "{n} Person": "{n} person",
  "{n} Person eingeladen": "{n} person invited",
  "{n} Person hinzufügen": "Add {n} person",
  "{n} Person ist jetzt in {crew}": "{n} person is now in {crew}",
  "{n} Personen": "{n} people",
  "{n} Personen eingeladen": "{n} people invited",
  "{n} Personen hinzufügen": "Add {n} people",
  "{n} Personen sind jetzt in {crew}": "{n} people are now in {crew}",
  "{n} Platz frei": "{n} seat free",
  "{n} Plätze frei": "{n} seats free",
  "{n} Punkte bei „{titel}“": "{n} items for “{titel}”",
  "{n} Std": "{n} h",
  "{n} Std.": "{n} h",
  "{n} Stimme": "{n} vote",
  "{n} Stimmen": "{n} votes",
  "{n} suchen": "{n} looking",
  "{n} suchen noch": "{n} still looking",
  "{n} sucht": "{n} looking",
  "{n} sucht noch": "{n} still looking",
  "{n} Teilnehmende ›": "{n} participants ›",
  "{n} teilnehmende Person ›": "{n} participant ›",
  "{n} Vorschlag": "{n} suggestion",
  "{n} Vorschläge": "{n} suggestions",
  "{n} Zuordnung ging nicht mehr": "{n} pick-up couldn't be saved anymore",
  "{n} Zuordnungen gingen nicht mehr": "{n} pick-ups couldn't be saved anymore",
  "{n}× gewählt": "picked {n}×",
  "{n}× nein": "no {n}×",
  "{n}× übergangen": "skipped {n}×",
  "{name} absetzen": "Remove {name} from your car",
  "{name} angestupst · {wort}": "{name} nudged you · {wort}",
  "{name} aufgelöst": "{name} disbanded",
  "{name} bietet eine {an}Mitfahrt{aus} an": "{name} is offering a {an}ride{aus}",
  "{name} blockieren?": "Block {name}?",
  "{name} blockiert": "{name} blocked",
  "{name} bringt etwas mit": "{name} is bringing something",
  "{name} bringt’s": "{name}'s bringing it",
  "{name} entfernt": "{name} removed",
  "{name} erwähnt {wort}": "{name} mentions {wort}",
  "{name} fährt": "{name} is driving",
  "{name} fährt gerade nicht": "{name} isn't driving right now",
  "{name} fährt noch nicht — du stehst bei „sucht noch“": "{name} isn't driving yet — you're listed as still looking",
  "{name} fragt, ob {titel} bei dir stattfinden kann. Deine Adresse sehen die anderen erst, wenn du zustimmst.": "{name} is asking if {titel} can happen at yours. The others only see your address once you agree.",
  "{name} hat angestupst": "{name} nudged",
  "{name} hat dich angestupst · Lust auf etwas?": "{name} nudged you · up for something?",
  "{name} hat dich zu Crew geholt.": "{name} brought you to Crew.",
  "{name} hatte dich angestupst": "{name} had nudged you",
  "{name} hätte Lust auf {wort}": "{name} is up for {wort}",
  "{name} holt {namen} ab": "{name} picks up {namen}",
  "{name} ist auch frei": "{name} is free too",
  "{name} ist gerade frei": "{name} is free right now",
  "{name} ist jetzt dein Freund": "{name} is now your friend",
  "{name} ist jetzt in {crew}": "{name} is now in {crew}",
  "{name} ist nicht mehr blockiert": "{name} is unblocked",
  "{name} ist nicht mehr dein:e Freund:in": "{name} is no longer your friend",
  "{name} ist schon dein Freund": "{name} is already your friend",
  "{name} mitnehmen": "Give {name} a ride",
  "{name} sucht eine {an}Mitfahrgelegenheit{aus}": "{name} needs a {an}lift{aus}",
  "{name} trägt gerade den goldenen Ring. Ein eigenes Zeichen ersetzt ihn — beides zusammen geht nicht.": "{name} currently has the gold ring. A custom mark replaces it — you can't have both.",
  "{name} trägt gerade ein eigenes Zeichen („{label}\"). Der goldene Ring ersetzt es — beides zusammen geht nicht.": "{name} currently has a custom mark (“{label}”). The gold ring replaces it — you can't have both.",
  "{name} trägt gerade ein eigenes Zeichen. Der goldene Ring ersetzt es — beides zusammen geht nicht.": "{name} currently has a custom mark. The gold ring replaces it — you can't have both.",
  "{name} und {n} weitere Person": "{name} and {n} other person",
  "{name} und {n} weitere Personen": "{name} and {n} other people",
  "{name} verlassen": "Left {name}",
  "{name} verlassen?": "Leave {name}?",
  "{name} wartet auf Antwort": "{name} is waiting for a reply",
  "{name}: {lust}": "{name}: {lust}",
  "{name}: {text}": "{name}: {text}",
  "{name}: frei ab {zeit}": "{name}: free from {zeit}",
  "{name}: im Meet": "{name}: in a Meet",
  "{name}: im Meet · {titel}": "{name}: in a Meet · {titel}",
  "{namen} gibt's schon als {an}„{name}\" ›{aus} — du kannst trotzdem neu erstellen.": "There's already {an}“{name}” ›{aus} with {namen} — you can still create a new one.",
  "{namen} suchen dann wieder.": "{namen} will be looking again.",
  "{namen} sucht dann wieder.": "{namen} will be looking again.",
  "{ort} angefragt": "{ort} requested",
  "{preis} € p. P.": "€{preis} pp",
  "{punkt} · {namen} — wieder freigeben": "{punkt} · {namen} — stop bringing",
  "{punkt} übernehmen": "Bring {punkt}",
  "{tag} · {zeit} vorschlagen": "Suggest {tag} · {zeit}",
  "{termin} · Original": "{termin} · original",
  "{titel} · Original": "{titel} · original",
  "{titel} · von {name}": "{titel} · by {name}",
  "{titel} · von dir": "{titel} · by you",
  "{titel} ansehen": "View {titel}",
  "{titel} bewerten": "Rate {titel}",
  "{zeit} · +{n} Termin": "{zeit} · +{n} date",
  "{zeit} · +{n} Termine": "{zeit} · +{n} dates",
  "{zeit} · Original": "{zeit} · original",
  "{zeit} · Vorschlag von {name}": "{zeit} · suggested by {name}",
  "{zeit} · Vorschlag von dir": "{zeit} · your suggestion",
  "{zeit} vor Beginn": "{zeit} before it starts",
  "{zeit} vorschlagen": "Suggest {zeit}",
  "© OpenStreetMap-Mitwirkende": "© OpenStreetMap contributors",
  "+ {n} Alternative": "+ {n} alternative",
  "+ {n} Alternativen": "+ {n} alternatives",
  "+ Meet": "+ Meet",
  "+ Umfrage": "+ Poll",
  "+ Vorschlag": "+ Suggest",
  "~{n} min Umweg": "~{n} min detour",
  "~{n} min Umweg für dich": "~{n} min detour for you",
  "1 auf der Liste": "1 on the list",
  "1 gemeinsamer Freund · Code {code}": "1 mutual friend · code {code}",
  "1 Monat": "1 month",
  "1 Woche": "1 week",
  "2 Minuten!": "2 minutes!",
  "2 Wochen": "2 weeks",
  "3 Tage": "3 days",
  "3 Wochen": "3 weeks",
  "4 Tage": "4 days",
  "5 Tage": "5 days",
  "ab 3 Personen": "3+ people",
  "ab 4 Personen": "4+ people",
  "ab 4 Personen am besten": "best with 4+",
  "ab und zu": "now and then",
  "Abbrechen": "Cancel",
  "Abends meist frei, Anfänger willkommen": "Quiet most evenings, beginners welcome",
  "Abends meist frei, Anfänger willkommen — Schuhe gibt es vor Ort.": "Quiet most evenings, beginners welcome — shoe hire on site.",
  "Abgesagt": "Cancelled",
  "Abgesagt [Person]": "Declined",
  "Abholreihenfolge": "Pick-up order",
  "Ablehnen": "Decline",
  "Abmelden": "Sign out",
  "Abstand": "Interval",
  "Abstimmen": "Vote",
  "abstimmen lassen": "let people vote",
  "Abwählen": "Deselect",
  "Adler": "Eagle",
  "Adminrolle übergeben": "Hand over admin",
  "Adresse erst nach Zustimmung": "Address once they agree",
  "Adresse freigegeben": "Address shared",
  "Affe": "Monkey",
  "aktiv": "active",
  "Aktiv": "Active",
  "aktiv oder kommend": "active or upcoming",
  "Aktivität": "Activity",
  "Aktivität · {n} Vorschlag": "Activity · {n} suggestion",
  "Aktivität · {n} Vorschläge": "Activity · {n} suggestions",
  "Aktivität abstimmen": "Vote on activity",
  "Aktivität festgelegt": "Activity locked in",
  "Aktivität oder Zeit": "Activity or time",
  "Aktivität vorschlagen": "Suggest an activity",
  "Aktivität zeigen": "Show activity",
  "Aktivitätsstatus für Freunde": "Activity status for friends",
  "Aktivitätsvorschläge ansehen": "See activity suggestions",
  "Aktuellen Entwurf speichern": "Save current draft",
  "Aktueller Standort": "Current location",
  "Aktuelles Passwort": "Current password",
  "Alien": "Alien",
  "alle": "every",
  "Alle": "All",
  "Alle ›": "All ›",
  "Alle {n} Anfragen": "All {n} requests",
  "Alle {n} Jahre am {tag}.{monat}.": "Every {n} years on {tag}/{monat}.",
  "Alle {n} Monate am {tag}.": "Every {n} months on day {tag}.",
  "Alle anderen": "Everyone else",
  "Alle Anfragen ({n})": "All requests ({n})",
  "Alle Autos sind voll.": "All cars are full.",
  "Alle Beteiligten sehen die Absage.": "Everyone involved will see it's cancelled.",
  "Alle deine Freunde sehen {name}.": "All your friends can see {name}.",
  "Alle deine Freunde sind schon in {name}.": "All your friends are already in {name}.",
  "Alle Freunde": "All friends",
  "Alle Freunde sehen deine Ressourcen — außer private.": "All your friends see your stuff — except private items.",
  "Alle Interessen ({n})": "All interests ({n})",
  "Alle Kategorien": "All categories",
  "Alle Meets": "All Meets",
  "alle Plätze belegt": "all seats taken",
  "Alle Ressourcen ({n})": "All items ({n})",
  "Alle sehen denselben Meet-Chat.": "Everyone sees the same Meet chat.",
  "Alles liegt in Ordnern": "Everything's in folders",
  "Alles vergessen": "Forget everything",
  "Alles wird wieder vorgeschlagen": "Everything will be suggested again",
  "Allgemein": "General",
  "Als Alternative": "As alternative",
  "Als besondere Person markieren": "Mark as special person",
  "Als besondere Person markiert": "Marked as special person",
  "Als beste Freund:in markieren": "Mark as best friend",
  "Als beste Freund:in markiert": "Marked as best friend",
  "Als bester Freund markiert": "Marked as best friend",
  "Als Loop starten": "Start as Loop",
  "Als Meet vorschlagen": "Suggest as Meet",
  "als Variante dieses Meets": "as an alternative for this Meet",
  "Als Vorlage nutzen": "Use as template",
  "Am Wasser": "By the water",
  "Amber": "Amber",
  "An": "On",
  "An · {n} Freund": "On · {n} friend",
  "An · {n} Freunde": "On · {n} friends",
  "An · Alle Freunde": "On · All friends",
  "an {n} Person · Wer hat Lust?": "to {n} person · Who's up for it?",
  "an {n} Personen · Wer hat Lust?": "to {n} people · Who's up for it?",
  "Anderes": "Other",
  "Anderes Foto": "Other photo",
  "Ändern": "Change",
  "Änderungen behalten?": "Keep changes?",
  "Änderungen verwerfen": "Discard changes",
  "Anfrage abgelehnt": "Request declined",
  "Anfrage ablehnen": "Decline request",
  "Anfrage an {name} gesendet": "Request sent to {name}",
  "Anfrage an {name} läuft schon": "You've already sent {name} a request",
  "Anfrage an {name} senden": "Ask {name}",
  "Anfrage angenommen": "Request accepted",
  "Anfrage annehmen": "Accept request",
  "Anfrage gesendet": "Request sent",
  "Anfrage läuft schon": "Request already pending",
  "Anfrage senden": "Send request",
  "Anfrage von {name} ablehnen?": "Decline {name}'s request?",
  "Anfrage zurückgezogen": "Request withdrawn",
  "Anfragen": "Requests",
  "Angestupst": "Nudged",
  "Angestupst · {zeit}": "Nudged · {zeit}",
  "Anhänger": "Trailer",
  "Anmelden": "Sign in",
  "Anmeldung": "Sign-in",
  "Anmeldung mit Apple und Google kommt mit der App-Version.": "Sign-in with Apple and Google is coming with the app version.",
  "Annehmen": "Accept",
  "Anstupsen": "Nudge",
  "Anstupser": "Nudges",
  "Anstupser zurücknehmen": "Take back nudge",
  "Antippen, um Mitteilungen auf dieses Gerät zu erlauben.": "Tap to allow notifications on this device.",
  "Antwort {n}": "Answer {n}",
  "Antwort auf Anstupser": "Reply to nudge",
  "Antwort entfernen": "Remove answer",
  "Antwort gespeichert": "Answer saved",
  "Antwort hinzufügen": "Add answer",
  "Antwort offen": "No answer yet",
  "Antworten": "Answers",
  "Anwenden": "Apply",
  "App": "App",
  "Apple Karten": "Apple Maps",
  "Apple und Google folgen mit der App.": "Apple and Google are coming with the app.",
  "Arbeit, Schule, Training": "Work, school, training",
  "Astronaut": "Astronaut",
  "Auf dem iPhone kommen Mitteilungen nur, wenn Crew auf dem Home-Bildschirm liegt. In Safari:": "On iPhone, notifications only arrive when Crew is on your Home Screen. In Safari:",
  "Auf der Karte": "On the map",
  "Auf der Karte gewählt": "Picked on the map",
  "Auf der Liste bei „{titel}“": "On the list for “{titel}”",
  "Auf die Liste": "On the list",
  "Auf diesem Gerät nicht möglich": "Not possible on this device",
  "Auf einer Wiese oder am Grillplatz — Grill und Kohle mitnehmen.": "On a lawn or at a BBQ area — bring a BBQ and charcoal.",
  "Auf Karte wählen": "Pick on map",
  "Auflösen": "Disband",
  "aus": "off",
  "Aus": "Off",
  "aus · Start wäre {datum}": "off · would start {datum}",
  "Aus Verlauf ausblenden": "Hide from history",
  "Ausdruck": "Expression",
  "Ausgeblendet": "Hidden",
  "Ausgehen": "Going out",
  "Ausgehen & Events": "Going out & events",
  "Ausschnitt verschieben und zoomen": "Move and zoom the crop",
  "Aussteigen": "Leave",
  "Auswahl aufheben": "Clear selection",
  "Auswählen": "Select",
  "Auto": "Car",
  "Automatisch": "Automatic",
  "Automatische Anmeldung fehlgeschlagen: {fehler}": "Automatic sign-in failed: {fehler}",
  "Autos": "Cars",
  "Baden": "Swimming",
  "Bahn fährt erst ab 8, also zu Fuß hoch": "Cable car doesn't run till 8, so we're walking up",
  "Bahn oder zu Fuß, oben Panorama": "Cable car or on foot, views from the top",
  "Bahn oder zu Fuß, oben Panorama über den ganzen See.": "Cable car or on foot — views over the whole lake from the top.",
  "Ballsport": "Ball sports",
  "Bar": "Bar",
  "Bär": "Bear",
  "Basketball": "Basketball",
  "Beamer": "Projector",
  "Beamer oder Fernseher": "Projector or TV",
  "Beamer oder Fernseher, Decken — zwei Filme zur Wahl.": "Projector or TV, blankets — two films to pick from.",
  "Beamer, Decken, zwei Filme zur Wahl": "Projector, blankets, two films to pick from",
  "Bearbeiten": "Edit",
  "Beere": "Berry",
  "Bei {name}": "{name}'s place",
  "Bei {name} einsteigen": "Ride with {name}",
  "Bei {name} mitfahren": "Ride with {name}",
  "Bei jemandem daheim": "At someone's place",
  "Bei mir": "My place",
  "Bei wem?": "Whose place?",
  "Beides dauert unter einer Minute.": "Both take less than a minute.",
  "Belästigung": "Harassment",
  "Belgien": "Belgium",
  "Benachrichtigungen": "Notifications",
  "Berg": "Mountain",
  "Berge": "Mountains",
  "Besondere Person": "Special person",
  "Besondere Person — Goldring zurückgenommen": "Special person — gold ring removed",
  "Besondere Person entfernt": "Special person removed",
  "Besonders": "Special",
  "Bestätige zuerst die E-Mail, die wir dir geschickt haben": "Confirm the email we sent you first",
  "Bestätigung schicken": "Send confirmation",
  "Beste Freunde": "Best friends",
  "Beste Freunde · {n} von 3": "Best friends · {n} of 3",
  "Bester Freund": "Best friend",
  "Bester Freund — besonderes Zeichen ersetzt": "Best friend — custom mark replaced",
  "Bester Freund entfernt": "Best friend removed",
  "Bewerten": "Rate",
  "Bewertung ändern": "Change rating",
  "Bewertung gelöscht": "Rating deleted",
  "Bewertung gespeichert": "Rating saved",
  "Bewertung löschen": "Delete review",
  "Bewertung speichern": "Save review",
  "Bild konnte nicht gelesen werden": "Couldn't read that picture",
  "Bildnachweis": "Image credit",
  "Bin am Kiosk, links vom Eingang": "At the kiosk, left of the entrance",
  "Bin dabei, ab 9 passt mir": "I'm in, anytime from 9 works",
  "Bin um 19:10 da, komme direkt von der Arbeit": "There at 19:10, coming straight from work",
  "Bis": "To",
  "bis {betrag} €": "up to €{betrag}",
  "bis {betrag} € p. P.": "up to €{betrag} pp",
  "bis {km} km": "up to {km} km",
  "bis {tag} {zeit}": "until {tag} {zeit}",
  "bis {zeit}": "until {zeit}",
  "Bis du annimmst, sieht die Person <b>nichts</b> von dir — kein Frei, keine Meets, keine Crews. Abgelehnte Anfragen verschwinden lautlos, ohne Hinweis an die andere Seite.": "Until you accept, they see <b>nothing</b> of you — no free status, no Meets, no Crews. Declined requests disappear quietly, without telling the other person.",
  "bis Mitternacht": "until midnight",
  "Bis Mitternacht": "Until midnight",
  "bis morgen {zeit}": "until tomorrow {zeit}",
  "Bitte ein Interesse eingeben": "Please enter an interest",
  "Bitte eine E-Mail-Adresse eingeben.": "Please enter an email address.",
  "Bitte eine gültige E-Mail-Adresse eingeben.": "Please enter a valid email address.",
  "Bitte einen Namen eingeben": "Please enter a name",
  "Bitte mindestens zwei Interessen wählen": "Please pick at least two interests",
  "Blendet den Vorschlag aus — Ähnliches kommt seltener": "Hides this idea — similar ones come up less often",
  "Blitz": "Lightning",
  "Blockieren": "Block",
  "Blockierte Person": "Blocked person",
  "Blockierte Personen": "Blocked people",
  "Blockierung aufheben": "Unblock",
  "Blume": "Flower",
  "Blüte": "Blossom",
  "Bohrmaschine": "Drill",
  "Bollerwagen": "Handcart",
  "Boot": "Boat",
  "Bosnien und Herzegowina": "Bosnia and Herzegovina",
  "Boulder-Dienstag": "Bouldering Tuesday",
  "Boulderhalle K1": "K1 bouldering gym",
  "Bouldern": "Bouldering",
  "Bouldern + Pizza": "Bouldering + pizza",
  "Boxen": "Speakers",
  "Brasilien": "Brazil",
  "Brauche Mitfahrt": "Need a ride",
  "Brettspiele": "Board games",
  "Brunch": "Brunch",
  "Brunch bei Kira": "Brunch at Kira's",
  "Buch": "Book",
  "Budget": "Budget",
  "Camping": "Camping",
  "Campingbus": "Camper van",
  "Campingstuhl": "Camping chair",
  "Chat": "Chat",
  "Chat öffnen": "Open chat",
  "Chillen": "Chill",
  "Chillen & Spiele": "Chilling & games",
  "Club": "Club",
  "Code eingeben": "Enter a code",
  "Code einlösen": "Redeem code",
  "Code erkannt": "Code recognised",
  "Code passt nicht": "That code doesn't work",
  "Code scannen oder Link teilen": "Scan a code or share a link",
  "Code ungültig": "Invalid code",
  "Code von Freund:in eingeben": "Enter a friend's code",
  "Cola": "Coke",
  "Containerschiff": "Container ship",
  "Cowboy": "Cowboy",
  "Crew": "Crew",
  "Crew bearbeiten": "Edit Crew",
  "Crew erstellen": "Create Crew",
  "Crew ist mit diesem Konto aktiviert": "Crew is activated with this account",
  "Crew nicht gefunden": "Crew not found",
  "Crew oder Freunde": "Crew or friends",
  "Crews": "Crews",
  "Curry": "Curry",
  "Cyan": "Cyan",
  "Da fehlt noch ein Eintrag": "Add an item first",
  "Dabei": "In",
  "Dafür braucht es zuerst ein Meet": "You need a Meet for that first",
  "Daheim": "At home",
  "Daheim entfernen": "Remove “At home”",
  "damit nutzt du": "to use",
  "Dänemark": "Denmark",
  "Danke — die Meldung ist raus": "Thanks — your report's been sent",
  "Daraus sortiert Crew deine Vorschläge. Es bleibt in deinem Konto.": "Crew uses this to sort your ideas. It stays in your account.",
  "Darstellung": "Appearance",
  "Dart": "Darts",
  "Das aktuelle Passwort stimmt nicht.": "That's not your current password.",
  "Das bist du selbst": "That's you",
  "Das dürfen nur Fahrer, Mitfahrer oder wer das Meet erstellt hat": "Only drivers, riders or whoever created the Meet can do that",
  "Das Einschalten hat nicht geklappt": "Couldn't turn them on",
  "Das Einschalten hat nicht geklappt. Bitte noch einmal versuchen.": "Turning them on didn't work. Please try again.",
  "Das hat gerade nicht geklappt": "That didn't work just now",
  "Das hat nicht geklappt": "That didn't work",
  "Das ist bereits der Originaltermin": "That's already the original time",
  "Das ist dasselbe Passwort wie bisher": "That's the same password as before",
  "Das ist dein eigener Code": "That's your own code",
  "Das ist kein Crew-Code": "That's not a Crew code",
  "Das ist schon deine Adresse.": "That's already your address.",
  "Das neue Passwort braucht mindestens 8 Zeichen.": "Your new password needs at least 8 characters.",
  "Das Original bleibt wählbar. Deine Stimme ist jederzeit änderbar.": "The original stays an option. You can change your vote any time.",
  "Das Passwort braucht mindestens 8 Zeichen": "Your password needs at least 8 characters",
  "Das Passwort ist zu kurz": "That password is too short",
  "Das sieht nicht nach einer E-Mail-Adresse aus": "That doesn't look like an email address",
  "Dein Desteny-Konto bleibt bestehen. Du kannst dich jederzeit wieder mit {email} anmelden.": "Your Desteny account stays. You can sign in again with {email} at any time.",
  "Dein Desteny-Konto bleibt bestehen. Du kannst dich jederzeit wieder mit deiner E-Mail anmelden.": "Your Desteny account stays. You can sign in again with your email at any time.",
  "Dein Desteny-Konto gilt für Crew und alle Apps von Desteny Development.": "Your Desteny account works for Crew and every app by Desteny Development.",
  "Dein Desteny-Konto wird gelöscht, auch für andere Apps von Desteny Development. Deine Crews und Meets werden dauerhaft entfernt. Das lässt sich nicht rückgängig machen.": "Your Desteny account will be deleted — for other Desteny Development apps too. Your Crews and Meets will be removed for good. This can't be undone.",
  "Dein Name": "Your name",
  "Dein Standort": "Your location",
  "Deine Bewertung": "Your rating",
  "Deine Freunde sehen es neben „frei\".": "Your friends see it next to “free”.",
  "Deine Freunde sehen, dass du frei bist": "Your friends can see you're free",
  "Demo": "Demo",
  "Demo · kein Konto": "Demo · no account",
  "Den Rest können die Fahrer übernehmen.": "The drivers can take care of the rest.",
  "Der Code ließ sich nicht einlösen": "That code didn't work",
  "Der Entwurf verschwindet endgültig.": "The draft will be gone for good.",
  "Der Frei-Status wird spätestens um diese Uhrzeit zurückgesetzt — oder früher durch dein eigenes aktives Meet.": "Your free status resets at this time at the latest — or sooner if you're in an active Meet of your own.",
  "Der Ort selbst": "The place itself",
  "Desteny-Apps": "Desteny apps",
  "Desteny-Konto": "Desteny account",
  "Desteny-Konto erstellen": "Create Desteny account",
  "Desteny-Konto löschen": "Delete Desteny account",
  "Deutschland": "Germany",
  "Diamant": "Diamond",
  "Die App konnte nicht starten.": "The app couldn't start.",
  "Die Crew braucht einen Namen": "The Crew needs a name",
  "Die Demo läuft nur auf diesem Gerät.": "The demo only runs on this device.",
  "Die Erlaubnis wird gerade eingeholt.": "Asking for permission now.",
  "Die Erlaubnis wurde abgelehnt. Zurücknehmen lässt sie sich nur in den Einstellungen des Browsers für diese Seite.": "Permission was denied. You can only undo that in your browser's settings for this site.",
  "Die Frage fehlt noch": "The question's still missing",
  "Die Kamera startet gerade nicht — gib den Code unten ein.": "The camera won't start right now — enter the code below.",
  "Die Karte lädt noch": "The map is still loading",
  "Die Nachricht wird zur Prüfung übermittelt. {name} erfährt nicht, dass du gemeldet hast.": "The message gets sent for review. {name} won't know you reported it.",
  "Die Passwörter stimmen nicht überein": "The passwords don't match",
  "Die Probe ging nicht — sind Mitteilungen erlaubt?": "The test didn't work — are notifications allowed?",
  "die Ressource": "the item",
  "Die Wiederholung endet, das Meet bleibt.": "It stops repeating, but the Meet stays.",
  "Diese E-Mail-Adresse sieht nicht richtig aus": "That email address doesn't look right",
  "Diese Person": "This person",
  "Diese Person fährt gerade nicht": "This person isn't driving right now",
  "Diese Person hat ihren Ort noch nicht geteilt. Die Anfrage geht trotzdem raus.": "This person hasn't shared their place yet. The request still goes out.",
  "diese Ressource": "this item",
  "Diese Stelle": "This spot",
  "Diese Woche mal wieder Bouldern?": "Bouldering again this week?",
  "Diesen Ort wählen": "Pick this spot",
  "Dieser Browser kennt keine Mitteilungen.": "This browser doesn't support notifications.",
  "Dieser Ordner ist noch leer": "This folder's still empty",
  "Dieses Foto verwenden": "Use this photo",
  "Dieses Gerät liefert keinen Standort. „Auf Karte wählen\" geht weiterhin.": "This device can't provide a location. “Pick on map” still works.",
  "Dieses Gerät wird benachrichtigt.": "This device gets notifications.",
  "Dieses Konto komplett zurücksetzen?\n\nAlles wird gelöscht: Profil, Freunde, Gruppen, Meets, Nachrichten. Danach läuft das Einrichten von vorn. Die Anmeldung (E-Mail und Passwort) bleibt.": "Reset this account completely?\n\nEverything gets deleted: profile, friends, groups, Meets, messages. Then setup starts from scratch. Your sign-in (email and password) stays.",
  "Dieses Meet gibt es nicht mehr.": "This Meet doesn't exist any more.",
  "Dieses Meet wurde abgesagt.": "This meet was cancelled.",
  "Direkte Erwähnungen": "Direct mentions",
  "Draußen": "Outdoors",
  "Drohne": "Drone",
  "Drucker": "Printer",
  "Du": "You",
  "du · {name}": "you · {name}",
  "Du bist dabei": "You're in",
  "Du bist das letzte Mitglied von {name}. Die Gruppe und ihr Chat verschwinden; vergangene eigene Meets bleiben in deinem Verlauf.": "You're the last member of {name}. The group and its chat will disappear; your past Meets stay in your history.",
  "Du bist die einzige Person, die {name} verwaltet. Wähle, wer das übernimmt — danach verlässt du die Gruppe.": "You're the only one running {name}. Pick who takes over — then you'll leave the group.",
  "Du bist eingeladen": "You're invited",
  "Du bist jetzt frei": "You're free now",
  "Du bist kein Mitglied": "You're not a member",
  "Du bist raus": "You're out",
  "Du bringst’s": "You're bringing it",
  "Du fährst": "You're driving",
  "Du fährst mit {name}": "You're riding with {name}",
  "Du hast {name} angestupst": "You nudged {name}",
  "Du hast abgesagt": "You can't make it",
  "Du hast abgesagt — hier siehst du nur, wer fährt.": "You can't make it — you only see who's driving.",
  "Du hast angestupst": "You nudged",
  "Du hast dich frei gemeldet": "You said you're free",
  "Du hast ein Meet gestartet": "You started a Meet",
  "Du hast etwas bearbeitet, aber noch nicht gespeichert.": "You've edited something but haven't saved it yet.",
  "Du hast zurückgestupst": "You nudged back",
  "Du holst {namen} ab": "You pick up {namen}",
  "Du kommst selbst hin.": "You're getting there on your own.",
  "Du siehst danach weder den Chat noch neue Meets dieser Gruppe. Vergangene eigene Meets bleiben in deinem Verlauf.": "After that you won't see this group's chat or new Meets. Your past Meets stay in your history.",
  "Du stehst bei „sucht noch“": "You're listed as still looking",
  "Du suchst eine Mitfahrt.": "You need a ride.",
  "Dunkel": "Dark",
  "E-Mail": "Email",
  "E-Mail ändern": "Change email",
  "E-Mail ausfüllen": "Enter your email",
  "E-Mail oder Passwort stimmt nicht": "Wrong email or password",
  "E-Mail und Passwort": "Email and password",
  "E-Mail und Passwort ausfüllen": "Enter your email and password",
  "eben hinzugefügt": "just added",
  "eben hinzugefügt · {kosten}": "just added · {kosten}",
  "Egal": "Any",
  "Eher nicht": "Not so much",
  "Eigene": "Custom",
  "Eigene Idee": "Own idea",
  "Eigene Mitteilung, getrennt von den übrigen": "Its own notification, separate from the rest",
  "Eigenes Emoji": "Custom emoji",
  "Eigenes Emoji: das rechte Feld antippen und aus der Tastatur wählen. Ein Emoji ersetzt das Symbol — der farbige Ring bleibt.": "Custom emoji: tap the field on the right and pick one from your keyboard. An emoji replaces the icon — the coloured ring stays.",
  "Eigenes Interesse": "Own interest",
  "Eigenes Interesse hinzufügen": "Add own interest",
  "Ein eigenes Foto statt Farbe und Motiv. Danach rückst du es im Kreis zurecht.": "Your own photo instead of a colour and icon. Then you position it in the circle.",
  "Ein Freund hat dich zu Crew geholt.": "A friend brought you to Crew.",
  "Ein Platz mehr": "One more seat",
  "Ein Platz weniger": "One seat fewer",
  "Ein Tipp genügt — so wissen alle, wer wen abholt.": "One tap — so everyone knows who picks up whom.",
  "Eine Ebene, keine Unterordner. Neue Ordner erscheinen sofort als Filter und im Speichern-Sheet.": "One level, no subfolders. New folders show up straight away as filters and when saving.",
  "Einen Moment …": "Just a moment …",
  "Einen Moment noch — kurz warten und noch einmal versuchen": "Hang on — wait a moment and try again",
  "Eingeladen": "Invited",
  "Einladen": "Invite",
  "Einladung": "Invitation",
  "Einladungen & Meet-Änderungen": "Invitations & Meet changes",
  "einmalig an {n} Mitglied von {name}": "once, to {n} member of {name}",
  "einmalig an {n} Mitglieder von {name}": "once, to {n} members of {name}",
  "einmalig an {n} Teilnehmende": "once, to {n} participants",
  "einmalig an {n} teilnehmende Person": "once, to {n} participant",
  "einmalig an {name}": "once, to {name}",
  "einmalig an diesen Raum": "once, to this room",
  "Einmalige Freigabe. Crew sendet danach keine weitere Position und ortet dich nicht im Hintergrund.": "One-time share. Crew won't send your position again or track you in the background.",
  "Einschalten": "Turn on",
  "Einsteigen": "Hop in",
  "Einstellungen": "Settings",
  "Einstellungen speichern": "Save settings",
  "Eis": "Ice cream",
  "Element hinzufügen": "Add item",
  "Emoji": "Emoji",
  "Endet am nächsten Tag": "Ends the next day",
  "Endgültig löschen": "Delete for good",
  "Engel": "Angel",
  "Entdecken": "Discover",
  "Entdecken oder eigene Idee": "Discover or own idea",
  "Entfernen": "Remove",
  "Entfernung": "Distance",
  "Entwurf löschen": "Delete draft",
  "Entwurf löschen?": "Delete draft?",
  "Entwurf speichern": "Save draft",
  "Erde": "Earth",
  "Ereignis eintragen": "Log event",
  "Erhalten · {n}": "Received · {n}",
  "Erinnerung aus": "Reminder off",
  "Erlauben lässt es sich in den iPhone-Einstellungen: Mitteilungen → Crew.": "You can allow them in iPhone Settings: Notifications → Crew.",
  "Erst auf den Home-Bildschirm": "Add to Home Screen first",
  "Erst die Gruppe übergeben": "Hand over the group first",
  "Erst eine Aktivität wählen": "Pick an activity first",
  "Erst eine Idee wählen": "Pick an idea first",
  "Erst eine Idee wählen — oder „Spontanes Treffen\"": "Pick an idea first — or “Spontaneous meet”",
  "Erst eine Person wählen": "Pick a person first",
  "Erst einen Namen eingeben": "Enter a name first",
  "Erst einen Ort wählen": "Pick a place first",
  "Erst einen Punkt eintragen": "Add an item first",
  "Erst einen Titel eingeben": "Enter a title first",
  "Erst jemanden absetzen": "Remove someone first",
  "Erst mindestens eine Person oder Crew wählen": "Pick at least one person or Crew first",
  "Erstmal umsehen": "Just look around first",
  "Essen": "Food",
  "Essen & Trinken": "Food & drink",
  "Essen gehen": "Eating out",
  "Etwas anderes": "Something else",
  "Etwas hinzufügen": "Add something",
  "Euer Kino-Klassiker": "Your cinema favourite",
  "Eule": "Owl",
  "Europa": "Europe",
  "Event": "Event",
  "EVENT": "EVENT",
  "Fahrrad": "Bike",
  "Fahrzeuge": "Vehicles",
  "Farbe": "Colour",
  "Farbe wählen": "Pick a colour",
  "Farbe, Motiv oder Foto — änderbar im Profil.": "Colour, icon or photo — you can change it in your profile.",
  "Farbverlauf": "Gradient",
  "Feiern": "Partying",
  "Fernglas": "Binoculars",
  "Fertig": "Done",
  "Feste Zeiten eintragen": "Add fixed times",
  "Festivals": "Festivals",
  "Festlegen": "Lock in",
  "Festspiele Seebühne": "Seebühne Festival",
  "Feuer": "Fire",
  "Feuerwerk am See": "Fireworks by the lake",
  "Film": "Film",
  "Filmabend": "Film night",
  "Filme & Serien": "Films & series",
  "Filter": "Filters",
  "Finnland": "Finland",
  "Fitness": "Fitness",
  "Fixe Uhrzeit": "Fixed time",
  "Flaggen": "Flags",
  "Flieder": "Lilac",
  "Flugzeug": "Plane",
  "Flugzeuge": "Aircraft",
  "folgt dem Gerät": "follows your device",
  "Foto": "Photo",
  "Foto entfernen": "Remove photo",
  "Foto wählen": "Choose photo",
  "Foto wird vorbereitet …": "Preparing photo …",
  "Foto-Nachweis ausblenden": "Hide photo credit",
  "Foto-Nachweis zeigen": "Show photo credit",
  "Foto: {urheber}": "Photo: {urheber}",
  "Fotografieren": "Photography",
  "Frage": "Question",
  "Frage und zwei Optionen ausfüllen": "Fill in a question and two options",
  "fragt jetzt nach Freigabe": "asks for permission now",
  "Frankreich": "France",
  "Frech": "Cheeky",
  "Frei": "Free",
  "Frei — aktiv": "Free — active",
  "frei · {lust}": "free · {lust}",
  "Frei · {status}": "Free · {status}",
  "Frei ab": "Free from",
  "frei ab {zeit}": "free from {zeit}",
  "Frei ab {zeit}": "Free from {zeit}",
  "Frei setzen": "Mark as free",
  "Frei zurücksetzen um": "Reset free at",
  "Frei zurücksetzen um {zeit}": "Free resets at {zeit}",
  "Frei-Hinweis": "Free alert",
  "Frei-Hinweis von {name} an": "Free alerts from {name} on",
  "Frei-Hinweis von {name} aus": "Free alerts from {name} off",
  "Frei-Hinweise · Individuell": "Free alerts · Custom",
  "Frei-Hinweise von Freunden": "Free alerts from friends",
  "Frei-Status speichern": "Save free status",
  "freie Umfrage im Chat": "standalone poll in the chat",
  "Freigabe": "Sharing",
  "Freigabe wird abgefragt …": "Asking for permission …",
  "Freigeben": "Unblock",
  "Freitag": "Friday",
  "Freitag wieder was machen?": "Do something again on Friday?",
  "Freitag-Crew": "Friday Crew",
  "freiwillig": "optional",
  "Freund hinzufügen": "Add friend",
  "Freunde": "Friends",
  "Freunde · {n}": "Friends · {n}",
  "Freunde hinzufügen": "Add friends",
  "Freunde sehen nur „Keine Zeit“.": "Friends only see “Busy”.",
  "Freunde suchen": "Search friends",
  "Freundesanfragen": "Friend requests",
  "Freundschaft beenden": "Remove friend",
  "Freundschaft beendet": "Friend removed",
  "Freundschaft mit {name} beenden?": "Remove {name} as a friend?",
  "Freundschaftsanfragen": "Friend requests",
  "Frisbee": "Frisbee",
  "Fröhlich": "Cheerful",
  "Frosch": "Frog",
  "Früh buchen": "Book early",
  "Früh buchen, nur bei gutem Wetter": "Book early, good weather only",
  "Fuchs": "Fox",
  "Füge mich in Crew hinzu: {code}": "Add me on Crew: {code}",
  "Für {antwort} stimmen": "Vote for {antwort}",
  "Für {titel} · Original bleibt wählbar": "For {titel} · original stays an option",
  "Für dein Desteny-Konto.": "For your Desteny account.",
  "Für dich": "For you",
  "Für dieses Meet gibt es keinen Raum": "There's no chat room for this Meet",
  "Fußball": "Football",
  "Gaming": "Gaming",
  "Gehört zu": "Belongs to",
  "Geht immer": "Always works",
  "Geist": "Ghost",
  "Geländewagen": "Off-roader",
  "Gelb": "Yellow",
  "Gemeinsam erlebt": "Done together",
  "Gemeinsam kochen": "Cook together",
  "Gemeinsame Crews": "Shared Crews",
  "Gemeinsame Interessen": "Shared interests",
  "Gemeinsame Ressourcen": "Shared stuff",
  "gemeinsamer Raum": "shared room",
  "Gemeldet · {name} blockiert": "Reported · {name} blocked",
  "Gemeldet · Person blockiert": "Reported · person blocked",
  "Gemütlich daheim": "Cosy at home",
  "genauer": "Refine",
  "gerade eben": "just now",
  "Gerade frei": "Free now",
  "Gerade frei · {n}": "Free now · {n}",
  "Gerade gilt dein Foto. Wählst du hier etwas, ersetzt es das Foto.": "Your photo is in use. Pick something here and it replaces the photo.",
  "Gerade nicht möglich": "Not possible right now",
  "gesendet": "sent",
  "Gespeichert": "Saved",
  "Gespeichertes suchen …": "Search saved …",
  "Gestern, {datum}": "Yesterday, {datum}",
  "Getränke": "Drinks",
  "Gib die E-Mail deines Desteny-Kontos ein. Wir schicken dir einen Link für ein neues Passwort.": "Enter the email of your Desteny account. We'll send you a link to set a new password.",
  "Gib zuerst dein aktuelles Passwort ein.": "Enter your current password first.",
  "Gilt für alle besten Freunde · nur für dich sichtbar": "Applies to all best friends · only visible to you",
  "Gitarre": "Guitar",
  "Gold": "Gold",
  "Graphit": "Graphite",
  "Griechenland": "Greece",
  "Grill": "BBQ",
  "Grill und Kohle mitnehmen": "Bring a BBQ and charcoal",
  "Grillen": "BBQ",
  "Grillen am See": "BBQ by the lake",
  "Grillen im Grünen": "Outdoor BBQ",
  "Grimmig": "Fierce",
  "Grinsen": "Grinning",
  "grob nach Luftlinie": "rough, as the crow flies",
  "grobe Umgebung · {ort}": "rough area · {ort}",
  "Großbritannien": "United Kingdom",
  "Große Küche": "Big kitchen",
  "Grün": "Green",
  "Grund fehlt": "Pick a reason",
  "Grund melden (freiwillig)": "Give a reason (optional)",
  "Gruppe ändern": "Edit group",
  "Gruppe anlegen": "Create group",
  "Gruppe auflösen": "Disband group",
  "Gruppe auflösen?": "Disband group?",
  "Gruppe bearbeiten": "Edit group",
  "Gruppe gespeichert": "Group saved",
  "Gruppe nicht gefunden": "Group not found",
  "Gruppe öffnen": "Open group",
  "Gruppe öffnen?": "Open group?",
  "Gruppe verlassen": "Leave group",
  "Gruppenbild": "Group picture",
  "Gruppenbild ändern": "Change group picture",
  "Gruppenbild groß ansehen": "View group picture",
  "Gruppenbild von {name}": "Group picture of {name}",
  "Gruppenbild wählen": "Choose group picture",
  "Gruppenoptionen": "Group options",
  "Gut": "Good",
  "Gym": "Gym",
  "Habt ihr schon gewählt": "You've picked this before",
  "Hängematte": "Hammock",
  "Hase": "Rabbit",
  "Hat nicht geklappt": "Didn't work",
  "Hat nicht stattgefunden": "Didn't happen",
  "Hauptnavigation": "Main navigation",
  "Hauptvorschlag": "Main pick",
  "Heißluftballon": "Hot-air balloon",
  "Helikopter": "Helicopter",
  "Hell": "Light",
  "Herz": "Heart",
  "Heute": "Today",
  "Heute und morgen": "Today and tomorrow",
  "heute, {zeit}": "today, {zeit}",
  "Himmelblau": "Sky blue",
  "Hintergrund": "Background",
  "Hinweis ausblenden": "Hide hint",
  "Hinweis schließen": "Dismiss hint",
  "Hinzufügen": "Add",
  "Höhe über der Karte": "Height above the map",
  "Hubschrauber": "Helicopter",
  "Hund": "Dog",
  "Ich bin frei": "I'm free",
  "Ich brauche eine Mitfahrt": "I need a ride",
  "Ich bring Cola, Chips und Kohle mit": "I'll bring Coke, crisps and charcoal",
  "Ich bring Snacks für oben mit": "I'll bring snacks for the top",
  "Ich fahre": "I'm driving",
  "Ich komme selbst": "I'm getting there on my own",
  "Ich nehm die Frisbee mit": "I'll bring the frisbee",
  "Ich nehm die Seile mit": "I'll bring the ropes",
  "Ich übernehm die Snacks @Mira du die Seile?": "I've got the snacks @Mira you do the ropes?",
  "Ich war nicht dabei": "I wasn't there",
  "Ich wäre für Kochen bei mir": "I vote cooking at mine",
  "Idee": "Idea",
  "IDEE": "IDEA",
  "Idee anlegen": "Add idea",
  "Idee entfernen": "Remove idea",
  "Idee speichern": "Save idea",
  "Igel": "Hedgehog",
  "Ihr habt: {ding}": "You have: {ding}",
  "Ihr seht danach nichts mehr voneinander — kein Frei, keine Meets, keine Crews. Eure gemeinsamen vergangenen Meets und deine eigenen Bewertungen bleiben erhalten.": "After that you won't see anything of each other — no free status, no Meets, no Crews. Your past Meets together and your own reviews stay.",
  "Ihr seht danach nichts mehr voneinander. {name} verschwindet aus deinen Listen, aus euren Gruppen und aus allen Räumen — auch bereits geschriebene Nachrichten. {name} erfährt davon nichts.": "After that you won't see anything of each other. {name} disappears from your lists, your groups and all rooms — including messages already sent. {name} won't be told.",
  "Ihr seht danach weder eure freie Zeit noch eure Profile. Gemeinsame Meets und deine eigenen Bewertungen bleiben in deinem Verlauf.": "After that you won't see each other's free time or profiles. Shared Meets and your own reviews stay in your history.",
  "Ihr seid schon befreundet": "You're already friends",
  "Im Demo-Modus gibt es kein Konto.": "There's no account in demo mode.",
  "Im Demo-Modus gibt es keine Mitteilungen — es gibt niemanden, der etwas schicken könnte.": "No notifications in demo mode — there's nobody to send you anything.",
  "Im Demo-Modus öffnen": "Open in demo mode",
  "Im Meet · {titel}": "In a Meet · {titel}",
  "Im Meet vermerkt": "Added to the Meet",
  "Immer": "Always",
  "immer dabei": "always included",
  "Immer verfügbar": "Always available",
  "in {min} Min.": "in {min} min",
  "In {ordner} gespeichert": "Saved to {ordner}",
  "In {ort}": "In {ort}",
  "in {std} Std": "in {std} h",
  "in {std} Std {min} Min": "in {std} h {min} min",
  "Indigo": "Indigo",
  "Individuell": "Custom",
  "Individuell · {n}": "Custom · {n}",
  "Individuell · niemand": "Custom · nobody",
  "Info zur Lage": "Heads-up",
  "Initialen": "Initials",
  "Interesse": "Interest",
  "Interesse bearbeiten": "Edit interest",
  "Interesse entfernen": "Remove interest",
  "Interesse entfernt": "Interest removed",
  "Interesse gibt es schon": "You've already got that interest",
  "Interesse hinzufügen": "Add interest",
  "Interesse hinzugefügt": "Interest added",
  "Interessen": "Interests",
  "Irland": "Ireland",
  "Italien": "Italy",
  "Ja, bei mir": "Yes, at mine",
  "Ja. @Jonny bringst du die Kohle mit?": "Yep. @Jonny can you bring the charcoal?",
  "Jahr": "Year",
  "Jahr [Einheit]": "year",
  "Jahr {jahr}": "Year {jahr}",
  "Jahr wählen": "Pick a year",
  "Jahre [Einheit]": "years",
  "Japan": "Japan",
  "Jause": "Snacks",
  "Jazz am See": "Jazz by the lake",
  "Jede Woche. Freunde sehen nur „Keine Zeit“.": "Every week. Friends only see “Busy”.",
  "Jeden {n}. {tag}": "Every {n}th {tag}",
  "Jeden {n}. {wochentag}": "Every {n}th {wochentag}",
  "Jeden {tag}": "Every {tag}",
  "Jeden {wochentag}": "Every {wochentag}",
  "Jeden dritten {tag}": "Every third {tag}",
  "Jeden dritten {wochentag}": "Every third {wochentag}",
  "Jeden fünften {tag}": "Every fifth {tag}",
  "Jeden fünften {wochentag}": "Every fifth {wochentag}",
  "Jeden Monat am {tag}.": "Every month on day {tag}.",
  "Jeden sechsten {tag}": "Every sixth {tag}",
  "Jeden sechsten {wochentag}": "Every sixth {wochentag}",
  "Jeden Tag": "Every day",
  "Jeden vierten {tag}": "Every fourth {tag}",
  "Jeden vierten {wochentag}": "Every fourth {wochentag}",
  "Jeden zweiten {tag}": "Every other {tag}",
  "Jeden zweiten {wochentag}": "Every other {wochentag}",
  "Jedes Jahr am {tag}.{monat}.": "Every year on {tag}/{monat}.",
  "Jemand": "Someone",
  "Jet": "Jet",
  "jetzt": "now",
  "Jetzt": "Now",
  "Jetzt bewerten": "Rate now",
  "Jetzt frei?": "Free now?",
  "Jetzt vorschlagen": "Suggest now",
  "Jetzt: {an}{email}{aus}": "Current: {an}{email}{aus}",
  "Jupiter": "Jupiter",
  "Kaffee": "Coffee",
  "Kaktus": "Cactus",
  "Kamera": "Camera",
  "Kamera nicht freigegeben — gib den Code unten ein.": "Camera not allowed — enter the code below.",
  "Kanada": "Canada",
  "Kann mich jemand mitnehmen? Ich bräuchte eine Mitfahrgelegenheit": "Can someone give me a lift? I need a ride",
  "Kanu": "Canoe",
  "Karamell": "Caramel",
  "Karaoke": "Karaoke",
  "Karte": "Map",
  "Karte bewegen — der Pin bleibt in der Mitte": "Move the map — the pin stays in the middle",
  "Karte nicht verfügbar": "Map unavailable",
  "Karten": "Cards",
  "Karten und Snacks — ab 3 Personen.": "Cards and snacks — 3+ people.",
  "Karten und Snacks, ab 3 Personen": "Cards and snacks, 3+ people",
  "Kartenabend": "Card night",
  "Kartendaten": "Map data",
  "Kartenspiele": "Card games",
  "Kategorie": "Category",
  "Katze": "Cat",
  "Kein Muster": "No pattern",
  "Kein Ordner": "No folder",
  "Kein Ort gefunden": "No place found",
  "Kein Ort gefunden. Tipp: Name des Lokals, der Halle oder der Straße.": "No place found. Tip: try the name of the venue, gym or street.",
  "Kein passendes Symbol gefunden — {an}such dir selbst eines aus{aus}.": "No matching icon found — {an}pick one yourself{aus}.",
  "Kein Platz mehr frei": "No seats left",
  "Kein Platz mehr für {namen}": "No seat left for {namen}",
  "kein Umweg": "no detour",
  "kein Umweg für dich": "no detour for you",
  "Keine aktuellen Meets": "No upcoming Meets",
  "Keine Angabe": "No preference",
  "Keine Freunde auf der Karte": "No friends on the map",
  "Keine gesendeten Anfragen": "No sent requests",
  "Keine Kamera gefunden — gib den Code unten ein.": "No camera found — enter the code below.",
  "Keine Meets in diesem Zeitraum": "No Meets in this time range",
  "Keine offenen Anfragen": "No pending requests",
  "Keine Variante gewählt": "No option picked",
  "Keine Verbindung zum Server. Deine Anmeldung ist noch da – öffne Crew gleich noch einmal.": "No connection to the server. You're still signed in – open Crew again in a moment.",
  "Keine Verbindung. Netz prüfen und noch einmal versuchen.": "No connection. Check your network and try again.",
  "Keine vergangenen Meets": "No past Meets",
  "Keine Vorschläge — Filter oder Suche anpassen": "No ideas — try another filter or search",
  "Keine Zeit": "Busy",
  "Keine Zeit bearbeiten": "Edit busy times",
  "Keine Zeit bis {tag} {zeit}": "Busy until {tag} {zeit}",
  "Keine Zeit bis {zeit}": "Busy until {zeit}",
  "Keine Zeit bis Mitternacht": "Busy until midnight",
  "Keine Zeit bis morgen {zeit}": "Busy until tomorrow {zeit}",
  "Keine Zeit eintragen": "Add busy times",
  "Keine Zeit ist seit {zeit} vorbei": "Your busy time ended at {zeit}",
  "Kino": "Cinema",
  "Kino & Filme": "Cinema & films",
  "Kino Donnerstag um 20:15 — kommst du mit?": "Cinema Thursday at 20:15 — you coming?",
  "Kino unter freiem Himmel direkt am See": "Outdoor cinema right by the lake",
  "Kino unter freiem Himmel direkt am See — Decken mitbringen.": "Outdoor cinema right by the lake — bring blankets.",
  "Kino: Dune Part 3": "Cinema: Dune Part 3",
  "Klavier": "Piano",
  "Kleeblatt": "Clover",
  "Kletterhalle K1": "K1 climbing gym",
  "Klettern & Berge": "Climbing & mountains",
  "Klettern Rheintal": "Rheintal climbing",
  "Kletterseil": "Climbing rope",
  "Koala": "Koala",
  "Kochabend": "Cooking night",
  "Kochen": "Cooking",
  "Kochen draußen": "Outdoor cooking",
  "Koffer": "Suitcase",
  "Kohle": "Charcoal",
  "Kohle nicht vergessen": "Don't forget the charcoal",
  "Kohle und Snacks bring ich mit": "I'll bring charcoal and snacks",
  "Komet": "Comet",
  "Komme selbst": "On my own",
  "Kommen selbst: {namen}": "On their own: {namen}",
  "Kommend": "Upcoming",
  "Konfetti": "Confetti",
  "Königsblau": "Royal blue",
  "Konsole": "Console",
  "Konto": "Account",
  "Konto löschen": "Delete account",
  "Konzert Kammgarn": "Gig at Kammgarn",
  "Konzerte": "Concerts",
  "Kopfhörer": "Headphones",
  "Kopieren": "Copy",
  "Kopieren ging nicht": "Couldn’t copy",
  "Kopiert": "Copied",
  "Koralle": "Coral",
  "Kosten": "Cost",
  "Kosten {an}optional{aus}": "Cost {an}optional{aus}",
  "kostenlos": "free",
  "Kreuzfahrtschiff": "Cruise ship",
  "Kroatien": "Croatia",
  "Krone": "Crown",
  "Kühlbox": "Cool box",
  "Kultur & Events": "Culture & events",
  "Kürbis": "Pumpkin",
  "Kurz warten, dann erneut vorschlagen": "Wait a moment, then suggest again",
  "Kurzcode": "Short code",
  "Kurzcode · gerade eben": "Short code · just now",
  "kurze Runde": "quick dip",
  "Kurze Runde im See — danach gemeinsam Kaffee.": "Quick dip in the lake — then coffee together.",
  "Kurze Runde im See, danach Kaffee": "Quick dip in the lake, coffee after",
  "Kurzer Ton und Vibration, wenn etwas ankommt, während Crew offen ist": "A short sound and vibration when something arrives while Crew is open",
  "Kurzfilmnacht": "Short film night",
  "Label": "Label",
  "Label · frei tippbar": "Label · type anything",
  "Lächelnd": "Smiling",
  "Lädt dich ein · Kino Do": "Inviting you · cinema Thu",
  "lädt ein": "host",
  "Lage nicht freigegeben": "Location not shared",
  "Laptop": "Laptop",
  "Laufen": "Running",
  "Laufrunde am See": "Run by the lake",
  "läuft": "on now",
  "läuft gerade": "happening now",
  "Lautsprecher": "Speaker",
  "Lavendel": "Lavender",
  "Leinwand": "Screen",
  "Leiter": "Ladder",
  "Lernen": "Learning",
  "Lesen": "Reading",
  "Lesestand merken": "Mark as read",
  "Lieber nicht": "Rather not",
  "Limette": "Lime",
  "Link geteilt · gestern": "Link shared · yesterday",
  "Link schicken": "Send link",
  "Liste": "List",
  "Liste · {n}": "List · {n}",
  "Liste übernommen · {wer}": "Added to list · {wer}",
  "Listenpunkt erstellen": "Add list item",
  "Lizenz: {lizenz}": "License: {lizenz}",
  "Loop": "Loop",
  "Loop · {n}. Mal": "Loop · #{n}",
  "Loop · {n}. Mal [erstes]": "Loop · #{n}",
  "Loop aktivieren": "Start Loop",
  "Loop aktiviert": "Loop started",
  "Loop bearbeiten": "Edit Loop",
  "Loop erstellen": "Create Loop",
  "Loop geändert": "Loop updated",
  "Loop gestoppt": "Loop stopped",
  "Loop speichern": "Save Loop",
  "Loop stoppen": "Stop Loop",
  "Loop stoppen?": "Stop Loop?",
  "Loop-Antwort speichern": "Save Loop response",
  "Loops": "Loops",
  "Los geht’s": "Let's go",
  "Löschen": "Delete",
  "Löschen hat nicht geklappt": "Couldn’t delete",
  "Löwe": "Lion",
  "Lust auf draußen": "Up for the outdoors",
  "Lust auf Essen": "Up for food",
  "Lust auf Kaffee": "Up for coffee",
  "Lust auf Sport": "Up for sports",
  "Lust zu chillen": "Up for chilling",
  "Lust?": "Up for?",
  "Magst du": "You like",
  "Manchmal": "Sometimes",
  "Manchmal verfügbar": "Sometimes available",
  "Markieren": "Mark",
  "Markierte Freunde": "Marked friends",
  "Markierung entfernen": "Remove mark",
  "Markierung entfernt": "Mark removed",
  "Mars": "Mars",
  "Maus": "Mouse",
  "Maximal drei beste Freunde": "Three best friends max",
  "Meet": "Meet",
  "Meet abgesagt": "Meet cancelled",
  "Meet absagen": "Cancel Meet",
  "Meet absagen?": "Cancel Meet?",
  "Meet anlegen": "Plan a Meet",
  "Meet bei dir?": "Meet at yours?",
  "Meet festlegen": "Lock in Meet",
  "Meet nicht gefunden": "Meet not found",
  "Meet öffnen": "Open Meet",
  "Meet senden": "Send Meet",
  "Meet veröffentlichen": "Publish Meet",
  "Meet-Erinnerung": "Meet reminder",
  "Mein Auto ist startklar, ich kann fahren": "My car's ready to go, I can drive",
  "Meine Einladung": "My invitation",
  "Meine Meets": "My Meets",
  "Meinen Teil übernehmen": "Use my part",
  "Melden": "Report",
  "Melden und {name} blockieren": "Report and block {name}",
  "Menü": "Menu",
  "Mikrofon": "Mic",
  "Mindestens 8 Zeichen.": "At least 8 characters.",
  "Mindestens 8 Zeichen. Deinen Namen fragen wir gleich danach.": "At least 8 characters. We'll ask your name right after.",
  "Mindestens eine Person": "At least one person",
  "Minute": "Minute",
  "mit {namen}": "with {namen}",
  "mit {namen} +{n}": "with {namen} +{n}",
  "Mit deinem Desteny-Konto anmelden": "Sign in with your Desteny account",
  "Mit deinem Standort — nur für Vorschläge": "Uses your location — only for ideas",
  "Mit Desteny-Konto anmelden": "Sign in with Desteny account",
  "Mit diesem Desteny-Konto meldest du dich bei allen Apps von Desteny Development an.": "Use this Desteny account to sign in to every app by Desteny Development.",
  "mit dir": "with you",
  "mit E-Mail und Passwort": "with email and password",
  "Mit wem": "Who with",
  "Mitbringen": "To bring",
  "Mitbringen ändern": "Update bring list",
  "Mitbringen anlegen": "Add to bring list",
  "Mitbringen löschen": "Remove item",
  "Mitfahren": "Carpool",
  "Mitfahrt ins Meet übernehmen": "Add ride to the Meet",
  "Mitfahrt speichern": "Save ride",
  "Mitfahrt zuordnen": "Assign ride",
  "Mitglieder": "Members",
  "Mitnehmen": "Pick up",
  "Mitte von {n} Standort": "Centre of {n} location",
  "Mitte von {n} Standorten": "Centre of {n} locations",
  "Mitteilungen": "Notifications",
  "Mitteilungen auf diesem Gerät": "Notifications on this device",
  "Mitteilungen aufs Handy": "Notifications on your phone",
  "Mitteilungen aufs iPhone": "Notifications on your iPhone",
  "Mitteilungen einschalten": "Turn on notifications",
  "Mitteilungen sind an": "Notifications are on",
  "Mitteilungen sind vom System blockiert": "Notifications are blocked by the system",
  "Mittel": "So-so",
  "Möchten dich adden": "Want to add you",
  "Mohn": "Poppy",
  "Moment …": "One moment …",
  "Monat": "Month",
  "Monat [Einheit]": "month",
  "Monate [Einheit]": "months",
  "Mond": "Moon",
  "Monitor": "Monitor",
  "Morgen": "Tomorrow",
  "morgen, {zeit}": "tomorrow, {zeit}",
  "Motiv": "Icon",
  "Motorboot": "Motorboat",
  "Motorrad": "Motorbike",
  "Müde": "Sleepy",
  "Museum": "Museum",
  "Musik": "Music",
  "Muster": "Pattern",
  "nach dem Namen gewählt: {name}": "picked from the name: {name}",
  "Nach rechts": "To the right",
  "Nach unten": "Downwards",
  "Nachricht …": "Message …",
  "Nachricht gelöscht": "Message deleted",
  "Nachricht löschen": "Delete message",
  "Nachricht melden": "Report message",
  "Nachricht senden": "Send message",
  "Nächste Woche": "Next week",
  "Nächster Monat": "Next month",
  "Nacht": "Night",
  "Nah & draußen": "Close & outdoors",
  "Name": "Name",
  "Name der Ressource": "Item name",
  "Nerd": "Nerd",
  "Neu für euch": "New for you",
  "Neu laden": "Reload",
  "Neu: mindestens 8 Zeichen.": "New: at least 8 characters.",
  "Neue Crew": "New Crew",
  "Neue E-Mail-Adresse": "New email address",
  "Neue Idee": "New idea",
  "Neue Mitglieder fügen {namen} hinzu.": "{namen} add new members.",
  "Neue Mitglieder fügt {namen} hinzu.": "{namen} adds new members.",
  "Neue Ressource": "New item",
  "Neue Umfrage": "New poll",
  "Neuer Listenpunkt": "New list item",
  "Neuer Ordner": "New folder",
  "Neues Interesse": "New interest",
  "Neues Meet": "New Meet",
  "Neues Passwort": "New password",
  "Neues Passwort setzen": "Set a new password",
  "Neutral": "Neutral",
  "Nicht dabei": "Out",
  "Nicht für mich": "Not for me",
  "Nicht gut": "Not good",
  "Nicht mehr übernehmen": "Stop bringing this",
  "Nicht öffnen": "Don’t open",
  "Nichts": "Nothing",
  "Nichts gefunden": "Nothing found",
  "nichts geplant": "nothing planned",
  "Nichts geplant": "Nothing planned",
  "Nichts geplant.": "Nothing planned.",
  "Niederlande": "Netherlands",
  "niemand": "nobody",
  "Niemand": "Nobody",
  "Niemand blockiert": "Nobody blocked",
  "Niemand gefunden für „{suche}“": "No one found for “{suche}”",
  "noch {n} wählen": "pick {n} more",
  "Noch etwas": "Something else",
  "Noch fährt niemand.": "Nobody's driving yet.",
  "Noch kein Desteny-Konto? Erstellen": "No Desteny account yet? Create one",
  "Noch kein Verlauf.": "No history yet.",
  "Noch keine besten Freunde — das Zeichen gilt, sobald du jemanden markierst.": "No best friends yet — the mark applies as soon as you mark someone.",
  "Noch keine Crew": "No Crew yet",
  "Noch keine Freunde": "No friends yet",
  "Noch keine Umfrage — hier stimmt ihr gemeinsam ab.": "No poll yet — this is where you vote together.",
  "Noch keine Vorlagen gespeichert": "No templates saved yet",
  "Noch nichts": "Nothing yet",
  "Noch nichts auf der Liste — hier steht, wer was mitbringt.": "Nothing on the list yet — this is where you see who's bringing what.",
  "Noch nichts drauf — schreib den ersten Punkt.": "Nothing on it yet — add the first item.",
  "Noch nichts gemeinsam erlebt": "Nothing done together yet",
  "Noch nichts geplant": "Nothing planned yet",
  "Noch nichts zusammen erlebt": "Nothing done together yet",
  "Noch ohne Angabe: {namen}": "Not said yet: {namen}",
  "Nochmal": "Try again",
  "Norwegen": "Norway",
  "Notiz": "Note",
  "Notiz (optional)": "Note (optional)",
  "Notiz hinzufügen": "Add note",
  "Nur {wer} sieht {name}.": "Only {wer} can see {name}.",
  "Nur Admins können Personen hinzufügen": "Only admins can add people",
  "Nur aktiv": "Active only",
  "Nur das Meet ansehen": "Just view the Meet",
  "Nur der Organisator kann absagen": "Only the organiser can cancel",
  "Nur der Organisator kann festlegen": "Only the organiser can lock it in",
  "Nur die Aktivität übernommen": "Only the activity carried over",
  "Nur die grobe Umgebung — die genaue Adresse erst nach Zustimmung.": "Just the rough area — the exact address once they agree.",
  "nur dieses Feld offen": "only this is still open",
  "Nur du siehst {name}.": "Only you can see {name}.",
  "Nur eigene Vorschläge": "Only your own suggestions",
  "Nur Freunde lassen sich hinzufügen": "You can only add friends",
  "Nur für dich": "Just for you",
  "Nur für dich — niemand sonst sieht deine Antwort.": "Just for you — nobody else sees your answer.",
  "Nur für dich sichtbar": "Only visible to you",
  "Nur ich": "Only me",
  "nur kostenlos": "free only",
  "Nur leere Entwürfe": "Only empty drafts",
  "Nur mit Konto": "Needs an account",
  "Nur vom Home-Bildschirm aus": "Only from the Home Screen",
  "Nuss": "Hazel",
  "Ocker": "Ochre",
  "offen": "TBC",
  "Offen": "Undecided",
  "Öffnen": "Open",
  "oft": "often",
  "Oft gemacht": "An old favourite",
  "Ohne Eingabe steht neben dem Namen nur der Name.": "Leave it empty and just the name shows.",
  "Ohne feste Aktivität": "No set activity",
  "ohne Limit": "no limit",
  "Ohne Meet": "No Meet",
  "ohne Meet, aktiv oder kommend": "no Meet, active or upcoming",
  "Ohne Netz lässt sich kein Ort wählen": "You can't pick a place offline",
  "ohne Standort": "no location",
  "ohne Standort — selbst absprechen": "no location — sort it out directly",
  "ohne Standortfreigabe": "without location access",
  "Ohne Standortfreigabe geht es nicht automatisch — „Auf Karte wählen\" bleibt offen. Deine allgemeine Standort-Einstellung bleibt unverändert.": "Without location access it can't be automatic — “Pick on map” is still there. Your general location setting stays as it is.",
  "Okay": "OK",
  "Oktopus": "Octopus",
  "Oldtimer": "Vintage car",
  "Open-Air Kino": "Open-air cinema",
  "Oper unter freiem Himmel — früh buchen, nur bei gutem Wetter.": "Open-air opera — book early, good weather only.",
  "Option {n}": "Option {n}",
  "Option 1": "Option 1",
  "Option 2": "Option 2",
  "Optionen": "Options",
  "Orange": "Orange",
  "Ordner": "Folder",
  "Ordner anlegen": "Create folder",
  "Ordner erstellen": "Create folder",
  "Original": "original",
  "Original bleibt wählbar": "Original stays an option",
  "Ort": "Place",
  "ORT": "PLACE",
  "Ort — Zustimmung steht aus": "Place — waiting for OK",
  "Ort abgelehnt": "Place declined",
  "Ort anfragen": "Request place",
  "Ort angefragt bei {name} — Zustimmung steht noch aus.": "Asked {name} about their place — waiting for a yes.",
  "Ort angefragt bei der Person — Zustimmung steht noch aus.": "Asked about their place — waiting for a yes.",
  "Ort bei {name} angefragt — die Adresse erscheint erst nach der Zustimmung.": "Asked to use {name}'s place — the address only shows once they agree.",
  "Ort bei der gefragten Person angefragt — die Adresse erscheint erst nach der Zustimmung.": "Place requested — the address only shows once they agree.",
  "Ort bei dir angefragt — die Adresse erscheint erst nach der Zustimmung.": "Someone's asked to use your place — the address only shows once you agree.",
  "Ort blieb offen": "No place was set",
  "Ort entfernen": "Remove place",
  "Ort freigegeben": "Place shared",
  "Ort hinzufügen": "Add place",
  "Ort offen": "Place TBC",
  "Ort suchen": "Find a place",
  "Ort suchen …": "Search places …",
  "Ort übernehmen": "Use this place",
  "Ort übernommen": "Place carried over",
  "Ort und Personen übernommen": "Place and people carried over",
  "Ort und Zeit übernommen": "Place and time carried over",
  "Ort, Zeit und Personen übernommen": "Place, time and people carried over",
  "Orte in deiner Nähe zeigen": "Show places near you",
  "Ortsanfrage beantworten": "Answer place request",
  "Österreich": "Austria",
  "Panda": "Panda",
  "Panorama oben": "Views from the top",
  "Park, weicher Rasen, ab 4 Personen": "Park, soft grass, 4+ people",
  "Party": "Party",
  "Passt": "Great",
  "Passt zu euch": "Right for you",
  "Passt zu: {interesse}": "Matches: {interesse}",
  "Passwort": "Password",
  "Passwort ändern": "Change password",
  "Passwort anzeigen": "Show password",
  "Passwort festlegen": "Choose a password",
  "Passwort geändert.": "Password changed.",
  "Passwort verbergen": "Hide password",
  "Passwort vergessen?": "Forgot password?",
  "Passwort wiederholen": "Repeat password",
  "Pasta": "Pasta",
  "Pasta danach": "Pasta after",
  "Pasta für alle — wer die größte Küche hat, lädt ein.": "Pasta for everyone — whoever has the biggest kitchen hosts.",
  "Pasta für alle, zusammen in einer Küche": "Pasta for everyone, all in one kitchen",
  "Pavillon": "Gazebo",
  "PC": "PC",
  "Perfekt, bis 21 Uhr geblieben": "Perfect, stayed till 21:00",
  "Person blockieren": "Block person",
  "Person blockiert": "Person blocked",
  "Person ist kein Mitglied": "That person isn't a member",
  "Person ist nicht mehr blockiert": "Person unblocked",
  "Personen · {n}": "People · {n}",
  "Personen hinzufügen": "Add people",
  "Personen übernommen": "People carried over",
  "Personen-Kapazität": "Capacity",
  "Petrol": "Teal",
  "Pfänder": "Pfänder",
  "Pfänder-Runde": "Pfänder walk",
  "Picknick": "Picnic",
  "Picknickkorb": "Picnic basket",
  "Pilz": "Mushroom",
  "Pinguin": "Penguin",
  "Pink": "Pink",
  "Pizza": "Pizza",
  "Pizza am Hafen": "Pizza by the harbour",
  "Pizza bei Mira": "Pizza at Mira's",
  "Planen": "Plan",
  "Plattenspieler": "Record player",
  "Plätze für Mitfahrer": "Seats for riders",
  "Polen": "Poland",
  "Pool": "Pool",
  "Portugal": "Portugal",
  "Privat": "Private",
  "Privat: {namen}": "Private: {namen}",
  "Private Ressource": "Private item",
  "Private Ressourcen sehen": "Who sees private items",
  "Privatsphäre & Freigaben": "Privacy & sharing",
  "Probe-Mitteilung senden": "Send a test notification",
  "Profil": "Profile",
  "Profil ›": "Profile ›",
  "Profil bearbeiten": "Edit profile",
  "Profil gespeichert": "Profile saved",
  "Profil speichern": "Save profile",
  "Profilbild": "Profile picture",
  "Profilbild ändern": "Change profile picture",
  "Profilbild gestalten": "Create profile picture",
  "Profilbild übernommen": "Profile picture updated",
  "Profilbild von {name}": "{name}'s profile picture",
  "Profilbild von {name} groß ansehen": "View {name}'s profile picture",
  "Propellerflugzeug": "Propeller plane",
  "PS5": "PS5",
  "Punkte": "Dots",
  "QR-Code scannen": "Scan QR code",
  "Quelle öffnen": "View source",
  "Raclette": "Raclette",
  "Radfahren": "Cycling",
  "Radtouren": "Bike rides",
  "Rakete": "Rocket",
  "Rallyeauto": "Rally car",
  "Rasenmäher": "Lawnmower",
  "Raum": "Room",
  "Raum {raum} nicht auflösbar": "Couldn't resolve room {raum}",
  "Raumschiff": "Spaceship",
  "regelmäßig": "regularly",
  "Regen angesagt": "Rain forecast",
  "Regenbogen": "Rainbow",
  "Rennwagen": "Race car",
  "Ressource entfernen": "Remove item",
  "Ressource entfernt": "Item removed",
  "Ressource gibt es schon": "You've already got that item",
  "Ressource hinzufügen": "Add item",
  "Ressource hinzugefügt": "Item added",
  "Ressourcen": "Things to share",
  "Ressourcen speichern": "Save stuff",
  "Richtung": "Direction",
  "Ringe": "Rings",
  "Roboter": "Robot",
  "Rosé": "Rose",
  "Rot": "Red",
  "Route": "Route",
  "Route mit Abholungen": "Route with pick-ups",
  "Route mit Abholungen in {karte} öffnen": "Open route with pick-ups in {karte}",
  "Route öffnen": "Open route",
  "Rückgängig": "Undo",
  "Rucksack": "Rucksack",
  "Ruhe & Kreatives": "Calm & creative",
  "Salbei": "Sage",
  "Samstag": "Saturday",
  "Satellit": "Satellite",
  "Saturn": "Saturn",
  "Scannen geht hier nicht — gib den Code unten ein.": "Scanning isn't possible here — enter the code below.",
  "Schaf": "Sheep",
  "Schalte den Standort oben ein, um zu wählen, wer ihn sieht.": "Turn on location above to choose who sees it.",
  "Schau in dein Postfach. Der Link ist eine Stunde gültig.": "Check your inbox. The link's valid for an hour.",
  "Schiffe": "Boats & ships",
  "Schlafsack": "Sleeping bag",
  "Schließen": "Close",
  "Schlitten": "Sledge",
  "Schnee": "Snow",
  "Schnell startklar": "Quick to set up",
  "Schnelle Runde im Park — Ball und Netz mitbringen.": "Quick game in the park — bring a ball and net.",
  "Schon ein Desteny-Konto? Anmelden": "Already have a Desteny account? Sign in",
  "Schon gespeichert · {n}": "Already saved · {n}",
  "Schräg nach links unten": "Diagonal, down to the left",
  "Schräg nach rechts unten": "Diagonal, down to the right",
  "Schubkarre": "Wheelbarrow",
  "Schweden": "Sweden",
  "Schwein": "Pig",
  "Schweiz": "Switzerland",
  "Schwester": "Sister",
  "Schwimmen": "Swimming",
  "Schwimmen im See": "Lake swim",
  "See": "Lake",
  "See & Chill": "Lake & Chill",
  "See, Wiese und Pizza direkt daneben": "Lake, lawn and pizza right next door",
  "Seebühne": "Seebühne",
  "Seebühne: Carmen": "Seebühne: Carmen",
  "Segelboot": "Sailboat",
  "Sehen, wer Zeit hat. Und daraus etwas machen.": "See who's free. And make something of it.",
  "seit {zeit}": "since {zeit}",
  "Senden": "Send",
  "Serbien": "Serbia",
  "Serien": "Series",
  "Servus! Am Wochenende was am Damm machen?": "Hiya! Fancy doing something at the Damm this weekend?",
  "Shopping": "Shopping",
  "Sie gilt, sobald du den Link in der Mail angeklickt hast.": "It kicks in once you've clicked the link in the email.",
  "Sieht gleich aus wie das Zeichen deiner besonderen Person.": "Looks the same as your special person's mark.",
  "Ski": "Skis",
  "Slackline": "Slackline",
  "Smaragd": "Emerald",
  "Snowboard": "Snowboard",
  "So kommen Mitteilungen von Crew an.": "This is how notifications from Crew arrive.",
  "So sehen dich deine Freunde. Änderbar im Profil.": "This is what your friends see. You can change it in your profile.",
  "So sieht dich deine Crew": "How your Crew sees you",
  "So sieht eure Gruppe aus": "This is how your group looks",
  "Social": "Social",
  "Social öffnen": "Open social",
  "Sofa": "Sofa",
  "Sommer": "Summer",
  "Sonne": "Sun",
  "Sonnenaufgang Pfänder": "Pfänder sunrise",
  "Sonnenbrille": "Sunglasses",
  "Sonnenschirm": "Parasol",
  "Spam": "Spam",
  "Spanien": "Spain",
  "Später": "Later",
  "Später — direkt zu Crew": "Later — straight into Crew",
  "Spätestens {zeit}": "{zeit} at the latest",
  "Spazieren": "Walks",
  "Speichern": "Save",
  "Speichern und weiter": "Save and continue",
  "Spiele": "Games",
  "Spieleabend": "Games night",
  "Spieleabend bei Noah": "Games night at Noah's",
  "Spielesammlung": "Game collection",
  "Spikeball": "Spikeball",
  "Spikeball im Park": "Spikeball in the park",
  "Spikeball-Turnier": "Spikeball tournament",
  "Spontan treffen": "Meet up now",
  "Spontanes Treffen": "Spontaneous meet",
  "Sport": "Sport",
  "Sport & draußen": "Sport & outdoors",
  "Sport-Runde": "Sports squad",
  "Sportwagen": "Sports car",
  "Sprache": "Language",
  "Standard": "Default",
  "Standard 00:00": "Default 00:00",
  "Standard: aus": "Default: off",
  "Stände am Dorfplatz und Livemusik": "Stalls on the village square and live music",
  "Stände am Dorfplatz und Livemusik — Eintritt frei, Gläser gegen Pfand.": "Stalls on the village square and live music — free entry, deposit on glasses.",
  "Standort": "Location",
  "Standort ansehen: {ort}": "View location: {ort}",
  "Standort für Vorschläge": "Location for suggestions",
  "Standort gerade nicht verfügbar": "Location not available right now",
  "Standort nicht erlaubt — du kannst ihn in den Einstellungen deines Geräts freigeben.": "Location not allowed — you can turn it on in your device settings.",
  "Standort nicht mehr teilen": "Stop sharing location",
  "Standort senden?": "Send location?",
  "Standort teilen": "Share location",
  "Standort teilen mit": "Share location with",
  "Standort verwenden": "Use location",
  "Standort wird abgefragt …": "Getting your location …",
  "Stativ": "Tripod",
  "Statt „{titel}\" — oder als Alternative dazu?": "Instead of “{titel}” — or as an alternative?",
  "Statt „{titel}\" und {n} weitere — oder als Alternative dazu?": "Instead of “{titel}” and {n} more — or as an alternative?",
  "Stattdessen blockieren und melden": "Block and report instead",
  "Steht nichts Passendes dabei?": "Nothing that fits?",
  "Stern": "Star",
  "Sterne": "Stars",
  "Stimme setzen": "Cast vote",
  "Stimme zurücknehmen": "Take back vote",
  "Strandbad": "Strandbad",
  "Strandbad + Pizza": "Strandbad + pizza",
  "Strandbad Bregenz": "Strandbad Bregenz",
  "Streifen": "Stripes",
  "Stunde": "Hour",
  "Suche läuft …": "Searching …",
  "Suche leeren": "Clear search",
  "Suche oben — oder tippe auf die Karte.": "Search above — or tap the map.",
  "Suchen …": "Search …",
  "Supabase-Bibliothek nicht ladbar": "Couldn't load the Supabase library",
  "Surfbrett": "Surfboard",
  "Symbol": "Icon",
  "Symbol ändern": "Change icon",
  "Symbol für {name}": "Icon for {name}",
  "Symbol oder Emoji": "Icon or emoji",
  "Symbol wählen": "Choose icon",
  "System": "System",
  "Tablet": "Tablet",
  "Tage": "Days",
  "Tanne": "Fir",
  "Taube": "Dusty blue",
  "Technik": "Tech",
  "Teilen": "Share",
  "Teilnahme absagen": "Can't make it",
  "Teilnahme speichern": "Save response",
  "Teilnehmende": "Participants",
  "Teilnehmende aktualisiert": "Participants updated",
  "Teilnehmende ändern": "Edit participants",
  "Teilnehmende bearbeiten": "Edit participants",
  "Temporäre Räume": "Temporary rooms",
  "Termine · {n}": "Dates · {n}",
  "Text: {quelle}": "Text: {quelle}",
  "Thermoskanne": "Flask",
  "Tickets": "Tickets",
  "Tickets & Infos": "Tickets & info",
  "Tiere": "Animals",
  "Tiger": "Tiger",
  "Tischtennis": "Table tennis",
  "Titel": "Title",
  "Töne": "Sounds",
  "Top — ich fahr, 3 Plätze frei": "Great — I'll drive, 3 seats free",
  "Tränen lachen": "Tears of joy",
  "Treffen planen": "Plan a get-together",
  "Treffpunkt bleibt Fluh, oder?": "Still meeting at Fluh, right?",
  "Trinken": "Drinks",
  "Trinken gehen": "Drinks",
  "Tschechien": "Czechia",
  "Türkei": "Turkey",
  "Türkis": "Turquoise",
  "U-Boot": "Submarine",
  "über {name}": "via {name}",
  "über Link": "via link",
  "Übernehmen": "Apply",
  "Übernehmen können Fahrer, Mitfahrer oder wer das Meet erstellt hat.": "Drivers, riders or whoever created the Meet can use it.",
  "übernommen": "claimed",
  "UFO": "UFO",
  "Uhr": "Clock",
  "Ukraine": "Ukraine",
  "Umfrage": "Poll",
  "Umfrage anlegen": "Create poll",
  "Umfrage bei „{titel}“": "Poll added to “{titel}”",
  "Umfrage erstellen": "Create poll",
  "Umfrage im Raum": "Poll posted in room",
  "Umfrage im Raum anlegen": "Create poll in room",
  "Umfragen": "Polls",
  "Umfragen · {n}": "Polls · {n}",
  "Umkreis": "Radius",
  "Umkreis · bis {km} km · {n} Ort": "Radius · up to {km} km · {n} place",
  "Umkreis · bis {km} km · {n} Orte": "Radius · up to {km} km · {n} places",
  "Umkreis entfernen": "Remove radius",
  "Unangemessene Inhalte": "Inappropriate content",
  "Unbekannt": "Unknown",
  "Unbekannte Meet-Teilnehmende sehen": "Unknown Meet participants see",
  "Ungarn": "Hungary",
  "Ungefähr, nur auf diesem Gerät gespeichert.": "Approximate, stored only on this device.",
  "Unterwegs": "Out & about",
  "Updates & Zusammenfassungen": "Updates & summaries",
  "USA": "USA",
  "Verbunden": "Connected",
  "verfügbar · für · wer": "available · for · who",
  "Verfügbarkeit": "Availability",
  "Vergessen": "Forget",
  "Vergrößern": "Zoom in",
  "Verkehrsflugzeug": "Airliner",
  "Verkleinern": "Zoom out",
  "Verlassen": "Leave",
  "Verlauf": "History",
  "Verliebt": "In love",
  "Verschoben": "Postponed",
  "Verwalten": "Manage",
  "Violett": "Violet",
  "Vogel": "Bird",
  "voll": "full",
  "Voll": "Full",
  "Volleyball": "Volleyball",
  "Vollständiges Profil": "Full profile",
  "Vom System blockiert": "Blocked by the system",
  "Von": "From",
  "Von der Mitte aus": "From the centre",
  "Von dir gesendet": "Sent by you",
  "Von mir gesendet · {n}": "Sent by me · {n}",
  "Von und Bis sind gleich": "From and to are the same",
  "vor {n} min": "{n} min ago",
  "vor {n} Minute": "{n} minute ago",
  "vor {n} Minuten": "{n} minutes ago",
  "vor {n} Stunde": "{n} hour ago",
  "vor {n} Stunden": "{n} hours ago",
  "Vorheriger Monat": "Previous month",
  "Vorige Woche": "Previous week",
  "Voriger Monat": "Previous month",
  "Vorlage gespeichert": "Template saved",
  "Vorname": "First name",
  "Vorschlag": "Suggestion",
  "Vorschlag ändern": "Edit suggestion",
  "Vorschlag anlegen": "Add suggestion",
  "Vorschlag ausblenden": "Hide suggestion",
  "Vorschlag bearbeiten": "Edit suggestion",
  "Vorschlag entfernen": "Remove suggestion",
  "Vorschlag für „{titel}\": {idee}": "Suggestion for “{titel}”: {idee}",
  "Vorschlag für {titel}": "Suggestion for {titel}",
  "Vorschlag gesendet": "Suggestion sent",
  "Vorschlag gespeichert": "Suggestion saved",
  "Vorschlag senden": "Send suggestion",
  "Vorschlag übernehmen": "Use suggestion",
  "Vorschlag übernommen": "Suggestion used",
  "Vorschlag: {idee}": "Suggestion: {idee}",
  "Vorschlag: {name} holt dich ab": "Suggestion: {name} picks you up",
  "Vorschlagen": "Suggest",
  "VR-Brille": "VR headset",
  "Wähl mindestens einen Tag": "Pick at least one day",
  "Wähl zuerst, wie es war": "First pick how it was",
  "Wähle oben, bei wem ihr euch trefft.": "Pick whose place you're meeting at above.",
  "Wählen": "Choose",
  "Wal": "Whale",
  "Wald": "Forest",
  "Wandern": "Hiking",
  "Wandern am Pfänder": "Hiking on the Pfänder",
  "Wandern Pfänder": "Pfänder hike",
  "Wann": "When",
  "Wann passt es?": "When works?",
  "Wartet": "Pending",
  "Wartet auf Bestätigung: {email}": "Waiting for confirmation: {email}",
  "Warum meldest du?": "Why are you reporting this?",
  "Was Crew gelernt hat": "What Crew has learnt",
  "Was die Vorlage mitnimmt": "What the template keeps",
  "Was es gekostet hat": "What it cost",
  "Was habt ihr vor?": "What are you up to?",
  "Was ihr gemacht habt": "What you did",
  "Was kochen wir?": "What are we cooking?",
  "Was machen wir?": "What are we doing?",
  "Was machen?": "What to do?",
  "Was machst du gern?": "What do you like doing?",
  "Was soll jemand mitbringen?": "What should someone bring?",
  "Was war los?": "What happened?",
  "Was?": "What?",
  "Waschbär": "Raccoon",
  "Wasser & Schnee": "Water & snow",
  "Wasser hat 24 Grad 🌊": "Water's 24 degrees 🌊",
  "Wasserflugzeug": "Seaplane",
  "Website": "Website",
  "Wechseln": "Switch",
  "Weinfest": "Wine festival",
  "Weinfest Lochau": "Lochau wine festival",
  "Weiter": "Continue",
  "Weiter bearbeiten": "Keep editing",
  "weiter zu": "continue to",
  "Weitere": "Other",
  "Weitere Freunde": "More friends",
  "Weitere Interessen": "More interests",
  "Welle": "Wave",
  "Wellen": "Waves",
  "Weltall": "Space",
  "Weniger anzeigen": "Show less",
  "Wenn dich jemand anstupst": "When someone nudges you",
  "wer bringt was mit": "who brings what",
  "Wer fährt?": "Who's driving?",
  "Wer hätte Samstag Bock auf den Pfänder?": "Who's up for the Pfänder on Saturday?",
  "Wer ist frei? Was machen wir?": "Who's free? What are we doing?",
  "Wer schreibt, wer frei ist": "Who's writing, who's free",
  "Werkzeug": "Tools",
  "Werkzeug & Garten": "Tools & garden",
  "Wetter soll top werden, viel Sonne": "Weather's meant to be great, loads of sun",
  "Wie das Gerät": "Same as device",
  "Wie heißt du?": "What's your name?",
  "Wie heißt ihr?": "What's your Crew called?",
  "Wie kommst du hin?": "How are you getting there?",
  "wie oft gemeinsam": "how often together",
  "Wie oft gerade?": "How often these days?",
  "Wie schaut’s Donnerstag aus?": "How's Thursday looking?",
  "Wie war {titel}?": "How was {titel}?",
  "Wie war der See gestern?": "How was the lake yesterday?",
  "Wie war's?": "How was it?",
  "Wie war’s?": "How was it?",
  "Wieder möglich in {zeit}": "Try again in {zeit}",
  "Wieder zeigen": "Show again",
  "Wiederholung": "Repeats",
  "Wiese am See mit Sprungturm und Kiosk — Eintritt frei.": "Lakeside lawn with a diving tower and kiosk — free entry.",
  "Wiese oder Grillplatz, Grill und Kohle mitnehmen": "Lawn or BBQ area, bring a BBQ and charcoal",
  "Wikingerschiff": "Viking ship",
  "Wir haben an {email} eine Bestätigung geschickt. Die Adresse gilt, sobald du den Link angeklickt hast.": "We've sent a confirmation to {email}. The new address kicks in once you've clicked the link.",
  "Wir haben dir eine E-Mail geschickt. Bestätige sie und melde dich dann an.": "We've sent you an email. Confirm it, then sign in.",
  "Wir haben dir einen Link an {email} geschickt.": "We've sent a link to {email}.",
  "wird gebraucht": "needed",
  "Wird mit eingeladen": "Will be invited too",
  "Wird nachgeschlagen …": "Looking it up …",
  "Woche": "Week",
  "Woche [Einheit]": "week",
  "Wochen [Einheit]": "weeks",
  "Wochenende": "Weekend",
  "Wolf": "Wolf",
  "Womit fängst du an?": "Where do you want to start?",
  "Woran lag’s genau?": "What made it that way?",
  "Worauf hast du Lust?": "What are you up for?",
  "Worüber soll abgestimmt werden?": "What should people vote on?",
  "Yoga": "Yoga",
  "z. B. Anhänger": "e.g. Trailer",
  "z. B. Freundin": "e.g. Partner",
  "z. B. Padel": "e.g. Padel",
  "Zeichen": "Mark",
  "Zeichen für beste Freunde": "Mark for best friends",
  "Zeichen für beste Freunde gespeichert": "Mark for best friends saved",
  "Zeile entfernen": "Remove line",
  "Zeit": "Time",
  "Zeit · {n} Vorschlag": "Time · {n} suggestion",
  "Zeit · {n} Vorschläge": "Time · {n} suggestions",
  "Zeit abstimmen": "Vote on time",
  "Zeit festgelegt": "Time locked in",
  "Zeit offen": "Time TBC",
  "Zeit übernommen": "Time carried over",
  "Zeit und Personen übernommen": "Time and people carried over",
  "Zeit vorgeschlagen": "Time suggested",
  "Zeit vorschlagen": "Suggest a time",
  "Zeiten entfernen": "Remove times",
  "Zeiten entfernt": "Times removed",
  "Zeiten gespeichert": "Times saved",
  "Zeiten hinzufügen": "Add times",
  "Zeiten hinzugefügt": "Times added",
  "Zeitraum": "Time range",
  "Zeitvorschläge ansehen": "See time suggestions",
  "Zelt": "Tent",
  "Ziehen": "Drag",
  "Ziehen zum Verschieben · Mausrad oder Regler zum Zoomen": "Drag to move · scroll wheel or slider to zoom",
  "Ziehen zum Verschieben · mit zwei Fingern zoomen": "Drag to move · pinch to zoom",
  "Ziel": "Destination",
  "Ziel wählen": "Pick where it goes",
  "Zielflagge": "Checkered flag",
  "Zoom": "Zoom",
  "Zu besonderer Person wechseln?": "Switch to special person?",
  "Zu bestem Freund wechseln?": "Switch to best friend?",
  "Zu diesem Konto gibt es keine E-Mail-Adresse.": "This account has no email address.",
  "Zu dieser E-Mail gibt es schon ein Konto — melde dich an": "There's already an account with this email — sign in",
  "Zu viele Versuche. Bitte später noch einmal.": "Too many attempts. Please try again later.",
  "Zuerst Freunde<br>hinzufügen": "Add friends<br>first",
  "Zuhause": "Home",
  "Zuhause & Alltag": "Home & everyday",
  "Zuhause, ab 4 Personen am besten": "At home, best with 4+",
  "Zuhause, ab 4 Personen am besten — ein paar Spiele reichen.": "At home, best with 4+ — a few games are all you need.",
  "Zum Home-Bildschirm": "Add to Home Screen",
  "zum Namen passt nichts — wähl unten selbst": "nothing matches the name — pick one below",
  "Zur Crew": "Go to Crew",
  "Zurück": "Back",
  "Zurück zu meiner Einladung": "Back to my invitation",
  "Zurück zur Anmeldung": "Back to sign-in",
  "Zurückgenommen · wieder in {n} min": "Withdrawn · again in {n} min",
  "Zurücksetzen": "Reset",
  "Zurücksetzen fehlgeschlagen: {fehler}": "Reset failed: {fehler}",
  "Zurückstupsen": "Nudge back",
  "Zurückziehen": "Withdraw",
  "Zusage geändert": "Response updated",
  "Zusage offen": "Still undecided",
  "zusammen kochen": "cook together",
  "Zusammenfassen": "Summarise",
  "Zustimmung steht aus": "Waiting for OK",
  "Zustimmung steht aus · {ort}": "Waiting for OK · {ort}",
  "Zwei Antworten braucht es mindestens": "You need at least two answers",
  "Zwei Farben, die ineinander übergehen": "Two colours blending into each other",
  "Zweite Farbe": "Second colour",
};
