// Übersetzungen (es). Schlüssel = deutscher Satz aus dem Quelltext, siehe web/core/sprache.js.
// Nicht von Hand zusammenführen: scripts/sprachen-bauen.mjs. Prüfen: node scripts/sprachen-pruefen.mjs
export default {
  "„{name}\" hinzugefügt": "«{name}» añadido",
  "„{titel}\" ausgeblendet": "Has ocultado «{titel}»",
  "„{titel}“ hat einen eigenen Gruppenchat mit allen, die dabei sind. Du verlässt dafür den Chat mit {name}.": "«{titel}» tiene su propio chat de grupo con todos los que van. Para ello sales del chat con {name}.",
  "„{titel}“ läuft in der Gruppe {gruppe}. Dort schreibt ihr alle zusammen — du verlässt dafür den Chat mit {name}.": "«{titel}» es en el grupo {gruppe}. Allí escribís todos juntos; para ello sales del chat con {name}.",
  "„Daheim\" hat keine Karte — es gibt dort nichts zu verorten.": "«En casa» no tiene mapa — no hay nada que ubicar.",
  "{a} und {b} sind auch frei": "{a} y {b} también están libres",
  "{a} und {b} warten auf Antwort": "{a} y {b} esperan respuesta",
  "{a}, {b} und {n} weitere sind auch frei": "{a}, {b} y {n} más también están libres",
  "{a}, {b} und {n} weitere warten auf Antwort": "{a}, {b} y {n} más esperan respuesta",
  "{a}, {b} und eine weitere Person sind auch frei": "{a}, {b} y una persona más también están libres",
  "{aktion} hat nicht geklappt": "No ha funcionado: {aktion}",
  "{an}alle{aus}{rad}{an}Jahr{aus}": "{an}cada{aus}{rad}{an}año{aus}",
  "{an}alle{aus}{rad}{an}Jahre{aus}": "{an}cada{aus}{rad}{an}años{aus}",
  "{an}alle{aus}{rad}{an}Monat{aus}": "{an}cada{aus}{rad}{an}mes{aus}",
  "{an}alle{aus}{rad}{an}Monate{aus}": "{an}cada{aus}{rad}{an}meses{aus}",
  "{an}alle{aus}{rad}{an}Woche{aus}": "{an}cada{aus}{rad}{an}semana{aus}",
  "{an}alle{aus}{rad}{an}Wochen{aus}": "{an}cada{aus}{rad}{an}semanas{aus}",
  "{antwort} — deine Stimme": "{antwort} — tu voto",
  "{belegt} von {n} Platz": "{belegt} de {n} plaza",
  "{belegt} von {n} Plätzen": "{belegt} de {n} plazas",
  "{bereich} zuklappen": "Contraer {bereich}",
  "{frei}/{alle} frei": "{frei}/{alle} libres",
  "{h} Uhr": "{h}:00",
  "{n} dabei": "Van: {n}",
  "{n} frei": "Libres: {n}",
  "{n} Freund": "{n} amigo",
  "{n} Freund:in gewählt": "{n} amigo elegido",
  "{n} Freund:innen gewählt": "{n} amigos elegidos",
  "{n} Freunde": "{n} amigos",
  "{n} gemeinsame Crew ›": "{n} Crew en común ›",
  "{n} gemeinsame Crews ›": "{n} Crews en común ›",
  "{n} gemeinsame Freunde · über {name}": "{n} amigos en común · vía {name}",
  "{n} gewählt": "Elegidos: {n}",
  "{n} Idee": "{n} idea",
  "{n} Ideen": "{n} ideas",
  "{n} Loop": "{n} Loop",
  "{n} Loops": "{n} Loops",
  "{n} Meet": "{n} Meet",
  "{n} Meets": "{n} Meets",
  "{n} Min": "{n} min",
  "{n} Min.": "{n} min",
  "{n} Mitglied": "{n} miembro",
  "{n} Mitglied ›": "{n} miembro ›",
  "{n} Mitglieder": "{n} miembros",
  "{n} Mitglieder ›": "{n} miembros ›",
  "{n} neu — sie bekommen eine Einladung und denselben Meet-Chat.": "{n} personas nuevas — reciben una invitación y el mismo chat del Meet.",
  "{n} neu — sie bekommt eine Einladung und denselben Meet-Chat.": "{n} persona nueva — recibe una invitación y el mismo chat del Meet.",
  "{n} neue Nachricht": "{n} mensaje nuevo",
  "{n} neue Nachrichten": "{n} mensajes nuevos",
  "{n} offene Anfragen": "{n} solicitudes pendientes",
  "{n} Person": "{n} persona",
  "{n} Person eingeladen": "{n} persona invitada",
  "{n} Person hinzufügen": "Añadir {n} persona",
  "{n} Person ist jetzt in {crew}": "{n} persona ya está en {crew}",
  "{n} Personen": "{n} personas",
  "{n} Personen eingeladen": "{n} personas invitadas",
  "{n} Personen hinzufügen": "Añadir {n} personas",
  "{n} Personen sind jetzt in {crew}": "{n} personas ya están en {crew}",
  "{n} Platz frei": "{n} plaza libre",
  "{n} Plätze frei": "{n} plazas libres",
  "{n} Punkte bei „{titel}“": "{n} cosas en la lista de «{titel}»",
  "{n} Std": "{n} h",
  "{n} Std.": "{n} h",
  "{n} Stimme": "{n} voto",
  "{n} Stimmen": "{n} votos",
  "{n} suchen": "{n} buscan",
  "{n} suchen noch": "{n} aún buscan",
  "{n} sucht": "{n} busca",
  "{n} sucht noch": "{n} aún busca",
  "{n} Teilnehmende ›": "{n} participantes ›",
  "{n} teilnehmende Person ›": "{n} participante ›",
  "{n} Vorschlag": "{n} propuesta",
  "{n} Vorschläge": "{n} propuestas",
  "{n} Zuordnung ging nicht mehr": "{n} recogida ya no se pudo guardar",
  "{n} Zuordnungen gingen nicht mehr": "{n} recogidas ya no se pudieron guardar",
  "{n}× gewählt": "{n}× elegido",
  "{n}× nein": "{n}× no",
  "{n}× übergangen": "{n}× ignorado",
  "{name} absetzen": "Quitar a {name} de tu coche",
  "{name} angestupst · {wort}": "{name} te ha dado un toque · {wort}",
  "{name} aufgelöst": "Has disuelto {name}",
  "{name} bietet eine {an}Mitfahrt{aus} an": "{name} ofrece {an}plaza en su coche{aus}",
  "{name} blockieren?": "¿Bloquear a {name}?",
  "{name} blockiert": "Has bloqueado a {name}",
  "{name} bringt etwas mit": "{name} lleva algo",
  "{name} bringt’s": "Lo lleva {name}",
  "{name} entfernt": "Has quitado a {name}",
  "{name} erwähnt {wort}": "{name} menciona {wort}",
  "{name} fährt": "{name} conduce",
  "{name} fährt gerade nicht": "{name} no conduce ahora mismo",
  "{name} fährt noch nicht — du stehst bei „sucht noch“": "{name} aún no conduce — estás en «aún busca»",
  "{name} fragt, ob {titel} bei dir stattfinden kann. Deine Adresse sehen die anderen erst, wenn du zustimmst.": "{name} pregunta si {titel} puede ser en tu casa. Los demás solo verán tu dirección si aceptas.",
  "{name} hat angestupst": "{name} te dio un toque",
  "{name} hat dich angestupst · Lust auf etwas?": "{name} te ha dado un toque · ¿Te apetece algo?",
  "{name} hat dich zu Crew geholt.": "{name} te ha traído a Crew.",
  "{name} hatte dich angestupst": "{name} te había dado un toque",
  "{name} hätte Lust auf {wort}": "A {name} le apetece {wort}",
  "{name} holt {namen} ab": "{name} recoge a {namen}",
  "{name} ist auch frei": "{name} también está libre",
  "{name} ist gerade frei": "{name} está libre ahora",
  "{name} ist jetzt dein Freund": "Ahora {name} es tu amigo",
  "{name} ist jetzt in {crew}": "{name} ya está en {crew}",
  "{name} ist nicht mehr blockiert": "Has desbloqueado a {name}",
  "{name} ist nicht mehr dein:e Freund:in": "{name} ya no está en tus amigos",
  "{name} ist schon dein Freund": "Ya eres amigo de {name}",
  "{name} mitnehmen": "Llevar a {name}",
  "{name} sucht eine {an}Mitfahrgelegenheit{aus}": "{name} busca {an}quien le lleve{aus}",
  "{name} trägt gerade den goldenen Ring. Ein eigenes Zeichen ersetzt ihn — beides zusammen geht nicht.": "{name} lleva ahora el anillo dorado. Una marca propia lo sustituye — no se pueden tener los dos.",
  "{name} trägt gerade ein eigenes Zeichen („{label}\"). Der goldene Ring ersetzt es — beides zusammen geht nicht.": "{name} lleva ahora una marca propia («{label}»). El anillo dorado la sustituye — no se pueden tener las dos.",
  "{name} trägt gerade ein eigenes Zeichen. Der goldene Ring ersetzt es — beides zusammen geht nicht.": "{name} lleva ahora una marca propia. El anillo dorado la sustituye — no se pueden tener las dos.",
  "{name} und {n} weitere Person": "{name} y {n} persona más",
  "{name} und {n} weitere Personen": "{name} y {n} personas más",
  "{name} verlassen": "Has salido de {name}",
  "{name} verlassen?": "¿Salir de {name}?",
  "{name} wartet auf Antwort": "{name} espera respuesta",
  "{name}: {lust}": "{name}: {lust}",
  "{name}: {text}": "{name}: {text}",
  "{name}: frei ab {zeit}": "{name}: libre desde las {zeit}",
  "{name}: im Meet": "{name}: en un Meet",
  "{name}: im Meet · {titel}": "{name}: en un Meet · {titel}",
  "{namen} gibt's schon als {an}„{name}\" ›{aus} — du kannst trotzdem neu erstellen.": "Con {namen} ya tienes {an}«{name}» ›{aus} — puedes crear otra igualmente.",
  "{namen} suchen dann wieder.": "{namen} volverán a buscar sitio.",
  "{namen} sucht dann wieder.": "{namen} volverá a buscar sitio.",
  "{ort} angefragt": "Pedido: {ort}",
  "{preis} € p. P.": "{preis} €/persona",
  "{punkt} · {namen} — wieder freigeben": "{punkt} · {namen} — dejar libre",
  "{punkt} übernehmen": "Llevar {punkt}",
  "{tag} · {zeit} vorschlagen": "Proponer {tag} · {zeit}",
  "{termin} · Original": "{termin} · Original",
  "{titel} · Original": "{titel} · Original",
  "{titel} · von {name}": "{titel} · por {name}",
  "{titel} · von dir": "{titel} · por ti",
  "{titel} ansehen": "Ver {titel}",
  "{titel} bewerten": "Valorar {titel}",
  "{zeit} · +{n} Termin": "{zeit} · +{n} fecha",
  "{zeit} · +{n} Termine": "{zeit} · +{n} fechas",
  "{zeit} · Original": "{zeit} · Original",
  "{zeit} · Vorschlag von {name}": "{zeit} · Propuesta de {name}",
  "{zeit} · Vorschlag von dir": "{zeit} · Propuesta tuya",
  "{zeit} vor Beginn": "{zeit} antes",
  "{zeit} vorschlagen": "Proponer {zeit}",
  "© OpenStreetMap-Mitwirkende": "© colaboradores de OpenStreetMap",
  "+ {n} Alternative": "+ {n} alternativa",
  "+ {n} Alternativen": "+ {n} alternativas",
  "+ Meet": "+ Meet",
  "+ Umfrage": "+ Encuesta",
  "+ Vorschlag": "+ Propuesta",
  "~{n} min Umweg": "~{n} min de desvío",
  "~{n} min Umweg für dich": "~{n} min de desvío para ti",
  "1 auf der Liste": "1 en la lista",
  "1 gemeinsamer Freund · Code {code}": "1 amigo en común · código {code}",
  "1 Monat": "1 mes",
  "1 Woche": "1 semana",
  "2 Minuten!": "¡2 minutos!",
  "2 Wochen": "2 semanas",
  "3 Tage": "3 días",
  "3 Wochen": "3 semanas",
  "4 Tage": "4 días",
  "5 Tage": "5 días",
  "ab 3 Personen": "desde 3 personas",
  "ab 4 Personen": "desde 4 personas",
  "ab 4 Personen am besten": "mejor desde 4 personas",
  "ab und zu": "a veces",
  "Abbrechen": "Cancelar",
  "Abends meist frei, Anfänger willkommen": "Por la noche suele haber hueco, principiantes bienvenidos",
  "Abends meist frei, Anfänger willkommen — Schuhe gibt es vor Ort.": "Por la noche suele haber hueco y los principiantes son bienvenidos — allí te dejan pies de gato.",
  "Abgesagt": "Cancelado",
  "Abgesagt [Person]": "No voy",
  "Abholreihenfolge": "Orden de recogida",
  "Ablehnen": "Rechazar",
  "Abmelden": "Cerrar sesión",
  "Abstand": "Intervalo",
  "Abstimmen": "Votar",
  "abstimmen lassen": "que voten todos",
  "Abwählen": "Quitar",
  "Adler": "Águila",
  "Adminrolle übergeben": "Pasar el rol de admin",
  "Adresse erst nach Zustimmung": "Dirección cuando acepte",
  "Adresse freigegeben": "Dirección compartida",
  "Affe": "Mono",
  "aktiv": "activa",
  "Aktiv": "Activos",
  "aktiv oder kommend": "activo o próximo",
  "Aktivität": "Actividad",
  "Aktivität · {n} Vorschlag": "Actividad · {n} propuesta",
  "Aktivität · {n} Vorschläge": "Actividad · {n} propuestas",
  "Aktivität abstimmen": "Votar actividad",
  "Aktivität festgelegt": "Actividad fijada",
  "Aktivität oder Zeit": "Actividad u hora",
  "Aktivität vorschlagen": "Proponer actividad",
  "Aktivität zeigen": "Mostrar actividad",
  "Aktivitätsstatus für Freunde": "Estado de actividad para amigos",
  "Aktivitätsvorschläge ansehen": "Ver propuestas de actividad",
  "Aktuellen Entwurf speichern": "Guardar el borrador actual",
  "Aktueller Standort": "Ubicación actual",
  "Aktuelles Passwort": "Contraseña actual",
  "Alien": "Alien",
  "alle": "cada",
  "Alle": "Todo",
  "Alle ›": "Todos ›",
  "Alle {n} Anfragen": "Las {n} solicitudes",
  "Alle {n} Jahre am {tag}.{monat}.": "Cada {n} años, el {tag}/{monat}.",
  "Alle {n} Monate am {tag}.": "Cada {n} meses, el día {tag}.",
  "Alle anderen": "Todos los demás",
  "Alle Anfragen ({n})": "Todas las solicitudes ({n})",
  "Alle Autos sind voll.": "Todos los coches están llenos.",
  "Alle Beteiligten sehen die Absage.": "Todos verán que se ha cancelado.",
  "Alle deine Freunde sehen {name}.": "Todos tus amigos ven {name}.",
  "Alle deine Freunde sind schon in {name}.": "Todos tus amigos ya están en {name}.",
  "Alle Freunde": "Todos tus amigos",
  "Alle Freunde sehen deine Ressourcen — außer private.": "Todos tus amigos ven tus cosas — menos las privadas.",
  "Alle Interessen ({n})": "Todos los intereses ({n})",
  "Alle Kategorien": "Todas las categorías",
  "Alle Meets": "Todos los Meets",
  "alle Plätze belegt": "todas las plazas ocupadas",
  "Alle Ressourcen ({n})": "Todas las cosas ({n})",
  "Alle sehen denselben Meet-Chat.": "Todos ven el mismo chat del Meet.",
  "Alles liegt in Ordnern": "Todo está en carpetas",
  "Alles vergessen": "Olvidarlo todo",
  "Alles wird wieder vorgeschlagen": "Volverás a ver todas las ideas",
  "Allgemein": "General",
  "Als Alternative": "Como alternativa",
  "Als besondere Person markieren": "Marcar como persona especial",
  "Als besondere Person markiert": "Marcado como persona especial",
  "Als beste Freund:in markieren": "Marcar como mejor amigo",
  "Als beste Freund:in markiert": "Marcado como mejor amigo",
  "Als bester Freund markiert": "Marcado como mejor amigo",
  "Als Loop starten": "Convertir en Loop",
  "Als Meet vorschlagen": "Proponer como Meet",
  "als Variante dieses Meets": "como alternativa a este Meet",
  "Als Vorlage nutzen": "Usar como plantilla",
  "Am Wasser": "Junto al agua",
  "Amber": "Ámbar",
  "An": "Activado",
  "An · {n} Freund": "Activado · {n} amigo",
  "An · {n} Freunde": "Activado · {n} amigos",
  "An · Alle Freunde": "Activado · Todos tus amigos",
  "an {n} Person · Wer hat Lust?": "a {n} persona · ¿Quién se apunta?",
  "an {n} Personen · Wer hat Lust?": "a {n} personas · ¿Quién se apunta?",
  "Anderes": "Otros",
  "Anderes Foto": "Otra foto",
  "Ändern": "Cambiar",
  "Änderungen behalten?": "¿Conservar los cambios?",
  "Änderungen verwerfen": "Descartar cambios",
  "Anfrage abgelehnt": "Solicitud rechazada",
  "Anfrage ablehnen": "Rechazar solicitud",
  "Anfrage an {name} gesendet": "Solicitud enviada a {name}",
  "Anfrage an {name} läuft schon": "Ya le has enviado una solicitud a {name}",
  "Anfrage an {name} senden": "Enviar solicitud a {name}",
  "Anfrage angenommen": "Solicitud aceptada",
  "Anfrage annehmen": "Aceptar solicitud",
  "Anfrage gesendet": "Solicitud enviada",
  "Anfrage läuft schon": "La solicitud ya está enviada",
  "Anfrage senden": "Enviar solicitud",
  "Anfrage von {name} ablehnen?": "¿Rechazar la solicitud de {name}?",
  "Anfrage zurückgezogen": "Solicitud retirada",
  "Anfragen": "Solicitudes",
  "Angestupst": "Toque dado",
  "Angestupst · {zeit}": "Toque dado · {zeit}",
  "Anhänger": "Remolque",
  "Anmelden": "Iniciar sesión",
  "Anmeldung": "Inicio de sesión",
  "Anmeldung mit Apple und Google kommt mit der App-Version.": "El inicio de sesión con Apple y Google llegará con la app.",
  "Annehmen": "Aceptar",
  "Anstupsen": "Dar un toque",
  "Anstupser": "Toques",
  "Anstupser zurücknehmen": "Retirar el toque",
  "Antippen, um Mitteilungen auf dieses Gerät zu erlauben.": "Toca para permitir notificaciones en este dispositivo.",
  "Antwort {n}": "Respuesta {n}",
  "Antwort auf Anstupser": "Responder al toque",
  "Antwort entfernen": "Quitar respuesta",
  "Antwort gespeichert": "Respuesta guardada",
  "Antwort hinzufügen": "Añadir respuesta",
  "Antwort offen": "Sin responder",
  "Antworten": "Respuestas",
  "Anwenden": "Aplicar",
  "App": "App",
  "Apple Karten": "Mapas de Apple",
  "Apple und Google folgen mit der App.": "Apple y Google llegarán con la app.",
  "Arbeit, Schule, Training": "Trabajo, clase, entrenamiento",
  "Astronaut": "Astronauta",
  "Auf dem iPhone kommen Mitteilungen nur, wenn Crew auf dem Home-Bildschirm liegt. In Safari:": "En el iPhone, las notificaciones solo llegan si Crew está en la pantalla de inicio. En Safari:",
  "Auf der Karte": "En el mapa",
  "Auf der Karte gewählt": "Elegida en el mapa",
  "Auf der Liste bei „{titel}“": "En la lista de «{titel}»",
  "Auf die Liste": "A la lista",
  "Auf diesem Gerät nicht möglich": "No es posible en este dispositivo",
  "Auf einer Wiese oder am Grillplatz — Grill und Kohle mitnehmen.": "En un prado o en una zona de barbacoas — lleva parrilla y carbón.",
  "Auf Karte wählen": "Elegir en el mapa",
  "Auflösen": "Disolver",
  "aus": "desactivado",
  "Aus": "Desactivado",
  "aus · Start wäre {datum}": "desactivado · empezaría el {datum}",
  "Aus Verlauf ausblenden": "Ocultar del historial",
  "Ausdruck": "Expresión",
  "Ausgeblendet": "Ocultos",
  "Ausgehen": "Salir",
  "Ausgehen & Events": "Salir y eventos",
  "Ausschnitt verschieben und zoomen": "Mover y ampliar el recorte",
  "Aussteigen": "Bajarme",
  "Auswahl aufheben": "Quitar selección",
  "Auswählen": "Elegir",
  "Auto": "Coche",
  "Automatisch": "Automático",
  "Automatische Anmeldung fehlgeschlagen: {fehler}": "No se ha podido iniciar sesión automáticamente: {fehler}",
  "Autos": "Coches",
  "Baden": "Bañarse",
  "Bahn fährt erst ab 8, also zu Fuß hoch": "El teleférico no abre hasta las 8, así que subimos a pie",
  "Bahn oder zu Fuß, oben Panorama": "En teleférico o a pie, con vistas arriba",
  "Bahn oder zu Fuß, oben Panorama über den ganzen See.": "En teleférico o a pie; arriba, vistas a todo el lago.",
  "Ballsport": "Deportes de pelota",
  "Bar": "Bar",
  "Bär": "Oso",
  "Basketball": "Baloncesto",
  "Beamer": "Proyector",
  "Beamer oder Fernseher": "Proyector o tele",
  "Beamer oder Fernseher, Decken — zwei Filme zur Wahl.": "Proyector o tele, mantas — dos pelis a elegir.",
  "Beamer, Decken, zwei Filme zur Wahl": "Proyector, mantas y dos pelis a elegir",
  "Bearbeiten": "Editar",
  "Beere": "Baya",
  "Bei {name}": "Casa de {name}",
  "Bei {name} einsteigen": "Ir con {name}",
  "Bei {name} mitfahren": "Ir con {name}",
  "Bei jemandem daheim": "En casa de alguien",
  "Bei mir": "Mi casa",
  "Bei wem?": "¿En casa de quién?",
  "Beides dauert unter einer Minute.": "Las dos cosas llevan menos de un minuto.",
  "Belästigung": "Acoso",
  "Belgien": "Bélgica",
  "Benachrichtigungen": "Notificaciones",
  "Berg": "Montaña",
  "Berge": "Montañas",
  "Besondere Person": "Persona especial",
  "Besondere Person — Goldring zurückgenommen": "Persona especial — anillo dorado retirado",
  "Besondere Person entfernt": "Persona especial quitada",
  "Besonders": "Especial",
  "Bestätige zuerst die E-Mail, die wir dir geschickt haben": "Primero confirma el correo que te hemos enviado",
  "Bestätigung schicken": "Enviar confirmación",
  "Beste Freunde": "Mejores amigos",
  "Beste Freunde · {n} von 3": "Mejores amigos · {n} de 3",
  "Bester Freund": "Mejor amigo",
  "Bester Freund — besonderes Zeichen ersetzt": "Mejor amigo — sustituye a la marca especial",
  "Bester Freund entfernt": "Quitado de mejores amigos",
  "Bewerten": "Valorar",
  "Bewertung ändern": "Cambiar valoración",
  "Bewertung gelöscht": "Valoración eliminada",
  "Bewertung gespeichert": "Valoración guardada",
  "Bewertung löschen": "Eliminar valoración",
  "Bewertung speichern": "Guardar valoración",
  "Bild konnte nicht gelesen werden": "No se ha podido leer la imagen",
  "Bildnachweis": "Crédito de la imagen",
  "Bin am Kiosk, links vom Eingang": "Estoy en el chiringuito, a la izquierda de la entrada",
  "Bin dabei, ab 9 passt mir": "Me apunto, a partir de las 9 me va bien",
  "Bin um 19:10 da, komme direkt von der Arbeit": "Llego a las 19:10, voy directo desde el curro",
  "Bis": "Hasta",
  "bis {betrag} €": "hasta {betrag} €",
  "bis {betrag} € p. P.": "hasta {betrag} €/persona",
  "bis {km} km": "hasta {km} km",
  "bis {tag} {zeit}": "hasta el {tag} a las {zeit}",
  "bis {zeit}": "hasta las {zeit}",
  "Bis du annimmst, sieht die Person <b>nichts</b> von dir — kein Frei, keine Meets, keine Crews. Abgelehnte Anfragen verschwinden lautlos, ohne Hinweis an die andere Seite.": "Hasta que aceptes, esa persona no ve <b>nada</b> de ti — ni libre, ni Meets, ni Crews. Las solicitudes rechazadas desaparecen sin avisar a la otra persona.",
  "bis Mitternacht": "hasta medianoche",
  "Bis Mitternacht": "Hasta medianoche",
  "bis morgen {zeit}": "hasta mañana a las {zeit}",
  "Bitte ein Interesse eingeben": "Escribe un interés",
  "Bitte eine E-Mail-Adresse eingeben.": "Escribe una dirección de correo.",
  "Bitte eine gültige E-Mail-Adresse eingeben.": "Escribe un correo válido.",
  "Bitte einen Namen eingeben": "Escribe un nombre",
  "Bitte mindestens zwei Interessen wählen": "Elige al menos dos intereses",
  "Blendet den Vorschlag aus — Ähnliches kommt seltener": "Oculta esta idea — verás menos ideas parecidas",
  "Blitz": "Rayo",
  "Blockieren": "Bloquear",
  "Blockierte Person": "Persona bloqueada",
  "Blockierte Personen": "Personas bloqueadas",
  "Blockierung aufheben": "Desbloquear",
  "Blume": "Flor",
  "Blüte": "Flor",
  "Bohrmaschine": "Taladro",
  "Bollerwagen": "Carrito",
  "Boot": "Barca",
  "Bosnien und Herzegowina": "Bosnia y Herzegovina",
  "Boulder-Dienstag": "Martes de búlder",
  "Boulderhalle K1": "Rocódromo K1",
  "Bouldern": "Búlder",
  "Bouldern + Pizza": "Búlder + pizza",
  "Boxen": "Altavoces",
  "Brasilien": "Brasil",
  "Brauche Mitfahrt": "Necesito sitio",
  "Brettspiele": "Juegos de mesa",
  "Brunch": "Brunch",
  "Brunch bei Kira": "Brunch en casa de Kira",
  "Buch": "Libro",
  "Budget": "Presupuesto",
  "Camping": "Camping",
  "Campingbus": "Furgoneta camper",
  "Campingstuhl": "Silla de camping",
  "Chat": "Chat",
  "Chat öffnen": "Abrir chat",
  "Chillen": "Relax",
  "Chillen & Spiele": "Relax y juegos",
  "Club": "Discoteca",
  "Code eingeben": "Introduce un código",
  "Code einlösen": "Canjear código",
  "Code erkannt": "Código reconocido",
  "Code passt nicht": "Ese código no funciona",
  "Code scannen oder Link teilen": "Escanear código o compartir enlace",
  "Code ungültig": "Código no válido",
  "Code von Freund:in eingeben": "Introduce el código de tu amigo",
  "Cola": "Coca-Cola",
  "Containerschiff": "Portacontenedores",
  "Cowboy": "Vaquero",
  "Crew": "Crew",
  "Crew bearbeiten": "Editar Crew",
  "Crew erstellen": "Crear Crew",
  "Crew ist mit diesem Konto aktiviert": "Crew está activado con esta cuenta",
  "Crew nicht gefunden": "No encontramos esa Crew",
  "Crew oder Freunde": "Crew o amigos",
  "Crews": "Crews",
  "Curry": "Curry",
  "Cyan": "Cian",
  "Da fehlt noch ein Eintrag": "Falta algo por escribir",
  "Dabei": "Voy",
  "Dafür braucht es zuerst ein Meet": "Para eso primero hace falta un Meet",
  "Daheim": "En casa",
  "Daheim entfernen": "Quitar «En casa»",
  "damit nutzt du": "para usar",
  "Dänemark": "Dinamarca",
  "Danke — die Meldung ist raus": "Gracias — denuncia enviada",
  "Daraus sortiert Crew deine Vorschläge. Es bleibt in deinem Konto.": "Con esto, Crew ordena tus ideas. Se queda en tu cuenta.",
  "Darstellung": "Apariencia",
  "Dart": "Dardos",
  "Das aktuelle Passwort stimmt nicht.": "La contraseña actual no es correcta.",
  "Das bist du selbst": "Ese eres tú",
  "Das dürfen nur Fahrer, Mitfahrer oder wer das Meet erstellt hat": "Solo pueden hacerlo los conductores, los pasajeros o quien creó el Meet",
  "Das Einschalten hat nicht geklappt": "No se pudieron activar",
  "Das Einschalten hat nicht geklappt. Bitte noch einmal versuchen.": "No se pudieron activar. Inténtalo de nuevo.",
  "Das hat gerade nicht geklappt": "Vaya, eso no ha funcionado",
  "Das hat nicht geklappt": "Eso no ha funcionado",
  "Das ist bereits der Originaltermin": "Ya es la fecha original",
  "Das ist dasselbe Passwort wie bisher": "Es la misma contraseña que ya tenías",
  "Das ist dein eigener Code": "Ese es tu propio código",
  "Das ist kein Crew-Code": "Eso no es un código de Crew",
  "Das ist schon deine Adresse.": "Ese ya es tu correo.",
  "Das neue Passwort braucht mindestens 8 Zeichen.": "La nueva contraseña necesita al menos 8 caracteres.",
  "Das Original bleibt wählbar. Deine Stimme ist jederzeit änderbar.": "El original sigue disponible. Puedes cambiar tu voto cuando quieras.",
  "Das Passwort braucht mindestens 8 Zeichen": "La contraseña necesita al menos 8 caracteres",
  "Das Passwort ist zu kurz": "La contraseña es demasiado corta",
  "Das sieht nicht nach einer E-Mail-Adresse aus": "Eso no parece una dirección de correo",
  "Dein Desteny-Konto bleibt bestehen. Du kannst dich jederzeit wieder mit {email} anmelden.": "Tu cuenta Desteny se mantiene. Puedes volver a iniciar sesión con {email} cuando quieras.",
  "Dein Desteny-Konto bleibt bestehen. Du kannst dich jederzeit wieder mit deiner E-Mail anmelden.": "Tu cuenta Desteny se mantiene. Puedes volver a iniciar sesión con tu correo cuando quieras.",
  "Dein Desteny-Konto gilt für Crew und alle Apps von Desteny Development.": "Tu cuenta Desteny sirve para Crew y todas las apps de Desteny Development.",
  "Dein Desteny-Konto wird gelöscht, auch für andere Apps von Desteny Development. Deine Crews und Meets werden dauerhaft entfernt. Das lässt sich nicht rückgängig machen.": "Se eliminará tu cuenta de Desteny, también para las demás apps de Desteny Development. Tus Crews y Meets se borrarán para siempre. No se puede deshacer.",
  "Dein Name": "Tu nombre",
  "Dein Standort": "Tu ubicación",
  "Deine Bewertung": "Tu valoración",
  "Deine Freunde sehen es neben „frei\".": "Tus amigos lo ven junto a «libre».",
  "Deine Freunde sehen, dass du frei bist": "Tus amigos ven que estás libre",
  "Demo": "Demo",
  "Demo · kein Konto": "Demo · sin cuenta",
  "Den Rest können die Fahrer übernehmen.": "Los conductores pueden hacer el resto.",
  "Der Code ließ sich nicht einlösen": "No se ha podido canjear el código",
  "Der Entwurf verschwindet endgültig.": "El borrador se eliminará para siempre.",
  "Der Frei-Status wird spätestens um diese Uhrzeit zurückgesetzt — oder früher durch dein eigenes aktives Meet.": "Tu estado libre se quita como muy tarde a esta hora — o antes, si empieza un Meet tuyo.",
  "Der Ort selbst": "El sitio en sí",
  "Desteny-Apps": "Apps de Desteny",
  "Desteny-Konto": "Cuenta de Desteny",
  "Desteny-Konto erstellen": "Crear cuenta Desteny",
  "Desteny-Konto löschen": "Eliminar cuenta Desteny",
  "Deutschland": "Alemania",
  "Diamant": "Diamante",
  "Die App konnte nicht starten.": "La app no ha podido arrancar.",
  "Die Crew braucht einen Namen": "La Crew necesita un nombre",
  "Die Demo läuft nur auf diesem Gerät.": "La demo solo funciona en este dispositivo.",
  "Die Erlaubnis wird gerade eingeholt.": "Pidiendo permiso…",
  "Die Erlaubnis wurde abgelehnt. Zurücknehmen lässt sie sich nur in den Einstellungen des Browsers für diese Seite.": "Se ha denegado el permiso. Solo puedes cambiarlo en los ajustes del navegador para esta web.",
  "Die Frage fehlt noch": "Falta la pregunta",
  "Die Kamera startet gerade nicht — gib den Code unten ein.": "La cámara no arranca ahora — escribe el código abajo.",
  "Die Karte lädt noch": "El mapa aún está cargando",
  "Die Nachricht wird zur Prüfung übermittelt. {name} erfährt nicht, dass du gemeldet hast.": "El mensaje se enviará para revisarlo. {name} no sabrá que lo has denunciado.",
  "Die Passwörter stimmen nicht überein": "Las contraseñas no coinciden",
  "Die Probe ging nicht — sind Mitteilungen erlaubt?": "La prueba no funcionó: ¿están permitidas las notificaciones?",
  "die Ressource": "esto",
  "Die Wiederholung endet, das Meet bleibt.": "Deja de repetirse, pero el Meet se queda.",
  "Diese E-Mail-Adresse sieht nicht richtig aus": "Este correo no parece correcto",
  "Diese Person": "Esta persona",
  "Diese Person fährt gerade nicht": "Esta persona no conduce ahora mismo",
  "Diese Person hat ihren Ort noch nicht geteilt. Die Anfrage geht trotzdem raus.": "Esta persona aún no ha compartido su ubicación. La solicitud se envía igualmente.",
  "diese Ressource": "esto",
  "Diese Stelle": "Este punto",
  "Diese Woche mal wieder Bouldern?": "¿Volvemos al rocódromo esta semana?",
  "Diesen Ort wählen": "Elegir este lugar",
  "Dieser Browser kennt keine Mitteilungen.": "Este navegador no admite notificaciones.",
  "Dieser Ordner ist noch leer": "Esta carpeta aún está vacía",
  "Dieses Foto verwenden": "Usar esta foto",
  "Dieses Gerät liefert keinen Standort. „Auf Karte wählen\" geht weiterhin.": "Este dispositivo no da la ubicación. «Elegir en el mapa» sigue funcionando.",
  "Dieses Gerät wird benachrichtigt.": "Este dispositivo recibe notificaciones.",
  "Dieses Konto komplett zurücksetzen?\n\nAlles wird gelöscht: Profil, Freunde, Gruppen, Meets, Nachrichten. Danach läuft das Einrichten von vorn. Die Anmeldung (E-Mail und Passwort) bleibt.": "¿Restablecer esta cuenta por completo?\n\nSe borra todo: perfil, amigos, grupos, Meets y mensajes. Después empiezas la configuración desde cero. El inicio de sesión (correo y contraseña) se mantiene.",
  "Dieses Meet gibt es nicht mehr.": "Este Meet ya no existe.",
  "Dieses Meet wurde abgesagt.": "Este meet se canceló.",
  "Direkte Erwähnungen": "Menciones directas",
  "Draußen": "Aire libre",
  "Drohne": "Dron",
  "Drucker": "Impresora",
  "Du": "Tú",
  "du · {name}": "tú · {name}",
  "Du bist dabei": "Te has apuntado",
  "Du bist das letzte Mitglied von {name}. Die Gruppe und ihr Chat verschwinden; vergangene eigene Meets bleiben in deinem Verlauf.": "Eres el último miembro de {name}. El grupo y su chat desaparecerán; tus Meets pasados se quedan en tu historial.",
  "Du bist die einzige Person, die {name} verwaltet. Wähle, wer das übernimmt — danach verlässt du die Gruppe.": "Eres la única persona que administra {name}. Elige quién se encarga — después saldrás del grupo.",
  "Du bist eingeladen": "Te han invitado",
  "Du bist jetzt frei": "Ahora estás libre",
  "Du bist kein Mitglied": "No eres miembro",
  "Du bist raus": "No vas",
  "Du bringst’s": "Lo llevas tú",
  "Du fährst": "Conduces tú",
  "Du fährst mit {name}": "Vas con {name}",
  "Du hast {name} angestupst": "Le has dado un toque a {name}",
  "Du hast abgesagt": "Has dicho que no",
  "Du hast abgesagt — hier siehst du nur, wer fährt.": "No vas — aquí solo ves quién conduce.",
  "Du hast angestupst": "Has dado un toque",
  "Du hast dich frei gemeldet": "Has dicho que estás libre",
  "Du hast ein Meet gestartet": "Has creado un Meet",
  "Du hast etwas bearbeitet, aber noch nicht gespeichert.": "Has editado algo, pero aún no lo has guardado.",
  "Du hast zurückgestupst": "Le has devuelto el toque",
  "Du holst {namen} ab": "Recoges a {namen}",
  "Du kommst selbst hin.": "Vas por tu cuenta.",
  "Du siehst danach weder den Chat noch neue Meets dieser Gruppe. Vergangene eigene Meets bleiben in deinem Verlauf.": "Ya no verás el chat ni los nuevos Meets de este grupo. Tus Meets pasados se quedan en tu historial.",
  "Du stehst bei „sucht noch“": "Estás en «aún busca»",
  "Du suchst eine Mitfahrt.": "Buscas sitio en un coche.",
  "Dunkel": "Oscuro",
  "E-Mail": "Correo",
  "E-Mail ändern": "Cambiar correo",
  "E-Mail ausfüllen": "Escribe tu correo",
  "E-Mail oder Passwort stimmt nicht": "El correo o la contraseña no son correctos",
  "E-Mail und Passwort": "Correo y contraseña",
  "E-Mail und Passwort ausfüllen": "Escribe tu correo y tu contraseña",
  "eben hinzugefügt": "recién añadida",
  "eben hinzugefügt · {kosten}": "recién añadida · {kosten}",
  "Egal": "Da igual",
  "Eher nicht": "Mejor no",
  "Eigene": "Personalizado",
  "Eigene Idee": "Idea propia",
  "Eigene Mitteilung, getrennt von den übrigen": "Notificación propia, separada de las demás",
  "Eigenes Emoji": "Emoji propio",
  "Eigenes Emoji: das rechte Feld antippen und aus der Tastatur wählen. Ein Emoji ersetzt das Symbol — der farbige Ring bleibt.": "Emoji propio: toca la casilla de la derecha y elige uno del teclado. El emoji sustituye al icono — el anillo de color se mantiene.",
  "Eigenes Interesse": "Interés propio",
  "Eigenes Interesse hinzufügen": "Añadir interés propio",
  "Ein eigenes Foto statt Farbe und Motiv. Danach rückst du es im Kreis zurecht.": "Tu propia foto en lugar de color y motivo. Después la colocas dentro del círculo.",
  "Ein Freund hat dich zu Crew geholt.": "Un amigo te ha traído a Crew.",
  "Ein Platz mehr": "Una plaza más",
  "Ein Platz weniger": "Una plaza menos",
  "Ein Tipp genügt — so wissen alle, wer wen abholt.": "Un toque basta — así todos saben quién recoge a quién.",
  "Eine Ebene, keine Unterordner. Neue Ordner erscheinen sofort als Filter und im Speichern-Sheet.": "Un solo nivel, sin subcarpetas. Las carpetas nuevas aparecen al momento como filtro y al guardar.",
  "Einen Moment …": "Un momento…",
  "Einen Moment noch — kurz warten und noch einmal versuchen": "Un momento — espera un poco y vuelve a intentarlo",
  "Eingeladen": "Invitados",
  "Einladen": "Invitar",
  "Einladung": "Invitación",
  "Einladungen & Meet-Änderungen": "Invitaciones y cambios en Meets",
  "einmalig an {n} Mitglied von {name}": "una sola vez a {n} miembro de {name}",
  "einmalig an {n} Mitglieder von {name}": "una sola vez a {n} miembros de {name}",
  "einmalig an {n} Teilnehmende": "una sola vez a {n} participantes",
  "einmalig an {n} teilnehmende Person": "una sola vez a {n} participante",
  "einmalig an {name}": "una sola vez a {name}",
  "einmalig an diesen Raum": "una sola vez a esta sala",
  "Einmalige Freigabe. Crew sendet danach keine weitere Position und ortet dich nicht im Hintergrund.": "Se comparte una sola vez. Crew no enviará más posiciones ni te localizará en segundo plano.",
  "Einschalten": "Activar",
  "Einsteigen": "Subir",
  "Einstellungen": "Ajustes",
  "Einstellungen speichern": "Guardar ajustes",
  "Eis": "Helado",
  "Element hinzufügen": "Añadir elemento",
  "Emoji": "Emoji",
  "Endet am nächsten Tag": "Termina al día siguiente",
  "Endgültig löschen": "Eliminar para siempre",
  "Engel": "Ángel",
  "Entdecken": "Descubrir",
  "Entdecken oder eigene Idee": "Descubrir o idea propia",
  "Entfernen": "Quitar",
  "Entfernung": "Distancia",
  "Entwurf löschen": "Eliminar borrador",
  "Entwurf löschen?": "¿Eliminar el borrador?",
  "Entwurf speichern": "Guardar borrador",
  "Erde": "Tierra",
  "Ereignis eintragen": "Registrar evento",
  "Erhalten · {n}": "Recibidas · {n}",
  "Erinnerung aus": "Recordatorio desactivado",
  "Erlauben lässt es sich in den iPhone-Einstellungen: Mitteilungen → Crew.": "Puedes permitirlas en Ajustes del iPhone: Notificaciones → Crew.",
  "Erst auf den Home-Bildschirm": "Primero a la pantalla de inicio",
  "Erst die Gruppe übergeben": "Primero pasa el grupo a otra persona",
  "Erst eine Aktivität wählen": "Elige primero una actividad",
  "Erst eine Idee wählen": "Elige primero una idea",
  "Erst eine Idee wählen — oder „Spontanes Treffen\"": "Elige primero una idea — o «Meet espontáneo»",
  "Erst eine Person wählen": "Elige primero una persona",
  "Erst einen Namen eingeben": "Escribe primero un nombre",
  "Erst einen Ort wählen": "Elige primero un lugar",
  "Erst einen Punkt eintragen": "Escribe algo primero",
  "Erst einen Titel eingeben": "Escribe primero un título",
  "Erst jemanden absetzen": "Quita primero a alguien",
  "Erst mindestens eine Person oder Crew wählen": "Elige primero al menos una persona o Crew",
  "Erstmal umsehen": "Primero echar un vistazo",
  "Essen": "Comer",
  "Essen & Trinken": "Comer y beber",
  "Essen gehen": "Salir a comer",
  "Etwas anderes": "Otra cosa",
  "Etwas hinzufügen": "Añadir algo",
  "Euer Kino-Klassiker": "El cine de siempre",
  "Eule": "Búho",
  "Europa": "Europa",
  "Event": "Evento",
  "EVENT": "EVENTO",
  "Fahrrad": "Bici",
  "Fahrzeuge": "Vehículos",
  "Farbe": "Color",
  "Farbe wählen": "Elegir color",
  "Farbe, Motiv oder Foto — änderbar im Profil.": "Color, icono o foto — puedes cambiarlo en tu perfil.",
  "Farbverlauf": "Degradado",
  "Feiern": "Fiesta",
  "Fernglas": "Prismáticos",
  "Fertig": "Listo",
  "Feste Zeiten eintragen": "Añadir horarios fijos",
  "Festivals": "Festivales",
  "Festlegen": "Fijar",
  "Festspiele Seebühne": "Festival en la Seebühne",
  "Feuer": "Fuego",
  "Feuerwerk am See": "Fuegos artificiales en el lago",
  "Film": "Película",
  "Filmabend": "Noche de peli",
  "Filme & Serien": "Cine y series",
  "Filter": "Filtros",
  "Finnland": "Finlandia",
  "Fitness": "Fitness",
  "Fixe Uhrzeit": "Hora fija",
  "Flaggen": "Banderas",
  "Flieder": "Lila",
  "Flugzeug": "Avión",
  "Flugzeuge": "Aviones",
  "folgt dem Gerät": "igual que el dispositivo",
  "Foto": "Foto",
  "Foto entfernen": "Quitar foto",
  "Foto wählen": "Elegir foto",
  "Foto wird vorbereitet …": "Preparando la foto …",
  "Foto-Nachweis ausblenden": "Ocultar crédito de la foto",
  "Foto-Nachweis zeigen": "Mostrar crédito de la foto",
  "Foto: {urheber}": "Foto: {urheber}",
  "Fotografieren": "Fotografía",
  "Frage": "Pregunta",
  "Frage und zwei Optionen ausfüllen": "Escribe la pregunta y dos opciones",
  "fragt jetzt nach Freigabe": "pedirá permiso ahora",
  "Frankreich": "Francia",
  "Frech": "Pícaro",
  "Frei": "Libre",
  "Frei — aktiv": "Libre — activo",
  "frei · {lust}": "libre · {lust}",
  "Frei · {status}": "Libre · {status}",
  "Frei ab": "Libre desde",
  "frei ab {zeit}": "libre desde las {zeit}",
  "Frei ab {zeit}": "Libre desde las {zeit}",
  "Frei setzen": "Activar libre",
  "Frei zurücksetzen um": "Libre se reinicia a las",
  "Frei zurücksetzen um {zeit}": "Libre se reinicia a las {zeit}",
  "Frei-Hinweis": "Aviso de libre",
  "Frei-Hinweis von {name} an": "Aviso de libre de {name} activado",
  "Frei-Hinweis von {name} aus": "Aviso de libre de {name} desactivado",
  "Frei-Hinweise · Individuell": "Avisos de libre · Personalizado",
  "Frei-Hinweise von Freunden": "Avisos de amigos libres",
  "Frei-Status speichern": "Guardar estado libre",
  "freie Umfrage im Chat": "encuesta suelta en el chat",
  "Freigabe": "Quién lo ve",
  "Freigabe wird abgefragt …": "Pidiendo permiso…",
  "Freigeben": "Desbloquear",
  "Freitag": "Viernes",
  "Freitag wieder was machen?": "¿Repetimos el viernes?",
  "Freitag-Crew": "Crew del viernes",
  "freiwillig": "opcional",
  "Freund hinzufügen": "Añadir amigo",
  "Freunde": "Amigos",
  "Freunde · {n}": "Amigos · {n}",
  "Freunde hinzufügen": "Añadir amigos",
  "Freunde sehen nur „Keine Zeit“.": "Tus amigos solo ven «Sin tiempo».",
  "Freunde suchen": "Buscar amigos",
  "Freundesanfragen": "Solicitudes de amistad",
  "Freundschaft beenden": "Eliminar de amigos",
  "Freundschaft beendet": "Eliminado de tus amigos",
  "Freundschaft mit {name} beenden?": "¿Eliminar a {name} de tus amigos?",
  "Freundschaftsanfragen": "Solicitudes de amistad",
  "Frisbee": "Frisbee",
  "Fröhlich": "Alegre",
  "Frosch": "Rana",
  "Früh buchen": "Reserva pronto",
  "Früh buchen, nur bei gutem Wetter": "Reserva pronto, solo con buen tiempo",
  "Fuchs": "Zorro",
  "Füge mich in Crew hinzu: {code}": "Añádeme en Crew: {code}",
  "Für {antwort} stimmen": "Votar por {antwort}",
  "Für {titel} · Original bleibt wählbar": "Para {titel} · el original sigue disponible",
  "Für dein Desteny-Konto.": "Para tu cuenta Desteny.",
  "Für dich": "Para ti",
  "Für dieses Meet gibt es keinen Raum": "Este Meet no tiene sala",
  "Fußball": "Fútbol",
  "Gaming": "Gaming",
  "Gehört zu": "Pertenece a",
  "Geht immer": "Siempre funciona",
  "Geist": "Fantasma",
  "Geländewagen": "Todoterreno",
  "Gelb": "Amarillo",
  "Gemeinsam erlebt": "Planes juntos",
  "Gemeinsam kochen": "Cocinar juntos",
  "Gemeinsame Crews": "Crews en común",
  "Gemeinsame Interessen": "Intereses en común",
  "Gemeinsame Ressourcen": "Cosas en común",
  "gemeinsamer Raum": "sala compartida",
  "Gemeldet · {name} blockiert": "Denuncia enviada · has bloqueado a {name}",
  "Gemeldet · Person blockiert": "Denuncia enviada · persona bloqueada",
  "Gemütlich daheim": "A gusto en casa",
  "genauer": "precisar",
  "gerade eben": "ahora mismo",
  "Gerade frei": "Libre ahora",
  "Gerade frei · {n}": "Libres ahora · {n}",
  "Gerade gilt dein Foto. Wählst du hier etwas, ersetzt es das Foto.": "Ahora se usa tu foto. Si eliges algo aquí, la reemplaza.",
  "Gerade nicht möglich": "Ahora no se puede",
  "gesendet": "enviada",
  "Gespeichert": "Guardado",
  "Gespeichertes suchen …": "Buscar en guardados…",
  "Gestern, {datum}": "Ayer, {datum}",
  "Getränke": "Bebidas",
  "Gib die E-Mail deines Desteny-Kontos ein. Wir schicken dir einen Link für ein neues Passwort.": "Escribe el correo de tu cuenta Desteny. Te enviamos un enlace para una nueva contraseña.",
  "Gib zuerst dein aktuelles Passwort ein.": "Primero escribe tu contraseña actual.",
  "Gilt für alle besten Freunde · nur für dich sichtbar": "Para todos tus mejores amigos · solo la ves tú",
  "Gitarre": "Guitarra",
  "Gold": "Oro",
  "Graphit": "Grafito",
  "Griechenland": "Grecia",
  "Grill": "Parrilla",
  "Grill und Kohle mitnehmen": "Lleva parrilla y carbón",
  "Grillen": "Barbacoa",
  "Grillen am See": "Barbacoa en el lago",
  "Grillen im Grünen": "Barbacoa en el campo",
  "Grimmig": "Feroz",
  "Grinsen": "Sonrisa",
  "grob nach Luftlinie": "aproximado, en línea recta",
  "grobe Umgebung · {ort}": "zona aproximada · {ort}",
  "Großbritannien": "Reino Unido",
  "Große Küche": "Cocina grande",
  "Grün": "Verde",
  "Grund fehlt": "Falta el motivo",
  "Grund melden (freiwillig)": "Motivo de la denuncia (opcional)",
  "Gruppe ändern": "Editar grupo",
  "Gruppe anlegen": "Crear grupo",
  "Gruppe auflösen": "Disolver grupo",
  "Gruppe auflösen?": "¿Disolver el grupo?",
  "Gruppe bearbeiten": "Editar grupo",
  "Gruppe gespeichert": "Grupo guardado",
  "Gruppe nicht gefunden": "No encontramos ese grupo",
  "Gruppe öffnen": "Abrir grupo",
  "Gruppe öffnen?": "¿Abrir el grupo?",
  "Gruppe verlassen": "Salir del grupo",
  "Gruppenbild": "Imagen del grupo",
  "Gruppenbild ändern": "Cambiar imagen del grupo",
  "Gruppenbild groß ansehen": "Ver en grande la imagen del grupo",
  "Gruppenbild von {name}": "Imagen del grupo {name}",
  "Gruppenbild wählen": "Elegir imagen del grupo",
  "Gruppenoptionen": "Opciones del grupo",
  "Gut": "Bien",
  "Gym": "Gimnasio",
  "Habt ihr schon gewählt": "Ya lo habéis elegido",
  "Hängematte": "Hamaca",
  "Hase": "Conejo",
  "Hat nicht geklappt": "No funcionó",
  "Hat nicht stattgefunden": "No se hizo",
  "Hauptnavigation": "Navegación principal",
  "Hauptvorschlag": "Propuesta principal",
  "Heißluftballon": "Globo aerostático",
  "Helikopter": "Helicóptero",
  "Hell": "Claro",
  "Herz": "Corazón",
  "Heute": "Hoy",
  "Heute und morgen": "Hoy y mañana",
  "heute, {zeit}": "hoy, {zeit}",
  "Himmelblau": "Celeste",
  "Hintergrund": "Fondo",
  "Hinweis ausblenden": "Ocultar aviso",
  "Hinweis schließen": "Cerrar aviso",
  "Hinzufügen": "Añadir",
  "Höhe über der Karte": "Altura sobre el mapa",
  "Hubschrauber": "Helicóptero",
  "Hund": "Perro",
  "Ich bin frei": "Estoy libre",
  "Ich brauche eine Mitfahrt": "Necesito que me lleven",
  "Ich bring Cola, Chips und Kohle mit": "Yo llevo Coca-Cola, patatas y carbón",
  "Ich bring Snacks für oben mit": "Yo llevo algo de picar para arriba",
  "Ich fahre": "Conduzco yo",
  "Ich komme selbst": "Voy por mi cuenta",
  "Ich nehm die Frisbee mit": "Yo llevo el frisbee",
  "Ich nehm die Seile mit": "Yo llevo las cuerdas",
  "Ich übernehm die Snacks @Mira du die Seile?": "Yo me encargo del picoteo, @Mira ¿tú las cuerdas?",
  "Ich war nicht dabei": "No estuve",
  "Ich wäre für Kochen bei mir": "Yo propongo cocinar en mi casa",
  "Idee": "Idea",
  "IDEE": "IDEA",
  "Idee anlegen": "Crear idea",
  "Idee entfernen": "Quitar idea",
  "Idee speichern": "Guardar idea",
  "Igel": "Erizo",
  "Ihr habt: {ding}": "Tenéis: {ding}",
  "Ihr seht danach nichts mehr voneinander — kein Frei, keine Meets, keine Crews. Eure gemeinsamen vergangenen Meets und deine eigenen Bewertungen bleiben erhalten.": "Dejaréis de ver nada el uno del otro — ni libre, ni Meets, ni Crews. Los Meets pasados que compartisteis y tus valoraciones se conservan.",
  "Ihr seht danach nichts mehr voneinander. {name} verschwindet aus deinen Listen, aus euren Gruppen und aus allen Räumen — auch bereits geschriebene Nachrichten. {name} erfährt davon nichts.": "Dejaréis de veros por completo. {name} desaparecerá de tus listas, de vuestros grupos y de todas las salas — también sus mensajes ya enviados. {name} no se enterará.",
  "Ihr seht danach weder eure freie Zeit noch eure Profile. Gemeinsame Meets und deine eigenen Bewertungen bleiben in deinem Verlauf.": "Dejaréis de ver el tiempo libre y el perfil del otro. Los Meets compartidos y tus valoraciones se quedan en tu historial.",
  "Ihr seid schon befreundet": "Ya sois amigos",
  "Im Demo-Modus gibt es kein Konto.": "En el modo demo no hay cuenta.",
  "Im Demo-Modus gibt es keine Mitteilungen — es gibt niemanden, der etwas schicken könnte.": "En el modo demo no hay notificaciones — no hay nadie que pueda enviarte nada.",
  "Im Demo-Modus öffnen": "Abrir en modo demo",
  "Im Meet · {titel}": "En un Meet · {titel}",
  "Im Meet vermerkt": "Añadido al Meet",
  "Immer": "Siempre",
  "immer dabei": "siempre incluida",
  "Immer verfügbar": "Siempre disponible",
  "in {min} Min.": "en {min} min",
  "In {ordner} gespeichert": "Guardado en {ordner}",
  "In {ort}": "En {ort}",
  "in {std} Std": "en {std} h",
  "in {std} Std {min} Min": "en {std} h {min} min",
  "Indigo": "Índigo",
  "Individuell": "Personalizado",
  "Individuell · {n}": "Personalizado · {n}",
  "Individuell · niemand": "Personalizado · nadie",
  "Info zur Lage": "Cómo está la cosa",
  "Initialen": "Iniciales",
  "Interesse": "Interés",
  "Interesse bearbeiten": "Editar interés",
  "Interesse entfernen": "Quitar interés",
  "Interesse entfernt": "Interés quitado",
  "Interesse gibt es schon": "Ese interés ya está",
  "Interesse hinzufügen": "Añadir interés",
  "Interesse hinzugefügt": "Interés añadido",
  "Interessen": "Intereses",
  "Irland": "Irlanda",
  "Italien": "Italia",
  "Ja, bei mir": "Sí, en mi casa",
  "Ja. @Jonny bringst du die Kohle mit?": "Sí. @Jonny, ¿traes tú el carbón?",
  "Jahr": "Año",
  "Jahr [Einheit]": "año",
  "Jahr {jahr}": "Año {jahr}",
  "Jahr wählen": "Elegir año",
  "Jahre [Einheit]": "años",
  "Japan": "Japón",
  "Jause": "Bocatas",
  "Jazz am See": "Jazz en el lago",
  "Jede Woche. Freunde sehen nur „Keine Zeit“.": "Cada semana. Tus amigos solo ven «Sin tiempo».",
  "Jeden {n}. {tag}": "Cada {n} semanas, el {tag}",
  "Jeden {n}. {wochentag}": "Cada {n} semanas, el {wochentag}",
  "Jeden {tag}": "Cada {tag}",
  "Jeden {wochentag}": "Cada {wochentag}",
  "Jeden dritten {tag}": "Cada 3 semanas, el {tag}",
  "Jeden dritten {wochentag}": "Cada 3 semanas, el {wochentag}",
  "Jeden fünften {tag}": "Cada 5 semanas, el {tag}",
  "Jeden fünften {wochentag}": "Cada 5 semanas, el {wochentag}",
  "Jeden Monat am {tag}.": "Cada mes, el día {tag}.",
  "Jeden sechsten {tag}": "Cada 6 semanas, el {tag}",
  "Jeden sechsten {wochentag}": "Cada 6 semanas, el {wochentag}",
  "Jeden Tag": "Todos los días",
  "Jeden vierten {tag}": "Cada 4 semanas, el {tag}",
  "Jeden vierten {wochentag}": "Cada 4 semanas, el {wochentag}",
  "Jeden zweiten {tag}": "Cada 2 semanas, el {tag}",
  "Jeden zweiten {wochentag}": "Cada 2 semanas, el {wochentag}",
  "Jedes Jahr am {tag}.{monat}.": "Cada año, el {tag}/{monat}.",
  "Jemand": "Alguien",
  "Jet": "Jet",
  "jetzt": "ahora",
  "Jetzt": "Ahora",
  "Jetzt bewerten": "Valorar ahora",
  "Jetzt frei?": "¿Libre ahora?",
  "Jetzt vorschlagen": "Proponer ahora",
  "Jetzt: {an}{email}{aus}": "Ahora: {an}{email}{aus}",
  "Jupiter": "Júpiter",
  "Kaffee": "Café",
  "Kaktus": "Cactus",
  "Kamera": "Cámara",
  "Kamera nicht freigegeben — gib den Code unten ein.": "Cámara no permitida — escribe el código abajo.",
  "Kanada": "Canadá",
  "Kann mich jemand mitnehmen? Ich bräuchte eine Mitfahrgelegenheit": "¿Alguien me puede llevar? No tengo cómo ir",
  "Kanu": "Canoa",
  "Karamell": "Caramelo",
  "Karaoke": "Karaoke",
  "Karte": "Mapa",
  "Karte bewegen — der Pin bleibt in der Mitte": "Mueve el mapa — el pin se queda en el centro",
  "Karte nicht verfügbar": "Mapa no disponible",
  "Karten": "Cartas",
  "Karten und Snacks — ab 3 Personen.": "Cartas y picoteo — desde 3 personas.",
  "Karten und Snacks, ab 3 Personen": "Cartas y picoteo, desde 3 personas",
  "Kartenabend": "Noche de cartas",
  "Kartendaten": "Datos del mapa",
  "Kartenspiele": "Cartas",
  "Kategorie": "Categoría",
  "Katze": "Gato",
  "Kein Muster": "Sin patrón",
  "Kein Ordner": "Sin carpeta",
  "Kein Ort gefunden": "Ningún lugar encontrado",
  "Kein Ort gefunden. Tipp: Name des Lokals, der Halle oder der Straße.": "Ningún lugar encontrado. Prueba con el nombre del bar, del pabellón o de la calle.",
  "Kein passendes Symbol gefunden — {an}such dir selbst eines aus{aus}.": "No hay un icono que encaje — {an}elige tú uno{aus}.",
  "Kein Platz mehr frei": "No quedan plazas",
  "Kein Platz mehr für {namen}": "No queda sitio para {namen}",
  "kein Umweg": "sin desvío",
  "kein Umweg für dich": "sin desvío para ti",
  "Keine aktuellen Meets": "No hay Meets próximos",
  "Keine Angabe": "Sin preferencia",
  "Keine Freunde auf der Karte": "No hay amigos en el mapa",
  "Keine gesendeten Anfragen": "No has enviado solicitudes",
  "Keine Kamera gefunden — gib den Code unten ein.": "No se encontró ninguna cámara — escribe el código abajo.",
  "Keine Meets in diesem Zeitraum": "No hay Meets en este periodo",
  "Keine offenen Anfragen": "No hay solicitudes pendientes",
  "Keine Variante gewählt": "No has elegido ninguna opción",
  "Keine Verbindung zum Server. Deine Anmeldung ist noch da – öffne Crew gleich noch einmal.": "No hay conexión con el servidor. Sigues con la sesión iniciada – vuelve a abrir Crew en un momento.",
  "Keine Verbindung. Netz prüfen und noch einmal versuchen.": "Sin conexión. Revisa la red y vuelve a intentarlo.",
  "Keine vergangenen Meets": "No hay Meets pasados",
  "Keine Vorschläge — Filter oder Suche anpassen": "No hay ideas — cambia los filtros o la búsqueda",
  "Keine Zeit": "Sin tiempo",
  "Keine Zeit bearbeiten": "Editar horario sin tiempo",
  "Keine Zeit bis {tag} {zeit}": "Sin tiempo hasta el {tag} a las {zeit}",
  "Keine Zeit bis {zeit}": "Sin tiempo hasta las {zeit}",
  "Keine Zeit bis Mitternacht": "Sin tiempo hasta medianoche",
  "Keine Zeit bis morgen {zeit}": "Sin tiempo hasta mañana a las {zeit}",
  "Keine Zeit eintragen": "Añadir horario sin tiempo",
  "Keine Zeit ist seit {zeit} vorbei": "Tu tiempo ocupado terminó a las {zeit}",
  "Kino": "Cine",
  "Kino & Filme": "Cine y pelis",
  "Kino Donnerstag um 20:15 — kommst du mit?": "Cine el jueves a las 20:15 — ¿te vienes?",
  "Kino unter freiem Himmel direkt am See": "Cine al aire libre junto al lago",
  "Kino unter freiem Himmel direkt am See — Decken mitbringen.": "Cine al aire libre junto al lago — trae una manta.",
  "Kino: Dune Part 3": "Cine: Dune Parte 3",
  "Klavier": "Piano",
  "Kleeblatt": "Trébol",
  "Kletterhalle K1": "Rocódromo K1",
  "Klettern & Berge": "Escalada y montaña",
  "Klettern Rheintal": "Escalada en el Rheintal",
  "Kletterseil": "Cuerda de escalada",
  "Koala": "Koala",
  "Kochabend": "Noche de cocina",
  "Kochen": "Cocinar",
  "Kochen draußen": "Cocinar al aire libre",
  "Koffer": "Maleta",
  "Kohle": "Carbón",
  "Kohle nicht vergessen": "No olvidar el carbón",
  "Kohle und Snacks bring ich mit": "Yo llevo el carbón y algo de picar",
  "Komet": "Cometa",
  "Komme selbst": "Voy por mi cuenta",
  "Kommen selbst: {namen}": "Por su cuenta: {namen}",
  "Kommend": "Próximos",
  "Konfetti": "Confeti",
  "Königsblau": "Azul real",
  "Konsole": "Consola",
  "Konto": "Cuenta",
  "Konto löschen": "Eliminar cuenta",
  "Konzert Kammgarn": "Concierto en el Kammgarn",
  "Konzerte": "Conciertos",
  "Kopfhörer": "Auriculares",
  "Kopieren": "Copiar",
  "Kopieren ging nicht": "No se pudo copiar",
  "Kopiert": "Copiado",
  "Koralle": "Coral",
  "Kosten": "Coste",
  "Kosten {an}optional{aus}": "Coste {an}opcional{aus}",
  "kostenlos": "gratis",
  "Kreuzfahrtschiff": "Crucero",
  "Kroatien": "Croacia",
  "Krone": "Corona",
  "Kühlbox": "Nevera portátil",
  "Kultur & Events": "Cultura y eventos",
  "Kürbis": "Calabaza",
  "Kurz warten, dann erneut vorschlagen": "Espera un poco antes de volver a proponer",
  "Kurzcode": "Por código",
  "Kurzcode · gerade eben": "Por código · ahora mismo",
  "kurze Runde": "chapuzón rápido",
  "Kurze Runde im See — danach gemeinsam Kaffee.": "Un chapuzón rápido en el lago — y luego, café juntos.",
  "Kurze Runde im See, danach Kaffee": "Chapuzón en el lago y luego café",
  "Kurzer Ton und Vibration, wenn etwas ankommt, während Crew offen ist": "Un sonido corto y vibración cuando llega algo mientras Crew está abierta",
  "Kurzfilmnacht": "Noche de cortos",
  "Label": "Etiqueta",
  "Label · frei tippbar": "Etiqueta · escribe lo que quieras",
  "Lächelnd": "Sonriente",
  "Lädt dich ein · Kino Do": "Te invita · Cine jue",
  "lädt ein": "invita",
  "Lage nicht freigegeben": "Ubicación no compartida",
  "Laptop": "Portátil",
  "Laufen": "Correr",
  "Laufrunde am See": "Correr junto al lago",
  "läuft": "en marcha",
  "läuft gerade": "en marcha",
  "Lautsprecher": "Altavoz",
  "Lavendel": "Lavanda",
  "Leinwand": "Pantalla",
  "Leiter": "Escalera",
  "Lernen": "Aprender",
  "Lesen": "Leer",
  "Lesestand merken": "Marcar como leído",
  "Lieber nicht": "Mejor no",
  "Limette": "Lima",
  "Link geteilt · gestern": "Enlace compartido · ayer",
  "Link schicken": "Enviar enlace",
  "Liste": "Lista",
  "Liste · {n}": "Lista · {n}",
  "Liste übernommen · {wer}": "En la lista · {wer}",
  "Listenpunkt erstellen": "Añadir a la lista",
  "Lizenz: {lizenz}": "Licencia: {lizenz}",
  "Loop": "Loop",
  "Loop · {n}. Mal": "Loop · {n}.ª vez",
  "Loop · {n}. Mal [erstes]": "Loop · {n}.ª vez",
  "Loop aktivieren": "Activar Loop",
  "Loop aktiviert": "Loop activado",
  "Loop bearbeiten": "Editar Loop",
  "Loop erstellen": "Crear Loop",
  "Loop geändert": "Loop actualizado",
  "Loop gestoppt": "Loop parado",
  "Loop speichern": "Guardar Loop",
  "Loop stoppen": "Parar Loop",
  "Loop stoppen?": "¿Parar el Loop?",
  "Loop-Antwort speichern": "Guardar respuesta del Loop",
  "Loops": "Loops",
  "Los geht’s": "¡Vamos!",
  "Löschen": "Eliminar",
  "Löschen hat nicht geklappt": "No se pudo eliminar",
  "Löwe": "León",
  "Lust auf draußen": "Con ganas de salir",
  "Lust auf Essen": "Con ganas de comer",
  "Lust auf Kaffee": "Con ganas de café",
  "Lust auf Sport": "Con ganas de deporte",
  "Lust zu chillen": "Con ganas de relajarse",
  "Lust?": "¿Ganas?",
  "Magst du": "Te gusta",
  "Manchmal": "A veces",
  "Manchmal verfügbar": "A veces disponible",
  "Markieren": "Marcar",
  "Markierte Freunde": "Amigos marcados",
  "Markierung entfernen": "Quitar marca",
  "Markierung entfernt": "Marca quitada",
  "Mars": "Marte",
  "Maus": "Ratón",
  "Maximal drei beste Freunde": "Máximo tres mejores amigos",
  "Meet": "Meet",
  "Meet abgesagt": "Meet cancelado",
  "Meet absagen": "Cancelar Meet",
  "Meet absagen?": "¿Cancelar el Meet?",
  "Meet anlegen": "Crear Meet",
  "Meet bei dir?": "¿Meet en tu casa?",
  "Meet festlegen": "Fijar el Meet",
  "Meet nicht gefunden": "No encontramos ese Meet",
  "Meet öffnen": "Abrir Meet",
  "Meet senden": "Enviar Meet",
  "Meet veröffentlichen": "Publicar Meet",
  "Meet-Erinnerung": "Recordatorio de Meet",
  "Mein Auto ist startklar, ich kann fahren": "Tengo el coche listo, puedo conducir yo",
  "Meine Einladung": "Mi invitación",
  "Meine Meets": "Mis Meets",
  "Meinen Teil übernehmen": "Aplicar mi parte",
  "Melden": "Denunciar",
  "Melden und {name} blockieren": "Denunciar y bloquear a {name}",
  "Menü": "Menú",
  "Mikrofon": "Micrófono",
  "Mindestens 8 Zeichen.": "Mínimo 8 caracteres.",
  "Mindestens 8 Zeichen. Deinen Namen fragen wir gleich danach.": "Mínimo 8 caracteres. Tu nombre te lo preguntamos justo después.",
  "Mindestens eine Person": "Al menos una persona",
  "Minute": "Minuto",
  "mit {namen}": "con {namen}",
  "mit {namen} +{n}": "con {namen} +{n}",
  "Mit deinem Desteny-Konto anmelden": "Inicia sesión con tu cuenta Desteny",
  "Mit deinem Standort — nur für Vorschläge": "Con tu ubicación — solo para ideas",
  "Mit Desteny-Konto anmelden": "Iniciar sesión con cuenta Desteny",
  "Mit diesem Desteny-Konto meldest du dich bei allen Apps von Desteny Development an.": "Con esta cuenta Desteny inicias sesión en todas las apps de Desteny Development.",
  "mit dir": "contigo",
  "mit E-Mail und Passwort": "con correo y contraseña",
  "Mit wem": "Con quién",
  "Mitbringen": "Para llevar",
  "Mitbringen ändern": "Cambiar lo que llevas",
  "Mitbringen anlegen": "Añadir algo para llevar",
  "Mitbringen löschen": "Quitar elemento",
  "Mitfahren": "Compartir coche",
  "Mitfahrt ins Meet übernehmen": "Añadir el coche al Meet",
  "Mitfahrt speichern": "Guardar viaje",
  "Mitfahrt zuordnen": "Asignar viaje",
  "Mitglieder": "Miembros",
  "Mitnehmen": "Llevar",
  "Mitte von {n} Standort": "Centro de {n} ubicación",
  "Mitte von {n} Standorten": "Centro de {n} ubicaciones",
  "Mitteilungen": "Notificaciones",
  "Mitteilungen auf diesem Gerät": "Notificaciones en este dispositivo",
  "Mitteilungen aufs Handy": "Notificaciones en tu móvil",
  "Mitteilungen aufs iPhone": "Notificaciones en tu iPhone",
  "Mitteilungen einschalten": "Activar notificaciones",
  "Mitteilungen sind an": "Las notificaciones están activadas",
  "Mitteilungen sind vom System blockiert": "El sistema bloquea las notificaciones",
  "Mittel": "Regular",
  "Möchten dich adden": "Quieren añadirte",
  "Mohn": "Amapola",
  "Moment …": "Un momento…",
  "Monat": "Mes",
  "Monat [Einheit]": "mes",
  "Monate [Einheit]": "meses",
  "Mond": "Luna",
  "Monitor": "Monitor",
  "Morgen": "Mañana",
  "morgen, {zeit}": "mañana, {zeit}",
  "Motiv": "Icono",
  "Motorboot": "Lancha motora",
  "Motorrad": "Moto",
  "Müde": "Cansado",
  "Museum": "Museo",
  "Musik": "Música",
  "Muster": "Patrón",
  "nach dem Namen gewählt: {name}": "elegido por el nombre: {name}",
  "Nach rechts": "Hacia la derecha",
  "Nach unten": "Hacia abajo",
  "Nachricht …": "Mensaje…",
  "Nachricht gelöscht": "Mensaje eliminado",
  "Nachricht löschen": "Eliminar mensaje",
  "Nachricht melden": "Denunciar mensaje",
  "Nachricht senden": "Enviar mensaje",
  "Nächste Woche": "Semana siguiente",
  "Nächster Monat": "Mes siguiente",
  "Nacht": "Noche",
  "Nah & draußen": "Cerca y al aire libre",
  "Name": "Nombre",
  "Name der Ressource": "Nombre",
  "Nerd": "Nerd",
  "Neu für euch": "Algo nuevo",
  "Neu laden": "Recargar",
  "Neu: mindestens 8 Zeichen.": "Nueva: mínimo 8 caracteres.",
  "Neue Crew": "Nueva Crew",
  "Neue E-Mail-Adresse": "Nuevo correo",
  "Neue Idee": "Nueva idea",
  "Neue Mitglieder fügen {namen} hinzu.": "Los nuevos miembros los añaden {namen}.",
  "Neue Mitglieder fügt {namen} hinzu.": "Los nuevos miembros los añade {namen}.",
  "Neue Ressource": "Algo para compartir",
  "Neue Umfrage": "Nueva encuesta",
  "Neuer Listenpunkt": "Nuevo elemento de la lista",
  "Neuer Ordner": "Nueva carpeta",
  "Neues Interesse": "Nuevo interés",
  "Neues Meet": "Nuevo Meet",
  "Neues Passwort": "Nueva contraseña",
  "Neues Passwort setzen": "Crear contraseña nueva",
  "Neutral": "Neutral",
  "Nicht dabei": "No voy",
  "Nicht für mich": "No es para mí",
  "Nicht gut": "No muy bien",
  "Nicht mehr übernehmen": "Ya no lo llevo",
  "Nicht öffnen": "No abrir",
  "Nichts": "Nada",
  "Nichts gefunden": "No hay resultados",
  "nichts geplant": "nada planeado",
  "Nichts geplant": "Nada planeado",
  "Nichts geplant.": "Nada planeado.",
  "Niederlande": "Países Bajos",
  "niemand": "nadie",
  "Niemand": "Nadie",
  "Niemand blockiert": "No has bloqueado a nadie",
  "Niemand gefunden für „{suche}“": "Nadie encontrado para «{suche}»",
  "noch {n} wählen": "elige {n} más",
  "Noch etwas": "Algo más",
  "Noch fährt niemand.": "Nadie conduce todavía.",
  "Noch kein Desteny-Konto? Erstellen": "¿Aún no tienes cuenta Desteny? Crear una",
  "Noch kein Verlauf.": "Aún no hay historial.",
  "Noch keine besten Freunde — das Zeichen gilt, sobald du jemanden markierst.": "Aún no tienes mejores amigos — la marca se aplica en cuanto marques a alguien.",
  "Noch keine Crew": "Aún no tienes Crew",
  "Noch keine Freunde": "Aún no tienes amigos",
  "Noch keine Umfrage — hier stimmt ihr gemeinsam ab.": "Aún no hay encuesta — aquí votáis juntos.",
  "Noch keine Vorlagen gespeichert": "Aún no has guardado plantillas",
  "Noch nichts": "Nada todavía",
  "Noch nichts auf der Liste — hier steht, wer was mitbringt.": "Aún no hay nada en la lista — aquí se ve quién trae qué.",
  "Noch nichts drauf — schreib den ersten Punkt.": "La lista está vacía — escribe lo primero.",
  "Noch nichts gemeinsam erlebt": "Todavía nada juntos",
  "Noch nichts geplant": "Aún no hay nada planeado",
  "Noch nichts zusammen erlebt": "Todavía nada juntos",
  "Noch ohne Angabe: {namen}": "Aún sin indicar: {namen}",
  "Nochmal": "Reintentar",
  "Norwegen": "Noruega",
  "Notiz": "Nota",
  "Notiz (optional)": "Nota (opcional)",
  "Notiz hinzufügen": "Añadir nota",
  "Nur {wer} sieht {name}.": "{name} · visible solo para {wer}.",
  "Nur Admins können Personen hinzufügen": "Solo los admins pueden añadir personas",
  "Nur aktiv": "Solo activo",
  "Nur das Meet ansehen": "Solo ver el Meet",
  "Nur der Organisator kann absagen": "Solo quien organiza puede cancelar",
  "Nur der Organisator kann festlegen": "Solo quien organiza puede fijar el plan",
  "Nur die Aktivität übernommen": "Solo se ha copiado la actividad",
  "Nur die grobe Umgebung — die genaue Adresse erst nach Zustimmung.": "Solo la zona aproximada — la dirección exacta, cuando acepte.",
  "nur dieses Feld offen": "solo esto está por decidir",
  "Nur du siehst {name}.": "Solo tú ves {name}.",
  "Nur eigene Vorschläge": "Solo puedes cambiar tus propuestas",
  "Nur Freunde lassen sich hinzufügen": "Solo puedes añadir amigos",
  "Nur für dich": "Solo para ti",
  "Nur für dich — niemand sonst sieht deine Antwort.": "Solo para ti — nadie más ve tu respuesta.",
  "Nur für dich sichtbar": "Solo lo ves tú",
  "Nur ich": "Solo yo",
  "nur kostenlos": "solo gratis",
  "Nur leere Entwürfe": "Solo borradores vacíos",
  "Nur mit Konto": "Solo con cuenta",
  "Nur vom Home-Bildschirm aus": "Solo desde la pantalla de inicio",
  "Nuss": "Avellana",
  "Ocker": "Ocre",
  "offen": "por decidir",
  "Offen": "Pendiente",
  "Öffnen": "Abrir",
  "oft": "a menudo",
  "Oft gemacht": "Ya es un fijo",
  "Ohne Eingabe steht neben dem Namen nur der Name.": "Si lo dejas vacío, solo se verá el nombre.",
  "Ohne feste Aktivität": "Sin actividad fija",
  "ohne Limit": "sin límite",
  "Ohne Meet": "Sin Meet",
  "ohne Meet, aktiv oder kommend": "sin Meet, activo o próximo",
  "Ohne Netz lässt sich kein Ort wählen": "Sin conexión no se puede elegir un lugar",
  "ohne Standort": "sin ubicación",
  "ohne Standort — selbst absprechen": "sin ubicación — acordadlo vosotros",
  "ohne Standortfreigabe": "sin permiso de ubicación",
  "Ohne Standortfreigabe geht es nicht automatisch — „Auf Karte wählen\" bleibt offen. Deine allgemeine Standort-Einstellung bleibt unverändert.": "Sin permiso de ubicación no se puede hacer automáticamente — «Elegir en el mapa» sigue disponible. Tu ajuste general de ubicación no cambia.",
  "Okay": "Vale",
  "Oktopus": "Pulpo",
  "Oldtimer": "Coche clásico",
  "Open-Air Kino": "Cine de verano",
  "Oper unter freiem Himmel — früh buchen, nur bei gutem Wetter.": "Ópera al aire libre — reserva pronto, solo con buen tiempo.",
  "Option {n}": "Opción {n}",
  "Option 1": "Opción 1",
  "Option 2": "Opción 2",
  "Optionen": "Opciones",
  "Orange": "Naranja",
  "Ordner": "Carpeta",
  "Ordner anlegen": "Crear carpeta",
  "Ordner erstellen": "Crear carpeta",
  "Original": "Original",
  "Original bleibt wählbar": "El original sigue disponible",
  "Ort": "Lugar",
  "ORT": "LUGAR",
  "Ort — Zustimmung steht aus": "Lugar — pendiente de aceptar",
  "Ort abgelehnt": "Lugar rechazado",
  "Ort anfragen": "Pedir lugar",
  "Ort angefragt bei {name} — Zustimmung steht noch aus.": "Pedido a {name} quedar en su casa — aún no ha respondido.",
  "Ort angefragt bei der Person — Zustimmung steht noch aus.": "Pedido quedar en casa de esa persona — aún no ha respondido.",
  "Ort bei {name} angefragt — die Adresse erscheint erst nach der Zustimmung.": "Pedido a {name} quedar en su casa — la dirección aparecerá cuando acepte.",
  "Ort bei der gefragten Person angefragt — die Adresse erscheint erst nach der Zustimmung.": "Pedido quedar en casa de esa persona — la dirección aparecerá cuando acepte.",
  "Ort bei dir angefragt — die Adresse erscheint erst nach der Zustimmung.": "Te han pedido quedar en tu casa — la dirección aparecerá cuando aceptes.",
  "Ort blieb offen": "Sin lugar fijado",
  "Ort entfernen": "Quitar lugar",
  "Ort freigegeben": "Lugar aceptado",
  "Ort hinzufügen": "Añadir lugar",
  "Ort offen": "Lugar sin fijar",
  "Ort suchen": "Buscar lugar",
  "Ort suchen …": "Buscar lugar…",
  "Ort übernehmen": "Usar este lugar",
  "Ort übernommen": "Lugar copiado",
  "Ort und Personen übernommen": "Lugar y personas copiados",
  "Ort und Zeit übernommen": "Lugar y hora copiados",
  "Ort, Zeit und Personen übernommen": "Lugar, hora y personas copiados",
  "Orte in deiner Nähe zeigen": "Mostrar lugares cerca de ti",
  "Ortsanfrage beantworten": "Responder a la petición de lugar",
  "Österreich": "Austria",
  "Panda": "Panda",
  "Panorama oben": "Vistas desde arriba",
  "Park, weicher Rasen, ab 4 Personen": "Parque, césped mullido, desde 4 personas",
  "Party": "Fiesta",
  "Passt": "Vale",
  "Passt zu euch": "Para vosotros",
  "Passt zu: {interesse}": "Encaja: {interesse}",
  "Passwort": "Contraseña",
  "Passwort ändern": "Cambiar contraseña",
  "Passwort anzeigen": "Mostrar contraseña",
  "Passwort festlegen": "Elige una contraseña",
  "Passwort geändert.": "Contraseña cambiada.",
  "Passwort verbergen": "Ocultar contraseña",
  "Passwort vergessen?": "¿Has olvidado la contraseña?",
  "Passwort wiederholen": "Repetir contraseña",
  "Pasta": "Pasta",
  "Pasta danach": "Pasta después",
  "Pasta für alle — wer die größte Küche hat, lädt ein.": "Pasta para todos — invita quien tenga la cocina más grande.",
  "Pasta für alle, zusammen in einer Küche": "Pasta para todos, juntos en una cocina",
  "Pavillon": "Carpa",
  "PC": "PC",
  "Perfekt, bis 21 Uhr geblieben": "Perfecto, me quedé hasta las 21:00",
  "Person blockieren": "Bloquear persona",
  "Person blockiert": "Persona bloqueada",
  "Person ist kein Mitglied": "Esa persona no es miembro",
  "Person ist nicht mehr blockiert": "Persona desbloqueada",
  "Personen · {n}": "Personas · {n}",
  "Personen hinzufügen": "Añadir personas",
  "Personen übernommen": "Personas copiadas",
  "Personen-Kapazität": "Capacidad (personas)",
  "Petrol": "Petróleo",
  "Pfänder": "Pfänder",
  "Pfänder-Runde": "Ruta al Pfänder",
  "Picknick": "Pícnic",
  "Picknickkorb": "Cesta de pícnic",
  "Pilz": "Seta",
  "Pinguin": "Pingüino",
  "Pink": "Rosa",
  "Pizza": "Pizza",
  "Pizza am Hafen": "Pizza en el puerto",
  "Pizza bei Mira": "Pizza en casa de Mira",
  "Planen": "Planear",
  "Plattenspieler": "Tocadiscos",
  "Plätze für Mitfahrer": "Plazas para pasajeros",
  "Polen": "Polonia",
  "Pool": "Piscina",
  "Portugal": "Portugal",
  "Privat": "Privacidad",
  "Privat: {namen}": "Privado: {namen}",
  "Private Ressource": "Privado",
  "Private Ressourcen sehen": "Ven tus cosas privadas",
  "Privatsphäre & Freigaben": "Privacidad y compartir",
  "Probe-Mitteilung senden": "Enviar notificación de prueba",
  "Profil": "Perfil",
  "Profil ›": "Perfil ›",
  "Profil bearbeiten": "Editar perfil",
  "Profil gespeichert": "Perfil guardado",
  "Profil speichern": "Guardar perfil",
  "Profilbild": "Imagen de perfil",
  "Profilbild ändern": "Cambiar foto de perfil",
  "Profilbild gestalten": "Crear foto de perfil",
  "Profilbild übernommen": "Imagen de perfil guardada",
  "Profilbild von {name}": "Foto de perfil de {name}",
  "Profilbild von {name} groß ansehen": "Ver en grande la foto de perfil de {name}",
  "Propellerflugzeug": "Avioneta",
  "PS5": "PS5",
  "Punkte": "Puntos",
  "QR-Code scannen": "Escanear código QR",
  "Quelle öffnen": "Ver la fuente",
  "Raclette": "Raclette",
  "Radfahren": "Bici",
  "Radtouren": "Rutas en bici",
  "Rakete": "Cohete",
  "Rallyeauto": "Coche de rally",
  "Rasenmäher": "Cortacésped",
  "Raum": "Espacio",
  "Raum {raum} nicht auflösbar": "No se encuentra la sala {raum}",
  "Raumschiff": "Nave espacial",
  "regelmäßig": "regularmente",
  "Regen angesagt": "Se espera lluvia",
  "Regenbogen": "Arcoíris",
  "Rennwagen": "Coche de carreras",
  "Ressource entfernen": "Quitar de tus cosas",
  "Ressource entfernt": "Quitado de tus cosas",
  "Ressource gibt es schon": "Eso ya está en tu lista",
  "Ressource hinzufügen": "Añadir algo",
  "Ressource hinzugefügt": "Añadido a tus cosas",
  "Ressourcen": "Cosas",
  "Ressourcen speichern": "Guardar tus cosas",
  "Richtung": "Dirección",
  "Ringe": "Anillos",
  "Roboter": "Robot",
  "Rosé": "Rosa palo",
  "Rot": "Rojo",
  "Route": "Ruta",
  "Route mit Abholungen": "Ruta con recogidas",
  "Route mit Abholungen in {karte} öffnen": "Abrir la ruta con recogidas en {karte}",
  "Route öffnen": "Abrir ruta",
  "Rückgängig": "Deshacer",
  "Rucksack": "Mochila",
  "Ruhe & Kreatives": "Calma y creatividad",
  "Salbei": "Salvia",
  "Samstag": "Sábado",
  "Satellit": "Satélite",
  "Saturn": "Saturno",
  "Scannen geht hier nicht — gib den Code unten ein.": "Aquí no se puede escanear — escribe el código abajo.",
  "Schaf": "Oveja",
  "Schalte den Standort oben ein, um zu wählen, wer ihn sieht.": "Activa la ubicación arriba para elegir quién la ve.",
  "Schau in dein Postfach. Der Link ist eine Stunde gültig.": "Mira tu bandeja de entrada. El enlace vale durante una hora.",
  "Schiffe": "Barcos",
  "Schlafsack": "Saco de dormir",
  "Schließen": "Cerrar",
  "Schlitten": "Trineo",
  "Schnee": "Nieve",
  "Schnell startklar": "Listo en nada",
  "Schnelle Runde im Park — Ball und Netz mitbringen.": "Partida rápida en el parque — trae pelota y red.",
  "Schon ein Desteny-Konto? Anmelden": "¿Ya tienes cuenta Desteny? Iniciar sesión",
  "Schon gespeichert · {n}": "Ya guardadas · {n}",
  "Schräg nach links unten": "En diagonal, hacia abajo a la izquierda",
  "Schräg nach rechts unten": "En diagonal, hacia abajo a la derecha",
  "Schubkarre": "Carretilla",
  "Schweden": "Suecia",
  "Schwein": "Cerdo",
  "Schweiz": "Suiza",
  "Schwester": "Hermana",
  "Schwimmen": "Nadar",
  "Schwimmen im See": "Nadar en el lago",
  "See": "Lago",
  "See & Chill": "Lago y relax",
  "See, Wiese und Pizza direkt daneben": "Lago, césped y pizza justo al lado",
  "Seebühne": "Seebühne",
  "Seebühne: Carmen": "Seebühne: Carmen",
  "Segelboot": "Velero",
  "Sehen, wer Zeit hat. Und daraus etwas machen.": "Mira quién tiene tiempo. Y monta un plan.",
  "seit {zeit}": "desde las {zeit}",
  "Senden": "Enviar",
  "Serbien": "Serbia",
  "Serien": "Series",
  "Servus! Am Wochenende was am Damm machen?": "¡Buenas! ¿Hacemos algo en el dique este finde?",
  "Shopping": "Compras",
  "Sie gilt, sobald du den Link in der Mail angeklickt hast.": "Se activará en cuanto pulses el enlace del correo.",
  "Sieht gleich aus wie das Zeichen deiner besonderen Person.": "Se ve igual que la marca de tu persona especial.",
  "Ski": "Esquís",
  "Slackline": "Slackline",
  "Smaragd": "Esmeralda",
  "Snowboard": "Snowboard",
  "So kommen Mitteilungen von Crew an.": "Así llegan las notificaciones de Crew.",
  "So sehen dich deine Freunde. Änderbar im Profil.": "Así te ven tus amigos. Puedes cambiarlo en tu perfil.",
  "So sieht dich deine Crew": "Así te ve tu Crew",
  "So sieht eure Gruppe aus": "Así se ve vuestro grupo",
  "Social": "Redes",
  "Social öffnen": "Abrir redes",
  "Sofa": "Sofá",
  "Sommer": "Verano",
  "Sonne": "Sol",
  "Sonnenaufgang Pfänder": "Amanecer en el Pfänder",
  "Sonnenbrille": "Gafas de sol",
  "Sonnenschirm": "Sombrilla",
  "Spam": "Spam",
  "Spanien": "España",
  "Später": "Más tarde",
  "Später — direkt zu Crew": "Luego — ir directo a Crew",
  "Spätestens {zeit}": "Como tarde, {zeit}",
  "Spazieren": "Pasear",
  "Speichern": "Guardar",
  "Speichern und weiter": "Guardar y continuar",
  "Spiele": "Juegos",
  "Spieleabend": "Noche de juegos",
  "Spieleabend bei Noah": "Noche de juegos en casa de Noah",
  "Spielesammlung": "Colección de juegos",
  "Spikeball": "Spikeball",
  "Spikeball im Park": "Spikeball en el parque",
  "Spikeball-Turnier": "Torneo de spikeball",
  "Spontan treffen": "Quedar ahora",
  "Spontanes Treffen": "Meet espontáneo",
  "Sport": "Deporte",
  "Sport & draußen": "Deporte y aire libre",
  "Sport-Runde": "Los del deporte",
  "Sportwagen": "Deportivo",
  "Sprache": "Idioma",
  "Standard": "Por defecto",
  "Standard 00:00": "Por defecto 00:00",
  "Standard: aus": "Por defecto: desactivado",
  "Stände am Dorfplatz und Livemusik": "Puestos en la plaza y música en directo",
  "Stände am Dorfplatz und Livemusik — Eintritt frei, Gläser gegen Pfand.": "Puestos en la plaza y música en directo — entrada gratis, copas con fianza.",
  "Standort": "Ubicación",
  "Standort ansehen: {ort}": "Ver ubicación: {ort}",
  "Standort für Vorschläge": "Ubicación para sugerencias",
  "Standort gerade nicht verfügbar": "Ubicación no disponible ahora",
  "Standort nicht erlaubt — du kannst ihn in den Einstellungen deines Geräts freigeben.": "Ubicación no permitida — puedes activarla en los ajustes de tu dispositivo.",
  "Standort nicht mehr teilen": "Dejar de compartir la ubicación",
  "Standort senden?": "¿Enviar ubicación?",
  "Standort teilen": "Compartir ubicación",
  "Standort teilen mit": "Compartir ubicación con",
  "Standort verwenden": "Usar ubicación",
  "Standort wird abgefragt …": "Obteniendo tu ubicación …",
  "Stativ": "Trípode",
  "Statt „{titel}\" — oder als Alternative dazu?": "¿En lugar de «{titel}» — o como alternativa?",
  "Statt „{titel}\" und {n} weitere — oder als Alternative dazu?": "¿En lugar de «{titel}» y {n} más — o como alternativa?",
  "Stattdessen blockieren und melden": "Mejor bloquear y denunciar",
  "Steht nichts Passendes dabei?": "¿No encuentras lo tuyo?",
  "Stern": "Estrella",
  "Sterne": "Estrellas",
  "Stimme setzen": "Votar",
  "Stimme zurücknehmen": "Retirar voto",
  "Strandbad": "Strandbad",
  "Strandbad + Pizza": "Strandbad + pizza",
  "Strandbad Bregenz": "Strandbad Bregenz",
  "Streifen": "Rayas",
  "Stunde": "Hora",
  "Suche läuft …": "Buscando…",
  "Suche leeren": "Borrar búsqueda",
  "Suche oben — oder tippe auf die Karte.": "Busca arriba — o toca el mapa.",
  "Suchen …": "Buscar…",
  "Supabase-Bibliothek nicht ladbar": "No se ha podido cargar la biblioteca de Supabase",
  "Surfbrett": "Tabla de surf",
  "Symbol": "Icono",
  "Symbol ändern": "Cambiar icono",
  "Symbol für {name}": "Icono para {name}",
  "Symbol oder Emoji": "Icono o emoji",
  "Symbol wählen": "Elegir icono",
  "System": "Sistema",
  "Tablet": "Tablet",
  "Tage": "Días",
  "Tanne": "Abeto",
  "Taube": "Azul grisáceo",
  "Technik": "Tecnología",
  "Teilen": "Compartir",
  "Teilnahme absagen": "Cancelar asistencia",
  "Teilnahme speichern": "Guardar asistencia",
  "Teilnehmende": "Participantes",
  "Teilnehmende aktualisiert": "Participantes actualizados",
  "Teilnehmende ändern": "Cambiar participantes",
  "Teilnehmende bearbeiten": "Editar participantes",
  "Temporäre Räume": "Salas temporales",
  "Termine · {n}": "Fechas · {n}",
  "Text: {quelle}": "Texto: {quelle}",
  "Thermoskanne": "Termo",
  "Tickets": "Entradas",
  "Tickets & Infos": "Entradas e info",
  "Tiere": "Animales",
  "Tiger": "Tigre",
  "Tischtennis": "Ping-pong",
  "Titel": "Título",
  "Töne": "Sonidos",
  "Top — ich fahr, 3 Plätze frei": "Genial — conduzco yo, quedan 3 plazas",
  "Tränen lachen": "Llorar de risa",
  "Treffen planen": "Organizar un plan",
  "Treffpunkt bleibt Fluh, oder?": "Seguimos quedando en Fluh, ¿no?",
  "Trinken": "Tomar algo",
  "Trinken gehen": "Tomar algo",
  "Tschechien": "Chequia",
  "Türkei": "Turquía",
  "Türkis": "Turquesa",
  "U-Boot": "Submarino",
  "über {name}": "con {name}",
  "über Link": "por enlace",
  "Übernehmen": "Aceptar",
  "Übernehmen können Fahrer, Mitfahrer oder wer das Meet erstellt hat.": "Pueden aplicarlo los conductores, los pasajeros o quien creó el Meet.",
  "übernommen": "cubierto",
  "UFO": "OVNI",
  "Uhr": "Reloj",
  "Ukraine": "Ucrania",
  "Umfrage": "Encuesta",
  "Umfrage anlegen": "Crear encuesta",
  "Umfrage bei „{titel}“": "Encuesta en «{titel}»",
  "Umfrage erstellen": "Crear encuesta",
  "Umfrage im Raum": "Encuesta en la sala",
  "Umfrage im Raum anlegen": "Crear encuesta en la sala",
  "Umfragen": "Encuestas",
  "Umfragen · {n}": "Encuestas · {n}",
  "Umkreis": "Radio",
  "Umkreis · bis {km} km · {n} Ort": "Radio · hasta {km} km · {n} lugar",
  "Umkreis · bis {km} km · {n} Orte": "Radio · hasta {km} km · {n} lugares",
  "Umkreis entfernen": "Quitar radio",
  "Unangemessene Inhalte": "Contenido inapropiado",
  "Unbekannt": "Desconocido",
  "Unbekannte Meet-Teilnehmende sehen": "Qué ven los desconocidos en un Meet",
  "Ungarn": "Hungría",
  "Ungefähr, nur auf diesem Gerät gespeichert.": "Aproximada, guardada solo en este dispositivo.",
  "Unterwegs": "Fuera",
  "Updates & Zusammenfassungen": "Novedades y resúmenes",
  "USA": "EE. UU.",
  "Verbunden": "Conectado",
  "verfügbar · für · wer": "disponible · para · quién",
  "Verfügbarkeit": "Disponibilidad",
  "Vergessen": "Olvidar",
  "Vergrößern": "Acercar",
  "Verkehrsflugzeug": "Avión de pasajeros",
  "Verkleinern": "Alejar",
  "Verlassen": "Salir",
  "Verlauf": "Historial",
  "Verliebt": "Enamorado",
  "Verschoben": "Aplazado",
  "Verwalten": "Gestionar",
  "Violett": "Violeta",
  "Vogel": "Pájaro",
  "voll": "lleno",
  "Voll": "Lleno",
  "Volleyball": "Vóley",
  "Vollständiges Profil": "Perfil completo",
  "Vom System blockiert": "Bloqueadas por el sistema",
  "Von": "Desde",
  "Von der Mitte aus": "Desde el centro",
  "Von dir gesendet": "Enviadas por ti",
  "Von mir gesendet · {n}": "Enviadas por mí · {n}",
  "Von und Bis sind gleich": "El inicio y el final son iguales",
  "vor {n} min": "hace {n} min",
  "vor {n} Minute": "hace {n} minuto",
  "vor {n} Minuten": "hace {n} minutos",
  "vor {n} Stunde": "hace {n} hora",
  "vor {n} Stunden": "hace {n} horas",
  "Vorheriger Monat": "Mes anterior",
  "Vorige Woche": "Semana anterior",
  "Voriger Monat": "Mes anterior",
  "Vorlage gespeichert": "Plantilla guardada",
  "Vorname": "Solo el nombre",
  "Vorschlag": "Propuesta",
  "Vorschlag ändern": "Editar propuesta",
  "Vorschlag anlegen": "Crear propuesta",
  "Vorschlag ausblenden": "Ocultar sugerencia",
  "Vorschlag bearbeiten": "Editar propuesta",
  "Vorschlag entfernen": "Quitar propuesta",
  "Vorschlag für „{titel}\": {idee}": "Propuesta para «{titel}»: {idee}",
  "Vorschlag für {titel}": "Propuesta para {titel}",
  "Vorschlag gesendet": "Propuesta enviada",
  "Vorschlag gespeichert": "Propuesta guardada",
  "Vorschlag senden": "Enviar propuesta",
  "Vorschlag übernehmen": "Aplicar sugerencia",
  "Vorschlag übernommen": "Sugerencia aplicada",
  "Vorschlag: {idee}": "Propuesta: {idee}",
  "Vorschlag: {name} holt dich ab": "Sugerencia: {name} te recoge",
  "Vorschlagen": "Proponer",
  "VR-Brille": "Gafas de RV",
  "Wähl mindestens einen Tag": "Elige al menos un día",
  "Wähl zuerst, wie es war": "Primero elige qué tal fue",
  "Wähle oben, bei wem ihr euch trefft.": "Elige arriba en casa de quién quedar.",
  "Wählen": "Elegir",
  "Wal": "Ballena",
  "Wald": "Bosque",
  "Wandern": "Senderismo",
  "Wandern am Pfänder": "Ruta por el Pfänder",
  "Wandern Pfänder": "Excursión al Pfänder",
  "Wann": "Cuándo",
  "Wann passt es?": "¿Cuándo va bien?",
  "Wartet": "Pendiente",
  "Wartet auf Bestätigung: {email}": "Pendiente de confirmar: {email}",
  "Warum meldest du?": "¿Por qué lo denuncias?",
  "Was Crew gelernt hat": "Lo que Crew ha aprendido",
  "Was die Vorlage mitnimmt": "Qué guarda la plantilla",
  "Was es gekostet hat": "Lo que costó",
  "Was habt ihr vor?": "¿Qué plan hay?",
  "Was ihr gemacht habt": "Lo que hicisteis",
  "Was kochen wir?": "¿Qué cocinamos?",
  "Was machen wir?": "¿Qué hacemos?",
  "Was machen?": "¿Qué hacemos?",
  "Was machst du gern?": "¿Qué te gusta hacer?",
  "Was soll jemand mitbringen?": "¿Qué hay que llevar?",
  "Was war los?": "¿Qué pasó?",
  "Was?": "¿Qué?",
  "Waschbär": "Mapache",
  "Wasser & Schnee": "Agua y nieve",
  "Wasser hat 24 Grad 🌊": "El agua está a 24 grados 🌊",
  "Wasserflugzeug": "Hidroavión",
  "Website": "Web",
  "Wechseln": "Cambiar",
  "Weinfest": "Fiesta del vino",
  "Weinfest Lochau": "Fiesta del vino de Lochau",
  "Weiter": "Continuar",
  "Weiter bearbeiten": "Seguir editando",
  "weiter zu": "continuar a",
  "Weitere": "Otros",
  "Weitere Freunde": "Más amigos",
  "Weitere Interessen": "Más intereses",
  "Welle": "Ola",
  "Wellen": "Olas",
  "Weltall": "Espacio",
  "Weniger anzeigen": "Ver menos",
  "Wenn dich jemand anstupst": "Cuando alguien te da un toque",
  "wer bringt was mit": "quién lleva qué",
  "Wer fährt?": "¿Quién conduce?",
  "Wer hätte Samstag Bock auf den Pfänder?": "¿Quién se apunta al Pfänder el sábado?",
  "Wer ist frei? Was machen wir?": "¿Quién está libre? ¿Qué hacemos?",
  "Wer schreibt, wer frei ist": "Quién escribe, quién está libre",
  "Werkzeug": "Herramientas",
  "Werkzeug & Garten": "Herramientas y jardín",
  "Wetter soll top werden, viel Sonne": "Dicen que hará un tiempo genial, mucho sol",
  "Wie das Gerät": "Como el dispositivo",
  "Wie heißt du?": "¿Cómo te llamas?",
  "Wie heißt ihr?": "¿Cómo se llama la Crew?",
  "Wie kommst du hin?": "¿Cómo vas?",
  "wie oft gemeinsam": "cuántas veces juntos",
  "Wie oft gerade?": "¿Con qué frecuencia ahora?",
  "Wie schaut’s Donnerstag aus?": "¿Qué tal el jueves?",
  "Wie war {titel}?": "¿Qué tal {titel}?",
  "Wie war der See gestern?": "¿Qué tal ayer en el lago?",
  "Wie war's?": "¿Qué tal fue?",
  "Wie war’s?": "¿Qué tal fue?",
  "Wieder möglich in {zeit}": "Podrás repetir en {zeit}",
  "Wieder zeigen": "Mostrar de nuevo",
  "Wiederholung": "Repetición",
  "Wiese am See mit Sprungturm und Kiosk — Eintritt frei.": "Césped junto al lago con trampolín y chiringuito — entrada gratis.",
  "Wiese oder Grillplatz, Grill und Kohle mitnehmen": "Prado o zona de barbacoa; lleva parrilla y carbón",
  "Wikingerschiff": "Barco vikingo",
  "Wir haben an {email} eine Bestätigung geschickt. Die Adresse gilt, sobald du den Link angeklickt hast.": "Te hemos enviado una confirmación a {email}. La dirección se activará en cuanto pulses el enlace.",
  "Wir haben dir eine E-Mail geschickt. Bestätige sie und melde dich dann an.": "Te hemos enviado un correo. Confírmalo y luego inicia sesión.",
  "Wir haben dir einen Link an {email} geschickt.": "Te hemos enviado un enlace a {email}.",
  "wird gebraucht": "hace falta",
  "Wird mit eingeladen": "También se invitará",
  "Wird nachgeschlagen …": "Buscando…",
  "Woche": "Semana",
  "Woche [Einheit]": "semana",
  "Wochen [Einheit]": "semanas",
  "Wochenende": "Fin de semana",
  "Wolf": "Lobo",
  "Womit fängst du an?": "¿Por dónde empiezas?",
  "Woran lag’s genau?": "¿A qué se debió?",
  "Worauf hast du Lust?": "¿De qué tienes ganas?",
  "Worüber soll abgestimmt werden?": "¿Sobre qué se vota?",
  "Yoga": "Yoga",
  "z. B. Anhänger": "p. ej., remolque",
  "z. B. Freundin": "p. ej., novia",
  "z. B. Padel": "p. ej., pádel",
  "Zeichen": "Marca",
  "Zeichen für beste Freunde": "Marca de mejores amigos",
  "Zeichen für beste Freunde gespeichert": "Marca de mejores amigos guardada",
  "Zeile entfernen": "Quitar fila",
  "Zeit": "Hora",
  "Zeit · {n} Vorschlag": "Hora · {n} propuesta",
  "Zeit · {n} Vorschläge": "Hora · {n} propuestas",
  "Zeit abstimmen": "Votar hora",
  "Zeit festgelegt": "Hora fijada",
  "Zeit offen": "Hora sin fijar",
  "Zeit übernommen": "Hora copiada",
  "Zeit und Personen übernommen": "Hora y personas copiadas",
  "Zeit vorgeschlagen": "Hora propuesta",
  "Zeit vorschlagen": "Proponer hora",
  "Zeiten entfernen": "Quitar horarios",
  "Zeiten entfernt": "Horarios quitados",
  "Zeiten gespeichert": "Horarios guardados",
  "Zeiten hinzufügen": "Añadir horarios",
  "Zeiten hinzugefügt": "Horarios añadidos",
  "Zeitraum": "Periodo",
  "Zeitvorschläge ansehen": "Ver propuestas de hora",
  "Zelt": "Tienda de campaña",
  "Ziehen": "Arrastrar",
  "Ziehen zum Verschieben · Mausrad oder Regler zum Zoomen": "Arrastra para mover · rueda o control para ampliar",
  "Ziehen zum Verschieben · mit zwei Fingern zoomen": "Arrastra para mover · pellizca para ampliar",
  "Ziel": "Destino",
  "Ziel wählen": "Elegir destino",
  "Zielflagge": "Bandera a cuadros",
  "Zoom": "Zoom",
  "Zu besonderer Person wechseln?": "¿Cambiar a persona especial?",
  "Zu bestem Freund wechseln?": "¿Cambiar a mejor amigo?",
  "Zu diesem Konto gibt es keine E-Mail-Adresse.": "Esta cuenta no tiene correo.",
  "Zu dieser E-Mail gibt es schon ein Konto — melde dich an": "Ya hay una cuenta con este correo — inicia sesión",
  "Zu viele Versuche. Bitte später noch einmal.": "Demasiados intentos. Vuelve a probar más tarde.",
  "Zuerst Freunde<br>hinzufügen": "Primero añade<br>amigos",
  "Zuhause": "Casa",
  "Zuhause & Alltag": "Casa y día a día",
  "Zuhause, ab 4 Personen am besten": "En casa, mejor desde 4 personas",
  "Zuhause, ab 4 Personen am besten — ein paar Spiele reichen.": "En casa, mejor desde 4 personas — con unos cuantos juegos basta.",
  "Zum Home-Bildschirm": "Añadir a pantalla de inicio",
  "zum Namen passt nichts — wähl unten selbst": "nada encaja con el nombre — elige tú abajo",
  "Zur Crew": "Ir a la Crew",
  "Zurück": "Atrás",
  "Zurück zu meiner Einladung": "Volver a mi invitación",
  "Zurück zur Anmeldung": "Volver a iniciar sesión",
  "Zurückgenommen · wieder in {n} min": "Retirado · de nuevo en {n} min",
  "Zurücksetzen": "Restablecer",
  "Zurücksetzen fehlgeschlagen: {fehler}": "No se ha podido restablecer: {fehler}",
  "Zurückstupsen": "Devolver el toque",
  "Zurückziehen": "Retirar",
  "Zusage geändert": "Respuesta cambiada",
  "Zusage offen": "Sin confirmar",
  "zusammen kochen": "cocinar juntos",
  "Zusammenfassen": "Resumir",
  "Zustimmung steht aus": "Pendiente de aceptar",
  "Zustimmung steht aus · {ort}": "Pendiente de aceptar · {ort}",
  "Zwei Antworten braucht es mindestens": "Hacen falta al menos dos respuestas",
  "Zwei Farben, die ineinander übergehen": "Dos colores que se funden entre sí",
  "Zweite Farbe": "Segundo color",
};
