// Übersetzungen (fr). Schlüssel = deutscher Satz aus dem Quelltext, siehe web/core/sprache.js.
// Nicht von Hand zusammenführen: scripts/sprachen-bauen.mjs. Prüfen: node scripts/sprachen-pruefen.mjs
export default {
  "„{name}\" hinzugefügt": "« {name} » ajouté",
  "„{titel}\" ausgeblendet": "« {titel} » masqué",
  "„{titel}“ hat einen eigenen Gruppenchat mit allen, die dabei sind. Du verlässt dafür den Chat mit {name}.": "« {titel} » a son propre chat de groupe avec tous les participants. Tu quittes pour cela ta discussion avec {name}.",
  "„{titel}“ läuft in der Gruppe {gruppe}. Dort schreibt ihr alle zusammen — du verlässt dafür den Chat mit {name}.": "« {titel} » se passe dans le groupe {gruppe}. Tout le monde y discute ensemble — tu quittes pour cela ta discussion avec {name}.",
  "„Daheim\" hat keine Karte — es gibt dort nichts zu verorten.": "« Chez soi » n'a pas de carte — il n'y a rien à y placer.",
  "{a} und {b} sind auch frei": "{a} et {b} sont libres aussi",
  "{a} und {b} warten auf Antwort": "{a} et {b} attendent ta réponse",
  "{a}, {b} und {n} weitere sind auch frei": "{a}, {b} et {n} autres sont libres aussi",
  "{a}, {b} und {n} weitere warten auf Antwort": "{a}, {b} et +{n} attendent ta réponse",
  "{a}, {b} und eine weitere Person sind auch frei": "{a}, {b} et une autre personne sont libres aussi",
  "{aktion} hat nicht geklappt": "{aktion} : ça n'a pas marché",
  "{an}alle{aus}{rad}{an}Jahr{aus}": "{an}tous les{aus}{rad}{an}an{aus}",
  "{an}alle{aus}{rad}{an}Jahre{aus}": "{an}tous les{aus}{rad}{an}ans{aus}",
  "{an}alle{aus}{rad}{an}Monat{aus}": "{an}tous les{aus}{rad}{an}mois{aus}",
  "{an}alle{aus}{rad}{an}Monate{aus}": "{an}tous les{aus}{rad}{an}mois{aus}",
  "{an}alle{aus}{rad}{an}Woche{aus}": "{an}toutes les{aus}{rad}{an}semaine{aus}",
  "{an}alle{aus}{rad}{an}Wochen{aus}": "{an}toutes les{aus}{rad}{an}semaines{aus}",
  "{antwort} — deine Stimme": "{antwort} — ton vote",
  "{belegt} von {n} Platz": "{belegt} sur {n} place",
  "{belegt} von {n} Plätzen": "{belegt} sur {n} places",
  "{bereich} zuklappen": "Replier {bereich}",
  "{frei}/{alle} frei": "{frei}/{alle} libres",
  "{h} Uhr": "{h} h",
  "{n} dabei": "{n} de la partie",
  "{n} frei": "{n} dispo",
  "{n} Freund": "{n} ami",
  "{n} Freund:in gewählt": "{n} ami choisi",
  "{n} Freund:innen gewählt": "{n} amis choisis",
  "{n} Freunde": "{n} amis",
  "{n} gemeinsame Crew ›": "{n} Crew en commun ›",
  "{n} gemeinsame Crews ›": "{n} Crews en commun ›",
  "{n} gemeinsame Freunde · über {name}": "{n} amis en commun · via {name}",
  "{n} gewählt": "Sélection : {n}",
  "{n} Idee": "{n} idée",
  "{n} Ideen": "{n} idées",
  "{n} Loop": "{n} Loop",
  "{n} Loops": "{n} Loops",
  "{n} Meet": "{n} Meet",
  "{n} Meets": "{n} Meets",
  "{n} Min": "{n} min",
  "{n} Min.": "{n} min",
  "{n} Mitglied": "{n} membre",
  "{n} Mitglied ›": "{n} membre ›",
  "{n} Mitglieder": "{n} membres",
  "{n} Mitglieder ›": "{n} membres ›",
  "{n} neu — sie bekommen eine Einladung und denselben Meet-Chat.": "{n} nouvelles personnes — elles reçoivent une invitation et rejoignent le chat du Meet.",
  "{n} neu — sie bekommt eine Einladung und denselben Meet-Chat.": "{n} nouvelle personne — elle reçoit une invitation et rejoint le chat du Meet.",
  "{n} neue Nachricht": "{n} nouveau message",
  "{n} neue Nachrichten": "{n} nouveaux messages",
  "{n} offene Anfragen": "{n} demandes en attente",
  "{n} Person": "{n} personne",
  "{n} Person eingeladen": "{n} personne invitée",
  "{n} Person hinzufügen": "Ajouter {n} personne",
  "{n} Person ist jetzt in {crew}": "{n} personne fait maintenant partie de {crew}",
  "{n} Personen": "{n} personnes",
  "{n} Personen eingeladen": "{n} personnes invitées",
  "{n} Personen hinzufügen": "Ajouter {n} personnes",
  "{n} Personen sind jetzt in {crew}": "{n} personnes font maintenant partie de {crew}",
  "{n} Platz frei": "{n} place libre",
  "{n} Plätze frei": "{n} places libres",
  "{n} Punkte bei „{titel}“": "{n} éléments ajoutés à « {titel} »",
  "{n} Std": "{n} h",
  "{n} Std.": "{n} h",
  "{n} Stimme": "{n} vote",
  "{n} Stimmen": "{n} votes",
  "{n} suchen": "{n} cherchent",
  "{n} suchen noch": "{n} cherchent encore",
  "{n} sucht": "{n} cherche",
  "{n} sucht noch": "{n} cherche encore",
  "{n} Teilnehmende ›": "{n} participants ›",
  "{n} teilnehmende Person ›": "{n} participant ›",
  "{n} Vorschlag": "{n} proposition",
  "{n} Vorschläge": "{n} propositions",
  "{n} Zuordnung ging nicht mehr": "{n} passage n'a pas pu être enregistré",
  "{n} Zuordnungen gingen nicht mehr": "{n} passages n'ont pas pu être enregistrés",
  "{n}× gewählt": "{n}× choisi",
  "{n}× nein": "{n}× non",
  "{n}× übergangen": "{n}× ignoré",
  "{name} absetzen": "Retirer {name} de ta voiture",
  "{name} angestupst · {wort}": "{name} t'a fait signe · {wort}",
  "{name} aufgelöst": "{name} supprimé",
  "{name} bietet eine {an}Mitfahrt{aus} an": "{name} propose un {an}covoit{aus}",
  "{name} blockieren?": "Bloquer {name} ?",
  "{name} blockiert": "Tu as bloqué {name}",
  "{name} bringt etwas mit": "{name} apporte quelque chose",
  "{name} bringt’s": "{name} s'en charge",
  "{name} entfernt": "{name} retiré de tes amis",
  "{name} erwähnt {wort}": "{name} parle de {wort}",
  "{name} fährt": "{name} conduit",
  "{name} fährt gerade nicht": "{name} ne conduit pas pour l'instant",
  "{name} fährt noch nicht — du stehst bei „sucht noch“": "{name} ne conduit pas encore — tu es dans « cherche encore »",
  "{name} fragt, ob {titel} bei dir stattfinden kann. Deine Adresse sehen die anderen erst, wenn du zustimmst.": "{name} demande si {titel} peut avoir lieu chez toi. Les autres ne verront ton adresse qu'une fois que tu auras accepté.",
  "{name} hat angestupst": "{name} a fait un signe",
  "{name} hat dich angestupst · Lust auf etwas?": "{name} t'a fait signe · envie de faire un truc ?",
  "{name} hat dich zu Crew geholt.": "{name} t'a fait venir sur Crew.",
  "{name} hatte dich angestupst": "{name} t'avait fait signe",
  "{name} hätte Lust auf {wort}": "{name} a envie de {wort}",
  "{name} holt {namen} ab": "{name} passe prendre {namen}",
  "{name} ist auch frei": "{name} est libre aussi",
  "{name} ist gerade frei": "{name} est libre en ce moment",
  "{name} ist jetzt dein Freund": "{name} fait maintenant partie de tes amis",
  "{name} ist jetzt in {crew}": "{name} fait maintenant partie de {crew}",
  "{name} ist nicht mehr blockiert": "Tu as débloqué {name}",
  "{name} ist nicht mehr dein:e Freund:in": "{name} ne fait plus partie de tes amis",
  "{name} ist schon dein Freund": "{name} fait déjà partie de tes amis",
  "{name} mitnehmen": "Emmener {name}",
  "{name} sucht eine {an}Mitfahrgelegenheit{aus}": "{name} cherche un {an}covoit{aus}",
  "{name} trägt gerade den goldenen Ring. Ein eigenes Zeichen ersetzt ihn — beides zusammen geht nicht.": "{name} a déjà l'anneau doré. Un signe perso le remplace — impossible d'avoir les deux.",
  "{name} trägt gerade ein eigenes Zeichen („{label}\"). Der goldene Ring ersetzt es — beides zusammen geht nicht.": "{name} a déjà un signe perso (« {label} »). L'anneau doré le remplace — impossible d'avoir les deux.",
  "{name} trägt gerade ein eigenes Zeichen. Der goldene Ring ersetzt es — beides zusammen geht nicht.": "{name} a déjà un signe perso. L'anneau doré le remplace — impossible d'avoir les deux.",
  "{name} und {n} weitere Person": "{name} et {n} autre personne",
  "{name} und {n} weitere Personen": "{name} et {n} autres personnes",
  "{name} verlassen": "Tu as quitté {name}",
  "{name} verlassen?": "Quitter {name} ?",
  "{name} wartet auf Antwort": "{name} attend ta réponse",
  "{name}: {lust}": "{name} : {lust}",
  "{name}: {text}": "{name} : {text}",
  "{name}: frei ab {zeit}": "{name} : libre dès {zeit}",
  "{name}: im Meet": "{name} : en Meet",
  "{name}: im Meet · {titel}": "{name} : en Meet · {titel}",
  "{namen} gibt's schon als {an}„{name}\" ›{aus} — du kannst trotzdem neu erstellen.": "{namen} : il y a déjà {an}« {name} » ›{aus} — tu peux quand même en créer une.",
  "{namen} suchen dann wieder.": "{namen} chercheront de nouveau.",
  "{namen} sucht dann wieder.": "{namen} cherchera de nouveau.",
  "{ort} angefragt": "{ort} demandé",
  "{preis} € p. P.": "{preis} € / pers.",
  "{punkt} · {namen} — wieder freigeben": "{punkt} · {namen} — je ne le prends plus",
  "{punkt} übernehmen": "Je prends {punkt}",
  "{tag} · {zeit} vorschlagen": "Proposer {tag} · {zeit}",
  "{termin} · Original": "{termin} · d'origine",
  "{titel} · Original": "{titel} · d'origine",
  "{titel} · von {name}": "{titel} · par {name}",
  "{titel} · von dir": "{titel} · par toi",
  "{titel} ansehen": "Voir {titel}",
  "{titel} bewerten": "Noter {titel}",
  "{zeit} · +{n} Termin": "{zeit} · +{n} date",
  "{zeit} · +{n} Termine": "{zeit} · +{n} dates",
  "{zeit} · Original": "{zeit} · d'origine",
  "{zeit} · Vorschlag von {name}": "{zeit} · proposé par {name}",
  "{zeit} · Vorschlag von dir": "{zeit} · proposé par toi",
  "{zeit} vor Beginn": "{zeit} avant le début",
  "{zeit} vorschlagen": "Proposer {zeit}",
  "© OpenStreetMap-Mitwirkende": "© contributeurs d’OpenStreetMap",
  "+ {n} Alternative": "+ {n} alternative",
  "+ {n} Alternativen": "+ {n} alternatives",
  "+ Meet": "+ Meet",
  "+ Umfrage": "+ Sondage",
  "+ Vorschlag": "+ Proposer",
  "~{n} min Umweg": "~{n} min de détour",
  "~{n} min Umweg für dich": "~{n} min de détour pour toi",
  "1 auf der Liste": "1 sur la liste",
  "1 gemeinsamer Freund · Code {code}": "1 ami en commun · code {code}",
  "1 Monat": "1 mois",
  "1 Woche": "1 semaine",
  "2 Minuten!": "2 minutes !",
  "2 Wochen": "2 semaines",
  "3 Tage": "3 jours",
  "3 Wochen": "3 semaines",
  "4 Tage": "4 jours",
  "5 Tage": "5 jours",
  "ab 3 Personen": "dès 3 personnes",
  "ab 4 Personen": "dès 4 personnes",
  "ab 4 Personen am besten": "idéal dès 4 personnes",
  "ab und zu": "de temps en temps",
  "Abbrechen": "Annuler",
  "Abends meist frei, Anfänger willkommen": "Peu de monde le soir, débutants bienvenus",
  "Abends meist frei, Anfänger willkommen — Schuhe gibt es vor Ort.": "Peu de monde le soir, débutants bienvenus — chaussons dispo sur place.",
  "Abgesagt": "Annulé",
  "Abgesagt [Person]": "Ne vient pas",
  "Abholreihenfolge": "Ordre de passage",
  "Ablehnen": "Refuser",
  "Abmelden": "Se déconnecter",
  "Abstand": "Intervalle",
  "Abstimmen": "Voter",
  "abstimmen lassen": "faire voter",
  "Abwählen": "Retirer",
  "Adler": "Aigle",
  "Adminrolle übergeben": "Passer le rôle d'admin",
  "Adresse erst nach Zustimmung": "Adresse après accord",
  "Adresse freigegeben": "Adresse partagée",
  "Affe": "Singe",
  "aktiv": "active",
  "Aktiv": "En cours",
  "aktiv oder kommend": "en cours ou à venir",
  "Aktivität": "Activité",
  "Aktivität · {n} Vorschlag": "Activité · {n} proposition",
  "Aktivität · {n} Vorschläge": "Activité · {n} propositions",
  "Aktivität abstimmen": "Voter pour l'activité",
  "Aktivität festgelegt": "Activité validée",
  "Aktivität oder Zeit": "Activité ou heure",
  "Aktivität vorschlagen": "Proposer une activité",
  "Aktivität zeigen": "Montrer l'activité",
  "Aktivitätsstatus für Freunde": "Statut d'activité pour tes amis",
  "Aktivitätsvorschläge ansehen": "Voir les propositions d'activité",
  "Aktuellen Entwurf speichern": "Enregistrer le brouillon actuel",
  "Aktueller Standort": "Position actuelle",
  "Aktuelles Passwort": "Mot de passe actuel",
  "Alien": "Alien",
  "alle": "Intervalle",
  "Alle": "Tous",
  "Alle ›": "Tout ›",
  "Alle {n} Anfragen": "Les {n} demandes",
  "Alle {n} Jahre am {tag}.{monat}.": "Tous les {n} ans, le {tag}/{monat}.",
  "Alle {n} Monate am {tag}.": "Tous les {n} mois, le {tag}.",
  "Alle anderen": "Tous les autres",
  "Alle Anfragen ({n})": "Toutes les demandes ({n})",
  "Alle Autos sind voll.": "Toutes les voitures sont pleines.",
  "Alle Beteiligten sehen die Absage.": "Tous les participants verront l'annulation.",
  "Alle deine Freunde sehen {name}.": "Tous tes amis voient {name}.",
  "Alle deine Freunde sind schon in {name}.": "Tous tes amis sont déjà dans {name}.",
  "Alle Freunde": "Tous les amis",
  "Alle Freunde sehen deine Ressourcen — außer private.": "Tous tes amis voient ton matériel — sauf le privé.",
  "Alle Interessen ({n})": "Tous les intérêts ({n})",
  "Alle Kategorien": "Toutes les catégories",
  "Alle Meets": "Tous les Meets",
  "alle Plätze belegt": "toutes les places sont prises",
  "Alle Ressourcen ({n})": "Tout le matériel ({n})",
  "Alle sehen denselben Meet-Chat.": "Tout le monde voit le même chat du Meet.",
  "Alles liegt in Ordnern": "Tout est rangé dans des dossiers",
  "Alles vergessen": "Tout oublier",
  "Alles wird wieder vorgeschlagen": "Tout sera de nouveau proposé",
  "Allgemein": "Général",
  "Als Alternative": "En alternative",
  "Als besondere Person markieren": "Marquer comme personne spéciale",
  "Als besondere Person markiert": "Personne spéciale ajoutée",
  "Als beste Freund:in markieren": "Marquer comme meilleur ami",
  "Als beste Freund:in markiert": "Ajouté aux meilleurs amis",
  "Als bester Freund markiert": "Ajouté aux meilleurs amis",
  "Als Loop starten": "Lancer en Loop",
  "Als Meet vorschlagen": "Proposer comme Meet",
  "als Variante dieses Meets": "comme alternative à ce Meet",
  "Als Vorlage nutzen": "Utiliser comme modèle",
  "Am Wasser": "Au bord de l'eau",
  "Amber": "Ambre",
  "An": "Activé",
  "An · {n} Freund": "Activé · {n} ami",
  "An · {n} Freunde": "Activé · {n} amis",
  "An · Alle Freunde": "Activé · Tous les amis",
  "an {n} Person · Wer hat Lust?": "à {n} personne · Qui a envie ?",
  "an {n} Personen · Wer hat Lust?": "à {n} personnes · Qui a envie ?",
  "Anderes": "Autre",
  "Anderes Foto": "Autre photo",
  "Ändern": "Modifier",
  "Änderungen behalten?": "Garder les modifications ?",
  "Änderungen verwerfen": "Abandonner les modifications",
  "Anfrage abgelehnt": "Demande refusée",
  "Anfrage ablehnen": "Refuser la demande",
  "Anfrage an {name} gesendet": "Demande envoyée à {name}",
  "Anfrage an {name} läuft schon": "Demande à {name} déjà envoyée",
  "Anfrage an {name} senden": "Envoyer la demande à {name}",
  "Anfrage angenommen": "Demande acceptée",
  "Anfrage annehmen": "Accepter la demande",
  "Anfrage gesendet": "Demande envoyée",
  "Anfrage läuft schon": "Demande déjà envoyée",
  "Anfrage senden": "Envoyer la demande",
  "Anfrage von {name} ablehnen?": "Refuser la demande de {name} ?",
  "Anfrage zurückgezogen": "Demande annulée",
  "Anfragen": "Demandes",
  "Angestupst": "Signe envoyé",
  "Angestupst · {zeit}": "Signe envoyé · {zeit}",
  "Anhänger": "Remorque",
  "Anmelden": "Se connecter",
  "Anmeldung": "Connexion",
  "Anmeldung mit Apple und Google kommt mit der App-Version.": "La connexion avec Apple et Google arrive avec la version app.",
  "Annehmen": "Accepter",
  "Anstupsen": "Faire signe",
  "Anstupser": "Petits coups de coude",
  "Anstupser zurücknehmen": "Annuler le signe",
  "Antippen, um Mitteilungen auf dieses Gerät zu erlauben.": "Touche pour autoriser les notifications sur cet appareil.",
  "Antwort {n}": "Réponse {n}",
  "Antwort auf Anstupser": "Répondre à un signe",
  "Antwort entfernen": "Retirer la réponse",
  "Antwort gespeichert": "Réponse enregistrée",
  "Antwort hinzufügen": "Ajouter une réponse",
  "Antwort offen": "Pas encore répondu",
  "Antworten": "Réponses",
  "Anwenden": "Appliquer",
  "App": "App",
  "Apple Karten": "Apple Plans",
  "Apple und Google folgen mit der App.": "Apple et Google arrivent avec l'app.",
  "Arbeit, Schule, Training": "Travail, école, entraînement",
  "Astronaut": "Astronaute",
  "Auf dem iPhone kommen Mitteilungen nur, wenn Crew auf dem Home-Bildschirm liegt. In Safari:": "Sur iPhone, les notifications n'arrivent que si Crew est sur l'écran d'accueil. Dans Safari :",
  "Auf der Karte": "Sur la carte",
  "Auf der Karte gewählt": "Choisie sur la carte",
  "Auf der Liste bei „{titel}“": "Ajouté à la liste de « {titel} »",
  "Auf die Liste": "Sur la liste",
  "Auf diesem Gerät nicht möglich": "Impossible sur cet appareil",
  "Auf einer Wiese oder am Grillplatz — Grill und Kohle mitnehmen.": "Sur une pelouse ou un coin barbecue — prends le grill et le charbon.",
  "Auf Karte wählen": "Choisir sur la carte",
  "Auflösen": "Supprimer",
  "aus": "désactivé",
  "Aus": "Désactivé",
  "aus · Start wäre {datum}": "désactivé · commencerait le {datum}",
  "Aus Verlauf ausblenden": "Masquer de l'historique",
  "Ausdruck": "Expression",
  "Ausgeblendet": "Masqués",
  "Ausgehen": "Sortir",
  "Ausgehen & Events": "Sorties & événements",
  "Ausschnitt verschieben und zoomen": "Déplacer et zoomer le cadrage",
  "Aussteigen": "Quitter",
  "Auswahl aufheben": "Effacer la sélection",
  "Auswählen": "Choisir",
  "Auto": "Voiture",
  "Automatisch": "Automatique",
  "Automatische Anmeldung fehlgeschlagen: {fehler}": "Échec de la connexion automatique : {fehler}",
  "Autos": "Voitures",
  "Baden": "Baignade",
  "Bahn fährt erst ab 8, also zu Fuß hoch": "Pas de téléphérique avant 8 h, donc on monte à pied",
  "Bahn oder zu Fuß, oben Panorama": "Téléphérique ou à pied, panorama au sommet",
  "Bahn oder zu Fuß, oben Panorama über den ganzen See.": "Téléphérique ou à pied, et en haut une vue sur tout le lac.",
  "Ballsport": "Sports de ballon",
  "Bar": "Bar",
  "Bär": "Ours",
  "Basketball": "Basket",
  "Beamer": "Vidéoprojecteur",
  "Beamer oder Fernseher": "Vidéoprojecteur ou télé",
  "Beamer oder Fernseher, Decken — zwei Filme zur Wahl.": "Vidéoprojecteur ou télé, plaids — deux films au choix.",
  "Beamer, Decken, zwei Filme zur Wahl": "Vidéoproj, plaids, deux films au choix",
  "Bearbeiten": "Modifier",
  "Beere": "Baie",
  "Bei {name}": "Chez {name}",
  "Bei {name} einsteigen": "Monter avec {name}",
  "Bei {name} mitfahren": "Monter avec {name}",
  "Bei jemandem daheim": "Chez quelqu'un",
  "Bei mir": "Chez moi",
  "Bei wem?": "Chez qui ?",
  "Beides dauert unter einer Minute.": "Les deux prennent moins d'une minute.",
  "Belästigung": "Harcèlement",
  "Belgien": "Belgique",
  "Benachrichtigungen": "Notifications",
  "Berg": "Montagne",
  "Berge": "Montagnes",
  "Besondere Person": "Personne spéciale",
  "Besondere Person — Goldring zurückgenommen": "Personne spéciale — anneau doré retiré",
  "Besondere Person entfernt": "Personne spéciale retirée",
  "Besonders": "Spécial",
  "Bestätige zuerst die E-Mail, die wir dir geschickt haben": "Confirme d'abord l'e-mail qu'on t'a envoyé",
  "Bestätigung schicken": "Envoyer la confirmation",
  "Beste Freunde": "Meilleurs amis",
  "Beste Freunde · {n} von 3": "Meilleurs amis · {n} sur 3",
  "Bester Freund": "Meilleur ami",
  "Bester Freund — besonderes Zeichen ersetzt": "Meilleur ami — signe perso remplacé",
  "Bester Freund entfernt": "Retiré des meilleurs amis",
  "Bewerten": "Noter",
  "Bewertung ändern": "Modifier la note",
  "Bewertung gelöscht": "Note supprimée",
  "Bewertung gespeichert": "Note enregistrée",
  "Bewertung löschen": "Supprimer l'avis",
  "Bewertung speichern": "Enregistrer l'avis",
  "Bild konnte nicht gelesen werden": "Impossible de lire l'image",
  "Bildnachweis": "Crédit photo",
  "Bin am Kiosk, links vom Eingang": "Je suis au kiosque, à gauche de l'entrée",
  "Bin dabei, ab 9 passt mir": "J'en suis, dès 9 h ça me va",
  "Bin um 19:10 da, komme direkt von der Arbeit": "J'arrive à 19:10, je viens direct du boulot",
  "Bis": "À",
  "bis {betrag} €": "jusqu'à {betrag} €",
  "bis {betrag} € p. P.": "jusqu'à {betrag} € / pers.",
  "bis {km} km": "jusqu'à {km} km",
  "bis {tag} {zeit}": "jusqu'à {tag} {zeit}",
  "bis {zeit}": "jusqu'à {zeit}",
  "Bis du annimmst, sieht die Person <b>nichts</b> von dir — kein Frei, keine Meets, keine Crews. Abgelehnte Anfragen verschwinden lautlos, ohne Hinweis an die andere Seite.": "Tant que tu n'as pas accepté, la personne ne voit <b>rien</b> de toi — ni statut libre, ni Meets, ni Crews. Les demandes refusées disparaissent en silence, sans prévenir l'autre.",
  "bis Mitternacht": "jusqu'à minuit",
  "Bis Mitternacht": "Jusqu'à minuit",
  "bis morgen {zeit}": "jusqu'à demain {zeit}",
  "Bitte ein Interesse eingeben": "Entre un intérêt",
  "Bitte eine E-Mail-Adresse eingeben.": "Entre une adresse e-mail.",
  "Bitte eine gültige E-Mail-Adresse eingeben.": "Entre une adresse e-mail valide.",
  "Bitte einen Namen eingeben": "Entre un nom",
  "Bitte mindestens zwei Interessen wählen": "Choisis au moins deux intérêts",
  "Blendet den Vorschlag aus — Ähnliches kommt seltener": "Masque cette idée — tu verras moins souvent des idées similaires",
  "Blitz": "Éclair",
  "Blockieren": "Bloquer",
  "Blockierte Person": "Personne bloquée",
  "Blockierte Personen": "Personnes bloquées",
  "Blockierung aufheben": "Débloquer",
  "Blume": "Fleur",
  "Blüte": "Fleur",
  "Bohrmaschine": "Perceuse",
  "Bollerwagen": "Chariot",
  "Boot": "Bateau",
  "Bosnien und Herzegowina": "Bosnie-Herzégovine",
  "Boulder-Dienstag": "Mardi grimpe",
  "Boulderhalle K1": "Salle de bloc K1",
  "Bouldern": "Escalade",
  "Bouldern + Pizza": "Escalade + pizza",
  "Boxen": "Enceintes",
  "Brasilien": "Brésil",
  "Brauche Mitfahrt": "Besoin d'une place",
  "Brettspiele": "Jeux de société",
  "Brunch": "Brunch",
  "Brunch bei Kira": "Brunch chez Kira",
  "Buch": "Livre",
  "Budget": "Budget",
  "Camping": "Camping",
  "Campingbus": "Van aménagé",
  "Campingstuhl": "Chaise de camping",
  "Chat": "Chat",
  "Chat öffnen": "Ouvrir le chat",
  "Chillen": "Chiller",
  "Chillen & Spiele": "Chill & jeux",
  "Club": "Boîte de nuit",
  "Code eingeben": "Entre un code",
  "Code einlösen": "Utiliser le code",
  "Code erkannt": "Code reconnu",
  "Code passt nicht": "Code incorrect",
  "Code scannen oder Link teilen": "Scanner un code ou partager un lien",
  "Code ungültig": "Code invalide",
  "Code von Freund:in eingeben": "Entre le code d'un ami",
  "Cola": "Coca",
  "Containerschiff": "Porte-conteneurs",
  "Cowboy": "Cow-boy",
  "Crew": "Crew",
  "Crew bearbeiten": "Modifier la Crew",
  "Crew erstellen": "Créer la Crew",
  "Crew ist mit diesem Konto aktiviert": "Crew est activé avec ce compte",
  "Crew nicht gefunden": "Crew introuvable",
  "Crew oder Freunde": "Crew ou amis",
  "Crews": "Crews",
  "Curry": "Curry",
  "Cyan": "Cyan",
  "Da fehlt noch ein Eintrag": "Il manque encore un élément",
  "Dabei": "Partant",
  "Dafür braucht es zuerst ein Meet": "Il faut d'abord un Meet",
  "Daheim": "Chez soi",
  "Daheim entfernen": "Retirer « Chez soi »",
  "damit nutzt du": "pour utiliser",
  "Dänemark": "Danemark",
  "Danke — die Meldung ist raus": "Merci — le signalement est envoyé",
  "Daraus sortiert Crew deine Vorschläge. Es bleibt in deinem Konto.": "Crew s'en sert pour trier tes idées. Ça reste dans ton compte.",
  "Darstellung": "Apparence",
  "Dart": "Fléchettes",
  "Das aktuelle Passwort stimmt nicht.": "Le mot de passe actuel est incorrect.",
  "Das bist du selbst": "C'est toi-même",
  "Das dürfen nur Fahrer, Mitfahrer oder wer das Meet erstellt hat": "Seuls les conducteurs, les passagers ou la personne qui a créé le Meet peuvent faire ça",
  "Das Einschalten hat nicht geklappt": "Impossible de les activer",
  "Das Einschalten hat nicht geklappt. Bitte noch einmal versuchen.": "L'activation n'a pas marché. Réessaie, s'il te plaît.",
  "Das hat gerade nicht geklappt": "Ça n'a pas marché",
  "Das hat nicht geklappt": "Ça n'a pas marché",
  "Das ist bereits der Originaltermin": "C'est déjà l'horaire d'origine",
  "Das ist dasselbe Passwort wie bisher": "C'est le même mot de passe qu'avant",
  "Das ist dein eigener Code": "C'est ton propre code",
  "Das ist kein Crew-Code": "Ce n'est pas un code Crew",
  "Das ist schon deine Adresse.": "C'est déjà ton adresse.",
  "Das neue Passwort braucht mindestens 8 Zeichen.": "Le nouveau mot de passe doit faire au moins 8 caractères.",
  "Das Original bleibt wählbar. Deine Stimme ist jederzeit änderbar.": "L'original reste possible. Tu peux changer ton vote à tout moment.",
  "Das Passwort braucht mindestens 8 Zeichen": "Le mot de passe doit faire au moins 8 caractères",
  "Das Passwort ist zu kurz": "Mot de passe trop court",
  "Das sieht nicht nach einer E-Mail-Adresse aus": "Cela ne ressemble pas à une adresse e-mail",
  "Dein Desteny-Konto bleibt bestehen. Du kannst dich jederzeit wieder mit {email} anmelden.": "Ton compte Desteny reste actif. Tu peux te reconnecter à tout moment avec {email}.",
  "Dein Desteny-Konto bleibt bestehen. Du kannst dich jederzeit wieder mit deiner E-Mail anmelden.": "Ton compte Desteny reste actif. Tu peux te reconnecter à tout moment avec ton e-mail.",
  "Dein Desteny-Konto gilt für Crew und alle Apps von Desteny Development.": "Ton compte Desteny vaut pour Crew et toutes les apps de Desteny Development.",
  "Dein Desteny-Konto wird gelöscht, auch für andere Apps von Desteny Development. Deine Crews und Meets werden dauerhaft entfernt. Das lässt sich nicht rückgängig machen.": "Ton compte Desteny sera supprimé, y compris pour les autres apps de Desteny Development. Tes Crews et tes Meets seront supprimés pour de bon. Impossible de revenir en arrière.",
  "Dein Name": "Ton nom",
  "Dein Standort": "Ta position",
  "Deine Bewertung": "Ta note",
  "Deine Freunde sehen es neben „frei\".": "Tes amis le voient à côté de « libre ».",
  "Deine Freunde sehen, dass du frei bist": "Tes amis voient que tu es libre",
  "Demo": "Démo",
  "Demo · kein Konto": "Démo · pas de compte",
  "Den Rest können die Fahrer übernehmen.": "Les conducteurs peuvent faire le reste.",
  "Der Code ließ sich nicht einlösen": "Impossible d'utiliser ce code",
  "Der Entwurf verschwindet endgültig.": "Le brouillon sera supprimé pour de bon.",
  "Der Frei-Status wird spätestens um diese Uhrzeit zurückgesetzt — oder früher durch dein eigenes aktives Meet.": "Ton statut libre est réinitialisé au plus tard à cette heure — ou plus tôt si tu as un Meet en cours.",
  "Der Ort selbst": "Le lieu lui-même",
  "Desteny-Apps": "Apps Desteny",
  "Desteny-Konto": "Compte Desteny",
  "Desteny-Konto erstellen": "Créer un compte Desteny",
  "Desteny-Konto löschen": "Supprimer le compte Desteny",
  "Deutschland": "Allemagne",
  "Diamant": "Diamant",
  "Die App konnte nicht starten.": "L'app n'a pas pu démarrer.",
  "Die Crew braucht einen Namen": "La Crew a besoin d'un nom",
  "Die Demo läuft nur auf diesem Gerät.": "La démo tourne uniquement sur cet appareil.",
  "Die Erlaubnis wird gerade eingeholt.": "Demande d'autorisation en cours.",
  "Die Erlaubnis wurde abgelehnt. Zurücknehmen lässt sie sich nur in den Einstellungen des Browsers für diese Seite.": "L'autorisation a été refusée. Tu ne peux la réactiver que dans les réglages du navigateur pour ce site.",
  "Die Frage fehlt noch": "Il manque la question",
  "Die Kamera startet gerade nicht — gib den Code unten ein.": "La caméra ne démarre pas pour l'instant — saisis le code ci-dessous.",
  "Die Karte lädt noch": "La carte charge encore",
  "Die Nachricht wird zur Prüfung übermittelt. {name} erfährt nicht, dass du gemeldet hast.": "Le message est transmis pour vérification. {name} ne saura pas que tu l'as signalé.",
  "Die Passwörter stimmen nicht überein": "Les mots de passe ne correspondent pas",
  "Die Probe ging nicht — sind Mitteilungen erlaubt?": "Le test n'a pas marché — les notifications sont-elles autorisées ?",
  "die Ressource": "le matériel",
  "Die Wiederholung endet, das Meet bleibt.": "La répétition s'arrête, le Meet reste.",
  "Diese E-Mail-Adresse sieht nicht richtig aus": "Cette adresse e-mail n'a pas l'air correcte",
  "Diese Person": "Cette personne",
  "Diese Person fährt gerade nicht": "Cette personne ne conduit pas pour l'instant",
  "Diese Person hat ihren Ort noch nicht geteilt. Die Anfrage geht trotzdem raus.": "Cette personne n'a pas encore partagé son lieu. La demande part quand même.",
  "diese Ressource": "ce matériel",
  "Diese Stelle": "Cet endroit",
  "Diese Woche mal wieder Bouldern?": "On retourne grimper cette semaine ?",
  "Diesen Ort wählen": "Choisir cet endroit",
  "Dieser Browser kennt keine Mitteilungen.": "Ce navigateur ne gère pas les notifications.",
  "Dieser Ordner ist noch leer": "Ce dossier est encore vide",
  "Dieses Foto verwenden": "Utiliser cette photo",
  "Dieses Gerät liefert keinen Standort. „Auf Karte wählen\" geht weiterhin.": "Cet appareil ne fournit pas de position. « Choisir sur la carte » marche toujours.",
  "Dieses Gerät wird benachrichtigt.": "Cet appareil reçoit les notifications.",
  "Dieses Konto komplett zurücksetzen?\n\nAlles wird gelöscht: Profil, Freunde, Gruppen, Meets, Nachrichten. Danach läuft das Einrichten von vorn. Die Anmeldung (E-Mail und Passwort) bleibt.": "Réinitialiser complètement ce compte ?\n\nTout sera effacé : profil, amis, groupes, Meets, messages. Ensuite, la configuration recommence depuis le début. Ta connexion (e-mail et mot de passe) est conservée.",
  "Dieses Meet gibt es nicht mehr.": "Ce Meet n'existe plus.",
  "Dieses Meet wurde abgesagt.": "Ce meet a été annulé.",
  "Direkte Erwähnungen": "Mentions directes",
  "Draußen": "Plein air",
  "Drohne": "Drone",
  "Drucker": "Imprimante",
  "Du": "Toi",
  "du · {name}": "toi · {name}",
  "Du bist dabei": "Tu en es",
  "Du bist das letzte Mitglied von {name}. Die Gruppe und ihr Chat verschwinden; vergangene eigene Meets bleiben in deinem Verlauf.": "Tu es le dernier membre de {name}. Le groupe et son chat disparaissent ; tes anciens Meets restent dans ton historique.",
  "Du bist die einzige Person, die {name} verwaltet. Wähle, wer das übernimmt — danach verlässt du die Gruppe.": "Tu es la seule personne à gérer {name}. Choisis qui prend le relais — ensuite tu quittes le groupe.",
  "Du bist eingeladen": "Tu as une invitation",
  "Du bist jetzt frei": "Tu es libre maintenant",
  "Du bist kein Mitglied": "Tu n'es pas membre",
  "Du bist raus": "Tu passes ton tour",
  "Du bringst’s": "Tu t'en charges",
  "Du fährst": "Tu conduis",
  "Du fährst mit {name}": "Tu pars avec {name}",
  "Du hast {name} angestupst": "Tu as fait signe à {name}",
  "Du hast abgesagt": "Tu ne viens pas",
  "Du hast abgesagt — hier siehst du nur, wer fährt.": "Tu ne viens pas — tu vois seulement qui conduit.",
  "Du hast angestupst": "Tu as fait signe",
  "Du hast dich frei gemeldet": "Tu as signalé que tu es libre",
  "Du hast ein Meet gestartet": "Tu as lancé un Meet",
  "Du hast etwas bearbeitet, aber noch nicht gespeichert.": "Tu as modifié quelque chose sans enregistrer.",
  "Du hast zurückgestupst": "Tu as fait signe en retour",
  "Du holst {namen} ab": "Tu passes prendre {namen}",
  "Du kommst selbst hin.": "Tu viens par tes propres moyens.",
  "Du siehst danach weder den Chat noch neue Meets dieser Gruppe. Vergangene eigene Meets bleiben in deinem Verlauf.": "Tu ne verras plus le chat ni les nouveaux Meets de ce groupe. Tes anciens Meets restent dans ton historique.",
  "Du stehst bei „sucht noch“": "Tu es dans « cherche encore »",
  "Du suchst eine Mitfahrt.": "Tu cherches une place.",
  "Dunkel": "Sombre",
  "E-Mail": "E-mail",
  "E-Mail ändern": "Changer d'e-mail",
  "E-Mail ausfüllen": "Entre ton e-mail",
  "E-Mail oder Passwort stimmt nicht": "E-mail ou mot de passe incorrect",
  "E-Mail und Passwort": "E-mail et mot de passe",
  "E-Mail und Passwort ausfüllen": "Entre ton e-mail et ton mot de passe",
  "eben hinzugefügt": "ajouté à l'instant",
  "eben hinzugefügt · {kosten}": "ajouté à l'instant · {kosten}",
  "Egal": "Peu importe",
  "Eher nicht": "Plutôt pas",
  "Eigene": "Perso",
  "Eigene Idee": "Mon idée",
  "Eigene Mitteilung, getrennt von den übrigen": "Une notification à part, séparée des autres",
  "Eigenes Emoji": "Ton emoji",
  "Eigenes Emoji: das rechte Feld antippen und aus der Tastatur wählen. Ein Emoji ersetzt das Symbol — der farbige Ring bleibt.": "Ton emoji : touche le champ de droite et choisis-le sur le clavier. Un emoji remplace l'icône — l'anneau de couleur reste.",
  "Eigenes Interesse": "Intérêt perso",
  "Eigenes Interesse hinzufügen": "Ajouter ton propre intérêt",
  "Ein eigenes Foto statt Farbe und Motiv. Danach rückst du es im Kreis zurecht.": "Ta propre photo au lieu d'une couleur et d'un motif. Ensuite, tu la cadres dans le cercle.",
  "Ein Freund hat dich zu Crew geholt.": "Un ami t'a fait venir sur Crew.",
  "Ein Platz mehr": "Une place de plus",
  "Ein Platz weniger": "Une place de moins",
  "Ein Tipp genügt — so wissen alle, wer wen abholt.": "Un geste suffit — tout le monde sait qui passe prendre qui.",
  "Eine Ebene, keine Unterordner. Neue Ordner erscheinen sofort als Filter und im Speichern-Sheet.": "Un seul niveau, pas de sous-dossiers. Les nouveaux dossiers apparaissent tout de suite comme filtres et dans l'écran d'enregistrement.",
  "Einen Moment …": "Un instant…",
  "Einen Moment noch — kurz warten und noch einmal versuchen": "Encore un instant — patiente un peu et réessaie",
  "Eingeladen": "Invités",
  "Einladen": "Inviter",
  "Einladung": "Invitation",
  "Einladungen & Meet-Änderungen": "Invitations & changements de Meet",
  "einmalig an {n} Mitglied von {name}": "une seule fois à {n} membre de {name}",
  "einmalig an {n} Mitglieder von {name}": "une seule fois à {n} membres de {name}",
  "einmalig an {n} Teilnehmende": "une seule fois à {n} participants",
  "einmalig an {n} teilnehmende Person": "une seule fois à {n} participant",
  "einmalig an {name}": "une seule fois à {name}",
  "einmalig an diesen Raum": "une seule fois dans ce salon",
  "Einmalige Freigabe. Crew sendet danach keine weitere Position und ortet dich nicht im Hintergrund.": "Partage unique. Crew n'envoie pas d'autre position ensuite et ne te localise pas en arrière-plan.",
  "Einschalten": "Activer",
  "Einsteigen": "Monter",
  "Einstellungen": "Réglages",
  "Einstellungen speichern": "Enregistrer les réglages",
  "Eis": "Glace",
  "Element hinzufügen": "Ajouter un élément",
  "Emoji": "Emoji",
  "Endet am nächsten Tag": "Se termine le lendemain",
  "Endgültig löschen": "Supprimer définitivement",
  "Engel": "Ange",
  "Entdecken": "Découvrir",
  "Entdecken oder eigene Idee": "Découvrir ou proposer ton idée",
  "Entfernen": "Retirer",
  "Entfernung": "Distance",
  "Entwurf löschen": "Supprimer le brouillon",
  "Entwurf löschen?": "Supprimer le brouillon ?",
  "Entwurf speichern": "Enregistrer le brouillon",
  "Erde": "Terre",
  "Ereignis eintragen": "Ajouter l'événement",
  "Erhalten · {n}": "Reçues · {n}",
  "Erinnerung aus": "Rappel désactivé",
  "Erlauben lässt es sich in den iPhone-Einstellungen: Mitteilungen → Crew.": "Tu peux les autoriser dans les Réglages de l'iPhone : Notifications → Crew.",
  "Erst auf den Home-Bildschirm": "D'abord sur l'écran d'accueil",
  "Erst die Gruppe übergeben": "D'abord confier le groupe",
  "Erst eine Aktivität wählen": "Choisis d'abord une activité",
  "Erst eine Idee wählen": "Choisis d'abord une idée",
  "Erst eine Idee wählen — oder „Spontanes Treffen\"": "Choisis d'abord une idée — ou « Meet spontané »",
  "Erst eine Person wählen": "Choisis d'abord une personne",
  "Erst einen Namen eingeben": "Entre d'abord un nom",
  "Erst einen Ort wählen": "Choisis d'abord un lieu",
  "Erst einen Punkt eintragen": "Ajoute d'abord un élément",
  "Erst einen Titel eingeben": "Entre d'abord un titre",
  "Erst jemanden absetzen": "Retire d'abord quelqu'un",
  "Erst mindestens eine Person oder Crew wählen": "Choisis d'abord au moins une personne ou une Crew",
  "Erstmal umsehen": "D'abord jeter un œil",
  "Essen": "Manger",
  "Essen & Trinken": "Manger & boire",
  "Essen gehen": "Resto",
  "Etwas anderes": "Autre chose",
  "Etwas hinzufügen": "Ajouter un truc",
  "Euer Kino-Klassiker": "Votre classique ciné",
  "Eule": "Hibou",
  "Europa": "Europe",
  "Event": "Événement",
  "EVENT": "ÉVÉNEMENT",
  "Fahrrad": "Vélo",
  "Fahrzeuge": "Véhicules",
  "Farbe": "Couleur",
  "Farbe wählen": "Choisir la couleur",
  "Farbe, Motiv oder Foto — änderbar im Profil.": "Couleur, icône ou photo — modifiable dans ton profil.",
  "Farbverlauf": "Dégradé",
  "Feiern": "Faire la fête",
  "Fernglas": "Jumelles",
  "Fertig": "Terminé",
  "Feste Zeiten eintragen": "Ajouter des horaires fixes",
  "Festivals": "Festivals",
  "Festlegen": "Valider",
  "Festspiele Seebühne": "Festival sur la Seebühne",
  "Feuer": "Feu",
  "Feuerwerk am See": "Feu d'artifice sur le lac",
  "Film": "Film",
  "Filmabend": "Soirée film",
  "Filme & Serien": "Films & séries",
  "Filter": "Filtres",
  "Finnland": "Finlande",
  "Fitness": "Fitness",
  "Fixe Uhrzeit": "Heure fixe",
  "Flaggen": "Drapeaux",
  "Flieder": "Lilas",
  "Flugzeug": "Avion",
  "Flugzeuge": "Avions",
  "folgt dem Gerät": "suit l'appareil",
  "Foto": "Photo",
  "Foto entfernen": "Retirer la photo",
  "Foto wählen": "Choisir une photo",
  "Foto wird vorbereitet …": "Préparation de la photo …",
  "Foto-Nachweis ausblenden": "Masquer le crédit photo",
  "Foto-Nachweis zeigen": "Afficher le crédit photo",
  "Foto: {urheber}": "Photo : {urheber}",
  "Fotografieren": "Photo",
  "Frage": "Question",
  "Frage und zwei Optionen ausfüllen": "Remplis la question et deux options",
  "fragt jetzt nach Freigabe": "demande l'autorisation",
  "Frankreich": "France",
  "Frech": "Espiègle",
  "Frei": "Libre",
  "Frei — aktiv": "Libre — activé",
  "frei · {lust}": "libre · {lust}",
  "Frei · {status}": "Dispo · {status}",
  "Frei ab": "Libre dès",
  "frei ab {zeit}": "libre dès {zeit}",
  "Frei ab {zeit}": "Libre dès {zeit}",
  "Frei setzen": "Passer en libre",
  "Frei zurücksetzen um": "Fin du statut libre à",
  "Frei zurücksetzen um {zeit}": "Fin du statut libre à {zeit}",
  "Frei-Hinweis": "Alerte « libre »",
  "Frei-Hinweis von {name} an": "On te prévient quand {name} est libre",
  "Frei-Hinweis von {name} aus": "Plus d'alerte quand {name} est libre",
  "Frei-Hinweise · Individuell": "Alertes « libre » · Personnalisé",
  "Frei-Hinweise von Freunden": "Alertes quand tes amis sont libres",
  "Frei-Status speichern": "Enregistrer le statut libre",
  "freie Umfrage im Chat": "sondage libre dans le chat",
  "Freigabe": "Partage",
  "Freigabe wird abgefragt …": "Demande d'autorisation…",
  "Freigeben": "Débloquer",
  "Freitag": "Vendredi",
  "Freitag wieder was machen?": "On refait un truc vendredi ?",
  "Freitag-Crew": "Crew du vendredi",
  "freiwillig": "facultatif",
  "Freund hinzufügen": "Ajouter un ami",
  "Freunde": "Amis",
  "Freunde · {n}": "Amis · {n}",
  "Freunde hinzufügen": "Ajouter des amis",
  "Freunde sehen nur „Keine Zeit“.": "Tes amis voient seulement « Pas dispo ».",
  "Freunde suchen": "Chercher des amis",
  "Freundesanfragen": "Demandes d'ami",
  "Freundschaft beenden": "Retirer des amis",
  "Freundschaft beendet": "Retiré de tes amis",
  "Freundschaft mit {name} beenden?": "Retirer {name} de tes amis ?",
  "Freundschaftsanfragen": "Demandes d'amis",
  "Frisbee": "Frisbee",
  "Fröhlich": "Joyeux",
  "Frosch": "Grenouille",
  "Früh buchen": "À réserver tôt",
  "Früh buchen, nur bei gutem Wetter": "À réserver tôt, seulement par beau temps",
  "Fuchs": "Renard",
  "Füge mich in Crew hinzu: {code}": "Ajoute-moi sur Crew : {code}",
  "Für {antwort} stimmen": "Voter pour {antwort}",
  "Für {titel} · Original bleibt wählbar": "Pour {titel} · l'original reste au choix",
  "Für dein Desteny-Konto.": "Pour ton compte Desteny.",
  "Für dich": "Pour toi",
  "Für dieses Meet gibt es keinen Raum": "Pas de salon pour ce Meet",
  "Fußball": "Foot",
  "Gaming": "Gaming",
  "Gehört zu": "Lié à",
  "Geht immer": "Toujours bien",
  "Geist": "Fantôme",
  "Geländewagen": "Tout-terrain",
  "Gelb": "Jaune",
  "Gemeinsam erlebt": "Vécu ensemble",
  "Gemeinsam kochen": "Cuisiner ensemble",
  "Gemeinsame Crews": "Crews en commun",
  "Gemeinsame Interessen": "Intérêts en commun",
  "Gemeinsame Ressourcen": "Matériel en commun",
  "gemeinsamer Raum": "salon commun",
  "Gemeldet · {name} blockiert": "Signalé · tu as bloqué {name}",
  "Gemeldet · Person blockiert": "Signalé · personne bloquée",
  "Gemütlich daheim": "Cosy à la maison",
  "genauer": "préciser",
  "gerade eben": "à l'instant",
  "Gerade frei": "Dispo maintenant",
  "Gerade frei · {n}": "Dispo maintenant · {n}",
  "Gerade gilt dein Foto. Wählst du hier etwas, ersetzt es das Foto.": "Ta photo est utilisée. Si tu choisis quelque chose ici, elle sera remplacée.",
  "Gerade nicht möglich": "Pas possible pour l'instant",
  "gesendet": "envoyée",
  "Gespeichert": "Enregistrés",
  "Gespeichertes suchen …": "Chercher un modèle…",
  "Gestern, {datum}": "Hier, {datum}",
  "Getränke": "Boissons",
  "Gib die E-Mail deines Desteny-Kontos ein. Wir schicken dir einen Link für ein neues Passwort.": "Entre l'e-mail de ton compte Desteny. On t'envoie un lien pour un nouveau mot de passe.",
  "Gib zuerst dein aktuelles Passwort ein.": "Entre d'abord ton mot de passe actuel.",
  "Gilt für alle besten Freunde · nur für dich sichtbar": "Pour tous tes meilleurs amis · visible par toi seul",
  "Gitarre": "Guitare",
  "Gold": "Or",
  "Graphit": "Graphite",
  "Griechenland": "Grèce",
  "Grill": "Barbecue",
  "Grill und Kohle mitnehmen": "Grill et charbon à prévoir",
  "Grillen": "Barbecue",
  "Grillen am See": "Barbecue au bord du lac",
  "Grillen im Grünen": "Barbecue au vert",
  "Grimmig": "Féroce",
  "Grinsen": "Sourire",
  "grob nach Luftlinie": "approximatif, à vol d'oiseau",
  "grobe Umgebung · {ort}": "zone approximative · {ort}",
  "Großbritannien": "Royaume-Uni",
  "Große Küche": "Grande cuisine",
  "Grün": "Vert",
  "Grund fehlt": "Choisis une raison",
  "Grund melden (freiwillig)": "Indiquer une raison (facultatif)",
  "Gruppe ändern": "Modifier le groupe",
  "Gruppe anlegen": "Créer le groupe",
  "Gruppe auflösen": "Supprimer le groupe",
  "Gruppe auflösen?": "Supprimer le groupe ?",
  "Gruppe bearbeiten": "Modifier le groupe",
  "Gruppe gespeichert": "Groupe enregistré",
  "Gruppe nicht gefunden": "Groupe introuvable",
  "Gruppe öffnen": "Ouvrir le groupe",
  "Gruppe öffnen?": "Ouvrir le groupe ?",
  "Gruppe verlassen": "Quitter le groupe",
  "Gruppenbild": "Photo du groupe",
  "Gruppenbild ändern": "Changer l’image du groupe",
  "Gruppenbild groß ansehen": "Voir l’image du groupe en grand",
  "Gruppenbild von {name}": "Image du groupe {name}",
  "Gruppenbild wählen": "Choisir une image de groupe",
  "Gruppenoptionen": "Options du groupe",
  "Gut": "Bien",
  "Gym": "Muscu",
  "Habt ihr schon gewählt": "Déjà choisi par vous",
  "Hängematte": "Hamac",
  "Hase": "Lapin",
  "Hat nicht geklappt": "Ça n'a pas marché",
  "Hat nicht stattgefunden": "N'a pas eu lieu",
  "Hauptnavigation": "Navigation principale",
  "Hauptvorschlag": "Choix principal",
  "Heißluftballon": "Montgolfière",
  "Helikopter": "Hélico",
  "Hell": "Clair",
  "Herz": "Cœur",
  "Heute": "Aujourd'hui",
  "Heute und morgen": "Aujourd'hui et demain",
  "heute, {zeit}": "aujourd'hui, {zeit}",
  "Himmelblau": "Bleu ciel",
  "Hintergrund": "Fond",
  "Hinweis ausblenden": "Masquer l'info",
  "Hinweis schließen": "Fermer l'info",
  "Hinzufügen": "Ajouter",
  "Höhe über der Karte": "Altitude au-dessus de la carte",
  "Hubschrauber": "Hélicoptère",
  "Hund": "Chien",
  "Ich bin frei": "Je suis libre",
  "Ich brauche eine Mitfahrt": "J'ai besoin d'une place",
  "Ich bring Cola, Chips und Kohle mit": "J'apporte coca, chips et charbon",
  "Ich bring Snacks für oben mit": "J'apporte des snacks pour là-haut",
  "Ich fahre": "Je conduis",
  "Ich komme selbst": "Je viens par mes propres moyens",
  "Ich nehm die Frisbee mit": "Je prends le frisbee",
  "Ich nehm die Seile mit": "Je prends les cordes",
  "Ich übernehm die Snacks @Mira du die Seile?": "Je m'occupe des snacks, @Mira toi les cordes ?",
  "Ich war nicht dabei": "Je n'y étais pas",
  "Ich wäre für Kochen bei mir": "Moi je dirais qu'on cuisine chez moi",
  "Idee": "Idée",
  "IDEE": "IDÉE",
  "Idee anlegen": "Créer l'idée",
  "Idee entfernen": "Retirer l'idée",
  "Idee speichern": "Enregistrer l'idée",
  "Igel": "Hérisson",
  "Ihr habt: {ding}": "Vous avez : {ding}",
  "Ihr seht danach nichts mehr voneinander — kein Frei, keine Meets, keine Crews. Eure gemeinsamen vergangenen Meets und deine eigenen Bewertungen bleiben erhalten.": "Vous ne verrez plus rien l'un de l'autre — ni statut libre, ni Meets, ni Crews. Vos anciens Meets en commun et tes propres avis sont conservés.",
  "Ihr seht danach nichts mehr voneinander. {name} verschwindet aus deinen Listen, aus euren Gruppen und aus allen Räumen — auch bereits geschriebene Nachrichten. {name} erfährt davon nichts.": "Vous ne verrez plus rien l'un de l'autre. {name} disparaît de tes listes, de vos groupes et de tous les salons — messages déjà envoyés compris. {name} n'en saura rien.",
  "Ihr seht danach weder eure freie Zeit noch eure Profile. Gemeinsame Meets und deine eigenen Bewertungen bleiben in deinem Verlauf.": "Vous ne verrez plus ni vos moments libres ni vos profils. Les Meets en commun et tes propres avis restent dans ton historique.",
  "Ihr seid schon befreundet": "Vous êtes déjà amis",
  "Im Demo-Modus gibt es kein Konto.": "Pas de compte en mode démo.",
  "Im Demo-Modus gibt es keine Mitteilungen — es gibt niemanden, der etwas schicken könnte.": "Pas de notifications en mode démo — personne ne pourrait t'écrire.",
  "Im Demo-Modus öffnen": "Ouvrir en mode démo",
  "Im Meet · {titel}": "En Meet · {titel}",
  "Im Meet vermerkt": "Ajouté au Meet",
  "Immer": "Toujours",
  "immer dabei": "toujours inclus",
  "Immer verfügbar": "Toujours dispo",
  "in {min} Min.": "dans {min} min",
  "In {ordner} gespeichert": "Enregistré dans {ordner}",
  "In {ort}": "À {ort}",
  "in {std} Std": "dans {std} h",
  "in {std} Std {min} Min": "dans {std} h {min} min",
  "Indigo": "Indigo",
  "Individuell": "Personnalisé",
  "Individuell · {n}": "Personnalisé · {n}",
  "Individuell · niemand": "Personnalisé · personne",
  "Info zur Lage": "Infos sur place",
  "Initialen": "Initiales",
  "Interesse": "Intérêt",
  "Interesse bearbeiten": "Modifier l'intérêt",
  "Interesse entfernen": "Retirer l'intérêt",
  "Interesse entfernt": "Intérêt retiré",
  "Interesse gibt es schon": "Cet intérêt existe déjà",
  "Interesse hinzufügen": "Ajouter un intérêt",
  "Interesse hinzugefügt": "Intérêt ajouté",
  "Interessen": "Centres d'intérêt",
  "Irland": "Irlande",
  "Italien": "Italie",
  "Ja, bei mir": "Oui, chez moi",
  "Ja. @Jonny bringst du die Kohle mit?": "Oui. @Jonny tu prends le charbon ?",
  "Jahr": "Année",
  "Jahr [Einheit]": "an",
  "Jahr {jahr}": "Année {jahr}",
  "Jahr wählen": "Choisir l'année",
  "Jahre [Einheit]": "ans",
  "Japan": "Japon",
  "Jause": "Casse-croûte",
  "Jazz am See": "Jazz au bord du lac",
  "Jede Woche. Freunde sehen nur „Keine Zeit“.": "Chaque semaine. Tes amis voient seulement « Pas dispo ».",
  "Jeden {n}. {tag}": "Un {tag} sur {n}",
  "Jeden {n}. {wochentag}": "Un {wochentag} sur {n}",
  "Jeden {tag}": "Chaque {tag}",
  "Jeden {wochentag}": "Chaque {wochentag}",
  "Jeden dritten {tag}": "Un {tag} sur trois",
  "Jeden dritten {wochentag}": "Un {wochentag} sur trois",
  "Jeden fünften {tag}": "Un {tag} sur cinq",
  "Jeden fünften {wochentag}": "Un {wochentag} sur cinq",
  "Jeden Monat am {tag}.": "Chaque mois le {tag}.",
  "Jeden sechsten {tag}": "Un {tag} sur six",
  "Jeden sechsten {wochentag}": "Un {wochentag} sur six",
  "Jeden Tag": "Tous les jours",
  "Jeden vierten {tag}": "Un {tag} sur quatre",
  "Jeden vierten {wochentag}": "Un {wochentag} sur quatre",
  "Jeden zweiten {tag}": "Un {tag} sur deux",
  "Jeden zweiten {wochentag}": "Un {wochentag} sur deux",
  "Jedes Jahr am {tag}.{monat}.": "Chaque année le {tag}/{monat}.",
  "Jemand": "Quelqu'un",
  "Jet": "Jet",
  "jetzt": "maintenant",
  "Jetzt": "Maintenant",
  "Jetzt bewerten": "Noter maintenant",
  "Jetzt frei?": "Libre maintenant ?",
  "Jetzt vorschlagen": "Proposer maintenant",
  "Jetzt: {an}{email}{aus}": "Actuelle : {an}{email}{aus}",
  "Jupiter": "Jupiter",
  "Kaffee": "Café",
  "Kaktus": "Cactus",
  "Kamera": "Appareil photo",
  "Kamera nicht freigegeben — gib den Code unten ein.": "Caméra non autorisée — saisis le code ci-dessous.",
  "Kanada": "Canada",
  "Kann mich jemand mitnehmen? Ich bräuchte eine Mitfahrgelegenheit": "Quelqu'un peut m'emmener ? J'aurais besoin d'un covoit",
  "Kanu": "Canoë",
  "Karamell": "Caramel",
  "Karaoke": "Karaoké",
  "Karte": "Carte",
  "Karte bewegen — der Pin bleibt in der Mitte": "Déplace la carte — l'épingle reste au centre",
  "Karte nicht verfügbar": "Carte indisponible",
  "Karten": "Cartes",
  "Karten und Snacks — ab 3 Personen.": "Cartes et snacks — dès 3 personnes.",
  "Karten und Snacks, ab 3 Personen": "Cartes et snacks, dès 3 personnes",
  "Kartenabend": "Soirée cartes",
  "Kartendaten": "Données cartographiques",
  "Kartenspiele": "Jeux de cartes",
  "Kategorie": "Catégorie",
  "Katze": "Chat",
  "Kein Muster": "Sans motif",
  "Kein Ordner": "Aucun dossier",
  "Kein Ort gefunden": "Aucun lieu trouvé",
  "Kein Ort gefunden. Tipp: Name des Lokals, der Halle oder der Straße.": "Aucun lieu trouvé. Astuce : nom du bar, de la salle ou de la rue.",
  "Kein passendes Symbol gefunden — {an}such dir selbst eines aus{aus}.": "Aucune icône trouvée — {an}choisis-en une toi-même{aus}.",
  "Kein Platz mehr frei": "Plus de place",
  "Kein Platz mehr für {namen}": "Plus de place pour {namen}",
  "kein Umweg": "pas de détour",
  "kein Umweg für dich": "pas de détour pour toi",
  "Keine aktuellen Meets": "Aucun Meet en ce moment",
  "Keine Angabe": "Sans préférence",
  "Keine Freunde auf der Karte": "Aucun ami sur la carte",
  "Keine gesendeten Anfragen": "Aucune demande envoyée",
  "Keine Kamera gefunden — gib den Code unten ein.": "Aucune caméra trouvée — saisis le code ci-dessous.",
  "Keine Meets in diesem Zeitraum": "Aucun Meet sur cette période",
  "Keine offenen Anfragen": "Aucune demande en attente",
  "Keine Variante gewählt": "Aucune option choisie",
  "Keine Verbindung zum Server. Deine Anmeldung ist noch da – öffne Crew gleich noch einmal.": "Pas de connexion au serveur. Tu es toujours connecté·e – rouvre Crew dans un instant.",
  "Keine Verbindung. Netz prüfen und noch einmal versuchen.": "Pas de connexion. Vérifie ton réseau et réessaie.",
  "Keine vergangenen Meets": "Aucun Meet passé",
  "Keine Vorschläge — Filter oder Suche anpassen": "Aucune idée — ajuste les filtres ou la recherche",
  "Keine Zeit": "Pas dispo",
  "Keine Zeit bearbeiten": "Modifier les moments pas dispo",
  "Keine Zeit bis {tag} {zeit}": "Pas dispo jusqu'à {tag} {zeit}",
  "Keine Zeit bis {zeit}": "Pas dispo jusqu'à {zeit}",
  "Keine Zeit bis Mitternacht": "Pas dispo jusqu'à minuit",
  "Keine Zeit bis morgen {zeit}": "Pas dispo jusqu'à demain {zeit}",
  "Keine Zeit eintragen": "Ajouter des moments pas dispo",
  "Keine Zeit ist seit {zeit} vorbei": "Ton créneau occupé s'est terminé à {zeit}",
  "Kino": "Ciné",
  "Kino & Filme": "Ciné & films",
  "Kino Donnerstag um 20:15 — kommst du mit?": "Ciné jeudi à 20:15 — tu viens ?",
  "Kino unter freiem Himmel direkt am See": "Ciné en plein air, au bord du lac",
  "Kino unter freiem Himmel direkt am See — Decken mitbringen.": "Ciné en plein air au bord du lac — prends un plaid.",
  "Kino: Dune Part 3": "Ciné : Dune Part 3",
  "Klavier": "Piano",
  "Kleeblatt": "Trèfle",
  "Kletterhalle K1": "Salle d'escalade K1",
  "Klettern & Berge": "Escalade & montagne",
  "Klettern Rheintal": "Escalade dans le Rheintal",
  "Kletterseil": "Corde d'escalade",
  "Koala": "Koala",
  "Kochabend": "Soirée cuisine",
  "Kochen": "Cuisine",
  "Kochen draußen": "Cuisine en plein air",
  "Koffer": "Valise",
  "Kohle": "Charbon",
  "Kohle nicht vergessen": "N'oublie pas le charbon",
  "Kohle und Snacks bring ich mit": "Le charbon et les snacks, je m'en occupe",
  "Komet": "Comète",
  "Komme selbst": "Par mes moyens",
  "Kommen selbst: {namen}": "Par leurs moyens : {namen}",
  "Kommend": "À venir",
  "Konfetti": "Confettis",
  "Königsblau": "Bleu roi",
  "Konsole": "Console",
  "Konto": "Compte",
  "Konto löschen": "Supprimer le compte",
  "Konzert Kammgarn": "Concert au Kammgarn",
  "Konzerte": "Concerts",
  "Kopfhörer": "Casque",
  "Kopieren": "Copier",
  "Kopieren ging nicht": "Copie impossible",
  "Kopiert": "Copié",
  "Koralle": "Corail",
  "Kosten": "Coût",
  "Kosten {an}optional{aus}": "Coût {an}facultatif{aus}",
  "kostenlos": "gratuit",
  "Kreuzfahrtschiff": "Paquebot",
  "Kroatien": "Croatie",
  "Krone": "Couronne",
  "Kühlbox": "Glacière",
  "Kultur & Events": "Culture & sorties",
  "Kürbis": "Citrouille",
  "Kurz warten, dann erneut vorschlagen": "Attends un peu avant de reproposer",
  "Kurzcode": "Par code",
  "Kurzcode · gerade eben": "Par code · à l'instant",
  "kurze Runde": "petit plouf",
  "Kurze Runde im See — danach gemeinsam Kaffee.": "Un petit plouf dans le lac — puis un café ensemble.",
  "Kurze Runde im See, danach Kaffee": "Un petit plouf dans le lac, puis un café",
  "Kurzer Ton und Vibration, wenn etwas ankommt, während Crew offen ist": "Un son court et une vibration quand quelque chose arrive pendant que Crew est ouvert",
  "Kurzfilmnacht": "Nuit du court-métrage",
  "Label": "Étiquette",
  "Label · frei tippbar": "Étiquette · texte libre",
  "Lächelnd": "Souriant",
  "Lädt dich ein · Kino Do": "T'invite · ciné jeudi",
  "lädt ein": "organise",
  "Lage nicht freigegeben": "Position non partagée",
  "Laptop": "Ordi portable",
  "Laufen": "Course à pied",
  "Laufrunde am See": "Footing au bord du lac",
  "läuft": "en cours",
  "läuft gerade": "en cours",
  "Lautsprecher": "Enceinte",
  "Lavendel": "Lavande",
  "Leinwand": "Écran de projection",
  "Leiter": "Échelle",
  "Lernen": "Apprendre",
  "Lesen": "Lecture",
  "Lesestand merken": "Marquer comme lu",
  "Lieber nicht": "Plutôt pas",
  "Limette": "Citron vert",
  "Link geteilt · gestern": "Lien partagé · hier",
  "Link schicken": "Envoyer le lien",
  "Liste": "Liste",
  "Liste · {n}": "Liste · {n}",
  "Liste übernommen · {wer}": "Sur la liste · {wer}",
  "Listenpunkt erstellen": "Ajouter un élément",
  "Lizenz: {lizenz}": "Licence : {lizenz}",
  "Loop": "Loop",
  "Loop · {n}. Mal": "Loop · {n}e fois",
  "Loop · {n}. Mal [erstes]": "Loop · {n}re fois",
  "Loop aktivieren": "Activer le Loop",
  "Loop aktiviert": "Loop activé",
  "Loop bearbeiten": "Modifier le Loop",
  "Loop erstellen": "Créer un Loop",
  "Loop geändert": "Loop modifié",
  "Loop gestoppt": "Loop arrêté",
  "Loop speichern": "Enregistrer le Loop",
  "Loop stoppen": "Arrêter le Loop",
  "Loop stoppen?": "Arrêter le Loop ?",
  "Loop-Antwort speichern": "Enregistrer la réponse au Loop",
  "Loops": "Loops",
  "Los geht’s": "C'est parti",
  "Löschen": "Supprimer",
  "Löschen hat nicht geklappt": "Suppression impossible",
  "Löwe": "Lion",
  "Lust auf draußen": "Envie de prendre l'air",
  "Lust auf Essen": "Envie de manger",
  "Lust auf Kaffee": "Envie d'un café",
  "Lust auf Sport": "Envie de sport",
  "Lust zu chillen": "Envie de se poser",
  "Lust?": "Envie ?",
  "Magst du": "Tu aimes",
  "Manchmal": "Parfois",
  "Manchmal verfügbar": "Parfois dispo",
  "Markieren": "Marquer",
  "Markierte Freunde": "Amis marqués",
  "Markierung entfernen": "Retirer le marquage",
  "Markierung entfernt": "Marquage retiré",
  "Mars": "Mars",
  "Maus": "Souris",
  "Maximal drei beste Freunde": "Trois meilleurs amis max",
  "Meet": "Meet",
  "Meet abgesagt": "Meet annulé",
  "Meet absagen": "Annuler le Meet",
  "Meet absagen?": "Annuler le Meet ?",
  "Meet anlegen": "Créer un Meet",
  "Meet bei dir?": "Le Meet chez toi ?",
  "Meet festlegen": "Valider le Meet",
  "Meet nicht gefunden": "Meet introuvable",
  "Meet öffnen": "Ouvrir le Meet",
  "Meet senden": "Envoyer le Meet",
  "Meet veröffentlichen": "Publier le Meet",
  "Meet-Erinnerung": "Rappel de Meet",
  "Mein Auto ist startklar, ich kann fahren": "Ma voiture est prête, je peux conduire",
  "Meine Einladung": "Mon invitation",
  "Meine Meets": "Mes Meets",
  "Meinen Teil übernehmen": "Appliquer ma part",
  "Melden": "Signaler",
  "Melden und {name} blockieren": "Signaler et bloquer {name}",
  "Menü": "Menu",
  "Mikrofon": "Micro",
  "Mindestens 8 Zeichen.": "8 caractères minimum.",
  "Mindestens 8 Zeichen. Deinen Namen fragen wir gleich danach.": "8 caractères minimum. On te demande ton nom juste après.",
  "Mindestens eine Person": "Au moins une personne",
  "Minute": "Minute",
  "mit {namen}": "avec {namen}",
  "mit {namen} +{n}": "avec {namen} +{n}",
  "Mit deinem Desteny-Konto anmelden": "Se connecter avec ton compte Desteny",
  "Mit deinem Standort — nur für Vorschläge": "Avec ta position — uniquement pour les idées",
  "Mit Desteny-Konto anmelden": "Se connecter avec un compte Desteny",
  "Mit diesem Desteny-Konto meldest du dich bei allen Apps von Desteny Development an.": "Avec ce compte Desteny, tu te connectes à toutes les apps de Desteny Development.",
  "mit dir": "avec toi",
  "mit E-Mail und Passwort": "avec e-mail et mot de passe",
  "Mit wem": "Avec qui",
  "Mitbringen": "À apporter",
  "Mitbringen ändern": "Modifier la liste à apporter",
  "Mitbringen anlegen": "Ajouter à la liste à apporter",
  "Mitbringen löschen": "Retirer l'élément",
  "Mitfahren": "Covoiturage",
  "Mitfahrt ins Meet übernehmen": "Ajouter le covoit au Meet",
  "Mitfahrt speichern": "Enregistrer le trajet",
  "Mitfahrt zuordnen": "Attribuer le trajet",
  "Mitglieder": "Membres",
  "Mitnehmen": "Prendre",
  "Mitte von {n} Standort": "Centre de {n} position",
  "Mitte von {n} Standorten": "Centre de {n} positions",
  "Mitteilungen": "Notifications",
  "Mitteilungen auf diesem Gerät": "Notifications sur cet appareil",
  "Mitteilungen aufs Handy": "Notifications sur ton téléphone",
  "Mitteilungen aufs iPhone": "Notifications sur ton iPhone",
  "Mitteilungen einschalten": "Activer les notifications",
  "Mitteilungen sind an": "Les notifications sont activées",
  "Mitteilungen sind vom System blockiert": "Les notifications sont bloquées par le système",
  "Mittel": "Moyen",
  "Möchten dich adden": "Veulent t'ajouter",
  "Mohn": "Coquelicot",
  "Moment …": "Un instant…",
  "Monat": "Mois",
  "Monat [Einheit]": "mois",
  "Monate [Einheit]": "mois",
  "Mond": "Lune",
  "Monitor": "Moniteur",
  "Morgen": "Demain",
  "morgen, {zeit}": "demain, {zeit}",
  "Motiv": "Icône",
  "Motorboot": "Bateau à moteur",
  "Motorrad": "Moto",
  "Müde": "Fatigué",
  "Museum": "Musée",
  "Musik": "Musique",
  "Muster": "Motif",
  "nach dem Namen gewählt: {name}": "choisie d'après le nom : {name}",
  "Nach rechts": "Vers la droite",
  "Nach unten": "Vers le bas",
  "Nachricht …": "Message…",
  "Nachricht gelöscht": "Message supprimé",
  "Nachricht löschen": "Supprimer le message",
  "Nachricht melden": "Signaler le message",
  "Nachricht senden": "Envoyer le message",
  "Nächste Woche": "Semaine suivante",
  "Nächster Monat": "Mois suivant",
  "Nacht": "Nuit",
  "Nah & draußen": "Tout près, en plein air",
  "Name": "Nom",
  "Name der Ressource": "Nom du matériel",
  "Nerd": "Intello",
  "Neu für euch": "Nouveau pour vous",
  "Neu laden": "Recharger",
  "Neu: mindestens 8 Zeichen.": "Nouveau : 8 caractères minimum.",
  "Neue Crew": "Nouvelle Crew",
  "Neue E-Mail-Adresse": "Nouvelle adresse e-mail",
  "Neue Idee": "Nouvelle idée",
  "Neue Mitglieder fügen {namen} hinzu.": "Ce sont {namen} qui ajoutent les nouveaux membres.",
  "Neue Mitglieder fügt {namen} hinzu.": "C’est {namen} qui ajoute les nouveaux membres.",
  "Neue Ressource": "Nouveau matériel",
  "Neue Umfrage": "Nouveau sondage",
  "Neuer Listenpunkt": "Nouvel élément de liste",
  "Neuer Ordner": "Nouveau dossier",
  "Neues Interesse": "Nouvel intérêt",
  "Neues Meet": "Nouveau Meet",
  "Neues Passwort": "Nouveau mot de passe",
  "Neues Passwort setzen": "Choisir un nouveau mot de passe",
  "Neutral": "Neutre",
  "Nicht dabei": "Pas partant",
  "Nicht für mich": "Pas pour moi",
  "Nicht gut": "Pas top",
  "Nicht mehr übernehmen": "Je ne m'en charge plus",
  "Nicht öffnen": "Ne pas ouvrir",
  "Nichts": "Rien",
  "Nichts gefunden": "Rien trouvé",
  "nichts geplant": "rien de prévu",
  "Nichts geplant": "Rien de prévu",
  "Nichts geplant.": "Rien de prévu.",
  "Niederlande": "Pays-Bas",
  "niemand": "personne",
  "Niemand": "Personne",
  "Niemand blockiert": "Personne n'est bloqué",
  "Niemand gefunden für „{suche}“": "Personne trouvé pour « {suche} »",
  "noch {n} wählen": "encore {n} à choisir",
  "Noch etwas": "Encore un truc",
  "Noch fährt niemand.": "Personne ne conduit encore.",
  "Noch kein Desteny-Konto? Erstellen": "Pas encore de compte Desteny ? En créer un",
  "Noch kein Verlauf.": "Pas encore d'historique.",
  "Noch keine besten Freunde — das Zeichen gilt, sobald du jemanden markierst.": "Pas encore de meilleurs amis — le signe s'applique dès que tu marques quelqu'un.",
  "Noch keine Crew": "Pas encore de Crew",
  "Noch keine Freunde": "Pas encore d'amis",
  "Noch keine Umfrage — hier stimmt ihr gemeinsam ab.": "Pas encore de sondage — c'est ici que vous votez ensemble.",
  "Noch keine Vorlagen gespeichert": "Aucun modèle enregistré pour l'instant",
  "Noch nichts": "Rien pour l'instant",
  "Noch nichts auf der Liste — hier steht, wer was mitbringt.": "Rien sur la liste pour l'instant — ici, on voit qui apporte quoi.",
  "Noch nichts drauf — schreib den ersten Punkt.": "Rien pour l'instant — ajoute le premier truc.",
  "Noch nichts gemeinsam erlebt": "Rien vécu ensemble pour l'instant",
  "Noch nichts geplant": "Rien de prévu pour l'instant",
  "Noch nichts zusammen erlebt": "Rien vécu ensemble pour l'instant",
  "Noch ohne Angabe: {namen}": "Pas encore indiqué : {namen}",
  "Nochmal": "Réessayer",
  "Norwegen": "Norvège",
  "Notiz": "Note",
  "Notiz (optional)": "Note (facultatif)",
  "Notiz hinzufügen": "Ajouter une note",
  "Nur {wer} sieht {name}.": "{name} n'est visible que par {wer}.",
  "Nur Admins können Personen hinzufügen": "Seuls les admins peuvent ajouter des personnes",
  "Nur aktiv": "Actif seulement",
  "Nur das Meet ansehen": "Voir seulement le Meet",
  "Nur der Organisator kann absagen": "Seul l'organisateur peut annuler",
  "Nur der Organisator kann festlegen": "Seul l'organisateur peut décider",
  "Nur die Aktivität übernommen": "Seule l'activité est reprise",
  "Nur die grobe Umgebung — die genaue Adresse erst nach Zustimmung.": "Seulement la zone approximative — l'adresse exacte après accord.",
  "nur dieses Feld offen": "seul ce point reste ouvert",
  "Nur du siehst {name}.": "{name} n'est visible que par toi.",
  "Nur eigene Vorschläge": "Uniquement tes propositions",
  "Nur Freunde lassen sich hinzufügen": "Tu ne peux ajouter que des amis",
  "Nur für dich": "Rien que pour toi",
  "Nur für dich — niemand sonst sieht deine Antwort.": "Rien que pour toi — personne d'autre ne voit ta réponse.",
  "Nur für dich sichtbar": "Visible uniquement par toi",
  "Nur ich": "Juste moi",
  "nur kostenlos": "gratuit seulement",
  "Nur leere Entwürfe": "Uniquement les brouillons vides",
  "Nur mit Konto": "Avec un compte uniquement",
  "Nur vom Home-Bildschirm aus": "Seulement depuis l'écran d'accueil",
  "Nuss": "Noisette",
  "Ocker": "Ocre",
  "offen": "à fixer",
  "Offen": "En attente",
  "Öffnen": "Ouvrir",
  "oft": "souvent",
  "Oft gemacht": "Vous y allez souvent",
  "Ohne Eingabe steht neben dem Namen nur der Name.": "Sans texte, seul le prénom s'affiche.",
  "Ohne feste Aktivität": "Sans activité précise",
  "ohne Limit": "sans limite",
  "Ohne Meet": "Sans Meet",
  "ohne Meet, aktiv oder kommend": "sans Meet, en cours ou à venir",
  "Ohne Netz lässt sich kein Ort wählen": "Sans réseau, impossible de choisir un lieu",
  "ohne Standort": "sans position",
  "ohne Standort — selbst absprechen": "sans position — à voir entre vous",
  "ohne Standortfreigabe": "sans partager ta position",
  "Ohne Standortfreigabe geht es nicht automatisch — „Auf Karte wählen\" bleibt offen. Deine allgemeine Standort-Einstellung bleibt unverändert.": "Sans autorisation, pas de position automatique — « Choisir sur la carte » reste possible. Ton réglage de position général ne change pas.",
  "Okay": "OK",
  "Oktopus": "Pieuvre",
  "Oldtimer": "Voiture ancienne",
  "Open-Air Kino": "Ciné plein air",
  "Oper unter freiem Himmel — früh buchen, nur bei gutem Wetter.": "Opéra en plein air — à réserver tôt, seulement par beau temps.",
  "Option {n}": "Option {n}",
  "Option 1": "Option 1",
  "Option 2": "Option 2",
  "Optionen": "Options",
  "Orange": "Orange",
  "Ordner": "Dossier",
  "Ordner anlegen": "Créer un dossier",
  "Ordner erstellen": "Créer le dossier",
  "Original": "d'origine",
  "Original bleibt wählbar": "L'original reste au choix",
  "Ort": "Lieu",
  "ORT": "LIEU",
  "Ort — Zustimmung steht aus": "Lieu — en attente d'accord",
  "Ort abgelehnt": "Lieu refusé",
  "Ort anfragen": "Demander le lieu",
  "Ort angefragt bei {name} — Zustimmung steht noch aus.": "Lieu demandé à {name} — en attente d'accord.",
  "Ort angefragt bei der Person — Zustimmung steht noch aus.": "Lieu demandé à la personne — en attente d'accord.",
  "Ort bei {name} angefragt — die Adresse erscheint erst nach der Zustimmung.": "Lieu demandé à {name} — l'adresse n'apparaît qu'après son accord.",
  "Ort bei der gefragten Person angefragt — die Adresse erscheint erst nach der Zustimmung.": "Lieu demandé à la personne — l'adresse n'apparaît qu'après son accord.",
  "Ort bei dir angefragt — die Adresse erscheint erst nach der Zustimmung.": "On te demande ton lieu — l'adresse n'apparaît qu'après ton accord.",
  "Ort blieb offen": "Lieu jamais fixé",
  "Ort entfernen": "Retirer le lieu",
  "Ort freigegeben": "Lieu accepté",
  "Ort hinzufügen": "Ajouter un lieu",
  "Ort offen": "Lieu à fixer",
  "Ort suchen": "Chercher un lieu",
  "Ort suchen …": "Chercher un lieu…",
  "Ort übernehmen": "Choisir ce lieu",
  "Ort übernommen": "Lieu repris",
  "Ort und Personen übernommen": "Lieu et personnes repris",
  "Ort und Zeit übernommen": "Lieu et heure repris",
  "Ort, Zeit und Personen übernommen": "Lieu, heure et personnes repris",
  "Orte in deiner Nähe zeigen": "Afficher les lieux près de toi",
  "Ortsanfrage beantworten": "Répondre à la demande de lieu",
  "Österreich": "Autriche",
  "Panda": "Panda",
  "Panorama oben": "Panorama au sommet",
  "Park, weicher Rasen, ab 4 Personen": "Parc, pelouse moelleuse, dès 4 personnes",
  "Party": "Fête",
  "Passt": "Parfait",
  "Passt zu euch": "Pour vous",
  "Passt zu: {interesse}": "Pour vous : {interesse}",
  "Passwort": "Mot de passe",
  "Passwort ändern": "Changer le mot de passe",
  "Passwort anzeigen": "Afficher le mot de passe",
  "Passwort festlegen": "Choisir un mot de passe",
  "Passwort geändert.": "Mot de passe modifié.",
  "Passwort verbergen": "Masquer le mot de passe",
  "Passwort vergessen?": "Mot de passe oublié ?",
  "Passwort wiederholen": "Répéter le mot de passe",
  "Pasta": "Pâtes",
  "Pasta danach": "Pâtes après",
  "Pasta für alle — wer die größte Küche hat, lädt ein.": "Des pâtes pour tout le monde — celui qui a la plus grande cuisine reçoit.",
  "Pasta für alle, zusammen in einer Küche": "Des pâtes pour tout le monde, ensemble en cuisine",
  "Pavillon": "Tonnelle",
  "PC": "PC",
  "Perfekt, bis 21 Uhr geblieben": "Parfait, on est restés jusqu'à 21 h",
  "Person blockieren": "Bloquer la personne",
  "Person blockiert": "Personne bloquée",
  "Person ist kein Mitglied": "Cette personne n'est pas membre",
  "Person ist nicht mehr blockiert": "Personne débloquée",
  "Personen · {n}": "Personnes · {n}",
  "Personen hinzufügen": "Ajouter des personnes",
  "Personen übernommen": "Personnes reprises",
  "Personen-Kapazität": "Nombre de personnes",
  "Petrol": "Bleu canard",
  "Pfänder": "Pfänder",
  "Pfänder-Runde": "Balade au Pfänder",
  "Picknick": "Pique-nique",
  "Picknickkorb": "Panier pique-nique",
  "Pilz": "Champignon",
  "Pinguin": "Pingouin",
  "Pink": "Rose",
  "Pizza": "Pizza",
  "Pizza am Hafen": "Pizza au port",
  "Pizza bei Mira": "Pizza chez Mira",
  "Planen": "Organiser",
  "Plattenspieler": "Platine vinyle",
  "Plätze für Mitfahrer": "Places passagers",
  "Polen": "Pologne",
  "Pool": "Piscine",
  "Portugal": "Portugal",
  "Privat": "Privé",
  "Privat: {namen}": "Privé : {namen}",
  "Private Ressource": "Matériel privé",
  "Private Ressourcen sehen": "Voir le matériel privé",
  "Privatsphäre & Freigaben": "Confidentialité & partage",
  "Probe-Mitteilung senden": "Envoyer une notification test",
  "Profil": "Profil",
  "Profil ›": "Profil ›",
  "Profil bearbeiten": "Modifier le profil",
  "Profil gespeichert": "Profil enregistré",
  "Profil speichern": "Enregistrer le profil",
  "Profilbild": "Photo de profil",
  "Profilbild ändern": "Changer la photo de profil",
  "Profilbild gestalten": "Créer ta photo de profil",
  "Profilbild übernommen": "Photo de profil mise à jour",
  "Profilbild von {name}": "Photo de profil de {name}",
  "Profilbild von {name} groß ansehen": "Voir la photo de profil de {name} en grand",
  "Propellerflugzeug": "Avion à hélice",
  "PS5": "PS5",
  "Punkte": "Pois",
  "QR-Code scannen": "Scanner le QR code",
  "Quelle öffnen": "Voir la source",
  "Raclette": "Raclette",
  "Radfahren": "Vélo",
  "Radtouren": "Balades à vélo",
  "Rakete": "Fusée",
  "Rallyeauto": "Voiture de rallye",
  "Rasenmäher": "Tondeuse",
  "Raum": "Salle",
  "Raum {raum} nicht auflösbar": "Salon {raum} introuvable",
  "Raumschiff": "Vaisseau spatial",
  "regelmäßig": "régulièrement",
  "Regen angesagt": "Pluie annoncée",
  "Regenbogen": "Arc-en-ciel",
  "Rennwagen": "Voiture de course",
  "Ressource entfernen": "Retirer le matériel",
  "Ressource entfernt": "Matériel retiré",
  "Ressource gibt es schon": "Ce matériel existe déjà",
  "Ressource hinzufügen": "Ajouter du matériel",
  "Ressource hinzugefügt": "Matériel ajouté",
  "Ressourcen": "Matériel",
  "Ressourcen speichern": "Enregistrer le matériel",
  "Richtung": "Direction",
  "Ringe": "Cercles",
  "Roboter": "Robot",
  "Rosé": "Vieux rose",
  "Rot": "Rouge",
  "Route": "Itinéraire",
  "Route mit Abholungen": "Itinéraire avec les arrêts",
  "Route mit Abholungen in {karte} öffnen": "Ouvrir l'itinéraire avec les arrêts dans {karte}",
  "Route öffnen": "Ouvrir l'itinéraire",
  "Rückgängig": "Annuler",
  "Rucksack": "Sac à dos",
  "Ruhe & Kreatives": "Calme & créatif",
  "Salbei": "Sauge",
  "Samstag": "Samedi",
  "Satellit": "Satellite",
  "Saturn": "Saturne",
  "Scannen geht hier nicht — gib den Code unten ein.": "Impossible de scanner ici — saisis le code ci-dessous.",
  "Schaf": "Mouton",
  "Schalte den Standort oben ein, um zu wählen, wer ihn sieht.": "Active la position en haut pour choisir qui la voit.",
  "Schau in dein Postfach. Der Link ist eine Stunde gültig.": "Regarde ta boîte mail. Le lien est valable une heure.",
  "Schiffe": "Bateaux",
  "Schlafsack": "Sac de couchage",
  "Schließen": "Fermer",
  "Schlitten": "Luge",
  "Schnee": "Neige",
  "Schnell startklar": "Vite lancé",
  "Schnelle Runde im Park — Ball und Netz mitbringen.": "Petite partie au parc — prends la balle et le filet.",
  "Schon ein Desteny-Konto? Anmelden": "Déjà un compte Desteny ? Connecte-toi",
  "Schon gespeichert · {n}": "Déjà enregistrées · {n}",
  "Schräg nach links unten": "En diagonale, vers le bas à gauche",
  "Schräg nach rechts unten": "En diagonale, vers le bas à droite",
  "Schubkarre": "Brouette",
  "Schweden": "Suède",
  "Schwein": "Cochon",
  "Schweiz": "Suisse",
  "Schwester": "Sœur",
  "Schwimmen": "Natation",
  "Schwimmen im See": "Baignade dans le lac",
  "See": "Lac",
  "See & Chill": "Lac & chill",
  "See, Wiese und Pizza direkt daneben": "Lac, pelouse et pizza juste à côté",
  "Seebühne": "Seebühne",
  "Seebühne: Carmen": "Seebühne : Carmen",
  "Segelboot": "Voilier",
  "Sehen, wer Zeit hat. Und daraus etwas machen.": "Voir qui est libre. Et en faire quelque chose.",
  "seit {zeit}": "depuis {zeit}",
  "Senden": "Envoyer",
  "Serbien": "Serbie",
  "Serien": "Séries",
  "Servus! Am Wochenende was am Damm machen?": "Salut ! On fait un truc à la digue ce week-end ?",
  "Shopping": "Shopping",
  "Sie gilt, sobald du den Link in der Mail angeklickt hast.": "Elle sera active dès que tu auras cliqué sur le lien dans l'e-mail.",
  "Sieht gleich aus wie das Zeichen deiner besonderen Person.": "Identique au signe de ta personne spéciale.",
  "Ski": "Ski",
  "Slackline": "Slackline",
  "Smaragd": "Émeraude",
  "Snowboard": "Snowboard",
  "So kommen Mitteilungen von Crew an.": "Voici comment arrivent les notifications de Crew.",
  "So sehen dich deine Freunde. Änderbar im Profil.": "C'est comme ça que tes amis te voient. Modifiable dans ton profil.",
  "So sieht dich deine Crew": "Voilà comment ta Crew te voit",
  "So sieht eure Gruppe aus": "Voilà à quoi ressemble votre groupe",
  "Social": "Réseaux",
  "Social öffnen": "Ouvrir les réseaux",
  "Sofa": "Canapé",
  "Sommer": "Été",
  "Sonne": "Soleil",
  "Sonnenaufgang Pfänder": "Lever de soleil au Pfänder",
  "Sonnenbrille": "Lunettes de soleil",
  "Sonnenschirm": "Parasol",
  "Spam": "Spam",
  "Spanien": "Espagne",
  "Später": "Plus tard",
  "Später — direkt zu Crew": "Plus tard — aller direct dans Crew",
  "Spätestens {zeit}": "Au plus tard à {zeit}",
  "Spazieren": "Balade",
  "Speichern": "Enregistrer",
  "Speichern und weiter": "Enregistrer et continuer",
  "Spiele": "Jeux",
  "Spieleabend": "Soirée jeux",
  "Spieleabend bei Noah": "Soirée jeux chez Noah",
  "Spielesammlung": "Collection de jeux",
  "Spikeball": "Spikeball",
  "Spikeball im Park": "Spikeball au parc",
  "Spikeball-Turnier": "Tournoi de Spikeball",
  "Spontan treffen": "Se voir maintenant",
  "Spontanes Treffen": "Meet spontané",
  "Sport": "Sport",
  "Sport & draußen": "Sport & plein air",
  "Sport-Runde": "Team sport",
  "Sportwagen": "Voiture de sport",
  "Sprache": "Langue",
  "Standard": "Par défaut",
  "Standard 00:00": "Par défaut 00:00",
  "Standard: aus": "Par défaut : désactivé",
  "Stände am Dorfplatz und Livemusik": "Stands sur la place du village et musique live",
  "Stände am Dorfplatz und Livemusik — Eintritt frei, Gläser gegen Pfand.": "Stands sur la place du village et musique live — entrée libre, verres consignés.",
  "Standort": "Position",
  "Standort ansehen: {ort}": "Voir la position : {ort}",
  "Standort für Vorschläge": "Position pour les suggestions",
  "Standort gerade nicht verfügbar": "Position indisponible pour le moment",
  "Standort nicht erlaubt — du kannst ihn in den Einstellungen deines Geräts freigeben.": "Position non autorisée — tu peux l’activer dans les réglages de ton appareil.",
  "Standort nicht mehr teilen": "Arrêter de partager la position",
  "Standort senden?": "Envoyer ta position ?",
  "Standort teilen": "Partager ma position",
  "Standort teilen mit": "Partager ma position avec",
  "Standort verwenden": "Utiliser la position",
  "Standort wird abgefragt …": "Recherche de ta position …",
  "Stativ": "Trépied",
  "Statt „{titel}\" — oder als Alternative dazu?": "À la place de « {titel} » — ou en alternative ?",
  "Statt „{titel}\" und {n} weitere — oder als Alternative dazu?": "À la place de « {titel} » (+{n}) — ou en alternative ?",
  "Stattdessen blockieren und melden": "Plutôt bloquer et signaler",
  "Steht nichts Passendes dabei?": "Rien ne te correspond ?",
  "Stern": "Étoile",
  "Sterne": "Étoiles",
  "Stimme setzen": "Voter",
  "Stimme zurücknehmen": "Retirer ton vote",
  "Strandbad": "Strandbad",
  "Strandbad + Pizza": "Strandbad + pizza",
  "Strandbad Bregenz": "Strandbad Bregenz",
  "Streifen": "Rayures",
  "Stunde": "Heure",
  "Suche läuft …": "Recherche…",
  "Suche leeren": "Effacer la recherche",
  "Suche oben — oder tippe auf die Karte.": "Cherche en haut — ou touche la carte.",
  "Suchen …": "Rechercher…",
  "Supabase-Bibliothek nicht ladbar": "Impossible de charger la bibliothèque Supabase",
  "Surfbrett": "Planche de surf",
  "Symbol": "Icône",
  "Symbol ändern": "Changer l'icône",
  "Symbol für {name}": "Icône pour {name}",
  "Symbol oder Emoji": "Icône ou emoji",
  "Symbol wählen": "Choisir l'icône",
  "System": "Système",
  "Tablet": "Tablette",
  "Tage": "Jours",
  "Tanne": "Sapin",
  "Taube": "Bleu gris",
  "Technik": "Tech",
  "Teilen": "Partager",
  "Teilnahme absagen": "Annuler ma participation",
  "Teilnahme speichern": "Enregistrer la participation",
  "Teilnehmende": "Participants",
  "Teilnehmende aktualisiert": "Participants mis à jour",
  "Teilnehmende ändern": "Modifier les participants",
  "Teilnehmende bearbeiten": "Modifier les participants",
  "Temporäre Räume": "Salons temporaires",
  "Termine · {n}": "Dates · {n}",
  "Text: {quelle}": "Texte : {quelle}",
  "Thermoskanne": "Thermos",
  "Tickets": "Billets",
  "Tickets & Infos": "Billets & infos",
  "Tiere": "Animaux",
  "Tiger": "Tigre",
  "Tischtennis": "Ping-pong",
  "Titel": "Titre",
  "Töne": "Sons",
  "Top — ich fahr, 3 Plätze frei": "Top — je conduis, 3 places libres",
  "Tränen lachen": "Mort de rire",
  "Treffen planen": "Prévoir une sortie",
  "Treffpunkt bleibt Fluh, oder?": "RDV toujours à Fluh, non ?",
  "Trinken": "Apéro",
  "Trinken gehen": "Boire un verre",
  "Tschechien": "Tchéquie",
  "Türkei": "Turquie",
  "Türkis": "Turquoise",
  "U-Boot": "Sous-marin",
  "über {name}": "via {name}",
  "über Link": "via lien",
  "Übernehmen": "Valider",
  "Übernehmen können Fahrer, Mitfahrer oder wer das Meet erstellt hat.": "Les conducteurs, les passagers ou la personne qui a créé le Meet peuvent l'appliquer.",
  "übernommen": "pris en charge",
  "UFO": "OVNI",
  "Uhr": "Horloge",
  "Ukraine": "Ukraine",
  "Umfrage": "Sondage",
  "Umfrage anlegen": "Créer un sondage",
  "Umfrage bei „{titel}“": "Sondage ajouté à « {titel} »",
  "Umfrage erstellen": "Créer un sondage",
  "Umfrage im Raum": "Sondage publié dans le salon",
  "Umfrage im Raum anlegen": "Créer un sondage dans le salon",
  "Umfragen": "Sondages",
  "Umfragen · {n}": "Sondages · {n}",
  "Umkreis": "Rayon",
  "Umkreis · bis {km} km · {n} Ort": "Rayon · jusqu'à {km} km · {n} lieu",
  "Umkreis · bis {km} km · {n} Orte": "Rayon · jusqu'à {km} km · {n} lieux",
  "Umkreis entfernen": "Retirer le rayon",
  "Unangemessene Inhalte": "Contenu inapproprié",
  "Unbekannt": "Inconnu",
  "Unbekannte Meet-Teilnehmende sehen": "Ce que voient les participants inconnus",
  "Ungarn": "Hongrie",
  "Ungefähr, nur auf diesem Gerät gespeichert.": "Approximative, enregistrée uniquement sur cet appareil.",
  "Unterwegs": "Dehors",
  "Updates & Zusammenfassungen": "Actus & résumés",
  "USA": "États-Unis",
  "Verbunden": "Connecté",
  "verfügbar · für · wer": "dispo · pour · qui",
  "Verfügbarkeit": "Disponibilité",
  "Vergessen": "Oublier",
  "Vergrößern": "Zoomer",
  "Verkehrsflugzeug": "Avion de ligne",
  "Verkleinern": "Dézoomer",
  "Verlassen": "Quitter",
  "Verlauf": "Historique",
  "Verliebt": "Amoureux",
  "Verschoben": "Reporté",
  "Verwalten": "Gérer",
  "Violett": "Violet",
  "Vogel": "Oiseau",
  "voll": "complet",
  "Voll": "Complet",
  "Volleyball": "Volley",
  "Vollständiges Profil": "Profil complet",
  "Vom System blockiert": "Bloquées par le système",
  "Von": "De",
  "Von der Mitte aus": "Depuis le centre",
  "Von dir gesendet": "Envoyées par toi",
  "Von mir gesendet · {n}": "Envoyées · {n}",
  "Von und Bis sind gleich": "Le début et la fin sont identiques",
  "vor {n} min": "il y a {n} min",
  "vor {n} Minute": "il y a {n} minute",
  "vor {n} Minuten": "il y a {n} minutes",
  "vor {n} Stunde": "il y a {n} heure",
  "vor {n} Stunden": "il y a {n} heures",
  "Vorheriger Monat": "Mois précédent",
  "Vorige Woche": "Semaine précédente",
  "Voriger Monat": "Mois précédent",
  "Vorlage gespeichert": "Modèle enregistré",
  "Vorname": "Prénom",
  "Vorschlag": "Proposition",
  "Vorschlag ändern": "Modifier la proposition",
  "Vorschlag anlegen": "Ajouter une proposition",
  "Vorschlag ausblenden": "Masquer la suggestion",
  "Vorschlag bearbeiten": "Modifier la proposition",
  "Vorschlag entfernen": "Retirer la proposition",
  "Vorschlag für „{titel}\": {idee}": "Proposition pour « {titel} » : {idee}",
  "Vorschlag für {titel}": "Proposition pour {titel}",
  "Vorschlag gesendet": "Proposition envoyée",
  "Vorschlag gespeichert": "Proposition enregistrée",
  "Vorschlag senden": "Envoyer la proposition",
  "Vorschlag übernehmen": "Appliquer la suggestion",
  "Vorschlag übernommen": "Suggestion appliquée",
  "Vorschlag: {idee}": "Proposition : {idee}",
  "Vorschlag: {name} holt dich ab": "Suggestion : {name} passe te prendre",
  "Vorschlagen": "Proposer",
  "VR-Brille": "Casque VR",
  "Wähl mindestens einen Tag": "Choisis au moins un jour",
  "Wähl zuerst, wie es war": "Choisis d'abord comment c'était",
  "Wähle oben, bei wem ihr euch trefft.": "Choisis en haut chez qui vous vous retrouvez.",
  "Wählen": "Choisir",
  "Wal": "Baleine",
  "Wald": "Forêt",
  "Wandern": "Rando",
  "Wandern am Pfänder": "Rando au Pfänder",
  "Wandern Pfänder": "Rando Pfänder",
  "Wann": "Quand",
  "Wann passt es?": "Quand ça vous va ?",
  "Wartet": "En attente",
  "Wartet auf Bestätigung: {email}": "En attente de confirmation : {email}",
  "Warum meldest du?": "Pourquoi tu signales ?",
  "Was Crew gelernt hat": "Ce que Crew a appris",
  "Was die Vorlage mitnimmt": "Ce que le modèle garde",
  "Was es gekostet hat": "Ce que ça a coûté",
  "Was habt ihr vor?": "Vous prévoyez quoi ?",
  "Was ihr gemacht habt": "Ce que vous avez fait",
  "Was kochen wir?": "On cuisine quoi ?",
  "Was machen wir?": "On fait quoi ?",
  "Was machen?": "On fait quoi ?",
  "Was machst du gern?": "Tu aimes faire quoi ?",
  "Was soll jemand mitbringen?": "Qu'est-ce qu'il faut apporter ?",
  "Was war los?": "Que s'est-il passé ?",
  "Was?": "Quoi ?",
  "Waschbär": "Raton laveur",
  "Wasser & Schnee": "Eau & neige",
  "Wasser hat 24 Grad 🌊": "L'eau est à 24 degrés 🌊",
  "Wasserflugzeug": "Hydravion",
  "Website": "Site web",
  "Wechseln": "Changer",
  "Weinfest": "Fête du vin",
  "Weinfest Lochau": "Fête du vin de Lochau",
  "Weiter": "Continuer",
  "Weiter bearbeiten": "Continuer à modifier",
  "weiter zu": "continuer vers",
  "Weitere": "Autres",
  "Weitere Freunde": "Plus d'amis",
  "Weitere Interessen": "Plus d'intérêts",
  "Welle": "Vague",
  "Wellen": "Vagues",
  "Weltall": "Espace",
  "Weniger anzeigen": "Voir moins",
  "Wenn dich jemand anstupst": "Quand quelqu'un te fait signe",
  "wer bringt was mit": "qui apporte quoi",
  "Wer fährt?": "Qui conduit ?",
  "Wer hätte Samstag Bock auf den Pfänder?": "Qui est chaud pour le Pfänder samedi ?",
  "Wer ist frei? Was machen wir?": "Qui est libre ? On fait quoi ?",
  "Wer schreibt, wer frei ist": "Qui écrit, qui est libre",
  "Werkzeug": "Outils",
  "Werkzeug & Garten": "Outils & jardin",
  "Wetter soll top werden, viel Sonne": "La météo a l'air top, grand soleil",
  "Wie das Gerät": "Comme l'appareil",
  "Wie heißt du?": "Tu t'appelles comment ?",
  "Wie heißt ihr?": "Vous vous appelez comment ?",
  "Wie kommst du hin?": "Comment tu viens ?",
  "wie oft gemeinsam": "fréquence ensemble",
  "Wie oft gerade?": "À quelle fréquence ?",
  "Wie schaut’s Donnerstag aus?": "Jeudi, t'es dispo ?",
  "Wie war {titel}?": "C'était comment, {titel} ?",
  "Wie war der See gestern?": "C'était comment le lac hier ?",
  "Wie war's?": "C'était comment ?",
  "Wie war’s?": "C'était comment ?",
  "Wieder möglich in {zeit}": "Réessaie dans {zeit}",
  "Wieder zeigen": "Réafficher",
  "Wiederholung": "Répétition",
  "Wiese am See mit Sprungturm und Kiosk — Eintritt frei.": "Pelouse au bord du lac avec plongeoir et kiosque — entrée gratuite.",
  "Wiese oder Grillplatz, Grill und Kohle mitnehmen": "Pelouse ou coin barbecue, grill et charbon à prévoir",
  "Wikingerschiff": "Drakkar",
  "Wir haben an {email} eine Bestätigung geschickt. Die Adresse gilt, sobald du den Link angeklickt hast.": "On a envoyé une confirmation à {email}. L'adresse sera active dès que tu auras cliqué sur le lien.",
  "Wir haben dir eine E-Mail geschickt. Bestätige sie und melde dich dann an.": "On t'a envoyé un e-mail. Confirme-le, puis connecte-toi.",
  "Wir haben dir einen Link an {email} geschickt.": "On t'a envoyé un lien à {email}.",
  "wird gebraucht": "à choisir",
  "Wird mit eingeladen": "Sera invité aussi",
  "Wird nachgeschlagen …": "Recherche en cours…",
  "Woche": "Semaine",
  "Woche [Einheit]": "semaine",
  "Wochen [Einheit]": "semaines",
  "Wochenende": "Week-end",
  "Wolf": "Loup",
  "Womit fängst du an?": "Tu commences par quoi ?",
  "Woran lag’s genau?": "Qu'est-ce qui a joué ?",
  "Worauf hast du Lust?": "Tu as envie de quoi ?",
  "Worüber soll abgestimmt werden?": "On vote sur quoi ?",
  "Yoga": "Yoga",
  "z. B. Anhänger": "ex. remorque",
  "z. B. Freundin": "ex. copine",
  "z. B. Padel": "ex. padel",
  "Zeichen": "Signe",
  "Zeichen für beste Freunde": "Signe des meilleurs amis",
  "Zeichen für beste Freunde gespeichert": "Signe des meilleurs amis enregistré",
  "Zeile entfernen": "Retirer la ligne",
  "Zeit": "Heure",
  "Zeit · {n} Vorschlag": "Heure · {n} proposition",
  "Zeit · {n} Vorschläge": "Heure · {n} propositions",
  "Zeit abstimmen": "Voter pour l'heure",
  "Zeit festgelegt": "Heure validée",
  "Zeit offen": "Heure à fixer",
  "Zeit übernommen": "Heure reprise",
  "Zeit und Personen übernommen": "Heure et personnes reprises",
  "Zeit vorgeschlagen": "Heure proposée",
  "Zeit vorschlagen": "Proposer une heure",
  "Zeiten entfernen": "Supprimer les horaires",
  "Zeiten entfernt": "Horaires supprimés",
  "Zeiten gespeichert": "Horaires enregistrés",
  "Zeiten hinzufügen": "Ajouter des horaires",
  "Zeiten hinzugefügt": "Horaires ajoutés",
  "Zeitraum": "Période",
  "Zeitvorschläge ansehen": "Voir les propositions d'heure",
  "Zelt": "Tente",
  "Ziehen": "Faire glisser",
  "Ziehen zum Verschieben · Mausrad oder Regler zum Zoomen": "Glisse pour déplacer · molette ou curseur pour zoomer",
  "Ziehen zum Verschieben · mit zwei Fingern zoomen": "Glisse pour déplacer · pince pour zoomer",
  "Ziel": "Destination",
  "Ziel wählen": "Choisir où",
  "Zielflagge": "Drapeau à damier",
  "Zoom": "Zoom",
  "Zu besonderer Person wechseln?": "Passer en personne spéciale ?",
  "Zu bestem Freund wechseln?": "Passer en meilleur ami ?",
  "Zu diesem Konto gibt es keine E-Mail-Adresse.": "Aucune adresse e-mail n'est liée à ce compte.",
  "Zu dieser E-Mail gibt es schon ein Konto — melde dich an": "Il existe déjà un compte avec cet e-mail — connecte-toi",
  "Zu viele Versuche. Bitte später noch einmal.": "Trop de tentatives. Réessaie plus tard.",
  "Zuerst Freunde<br>hinzufügen": "Ajoute d'abord<br>des amis",
  "Zuhause": "À la maison",
  "Zuhause & Alltag": "Maison & quotidien",
  "Zuhause, ab 4 Personen am besten": "À la maison, idéal dès 4 personnes",
  "Zuhause, ab 4 Personen am besten — ein paar Spiele reichen.": "À la maison, idéal dès 4 personnes — quelques jeux suffisent.",
  "Zum Home-Bildschirm": "Sur l'écran d'accueil",
  "zum Namen passt nichts — wähl unten selbst": "rien ne correspond au nom — choisis ci-dessous",
  "Zur Crew": "Rejoindre la Crew",
  "Zurück": "Retour",
  "Zurück zu meiner Einladung": "Retour à mon invitation",
  "Zurück zur Anmeldung": "Retour à la connexion",
  "Zurückgenommen · wieder in {n} min": "Annulé · à nouveau dans {n} min",
  "Zurücksetzen": "Réinitialiser",
  "Zurücksetzen fehlgeschlagen: {fehler}": "Échec de la réinitialisation : {fehler}",
  "Zurückstupsen": "Faire signe en retour",
  "Zurückziehen": "Retirer",
  "Zusage geändert": "Réponse modifiée",
  "Zusage offen": "Réponse en attente",
  "zusammen kochen": "cuisiner ensemble",
  "Zusammenfassen": "Résumer",
  "Zustimmung steht aus": "En attente d'accord",
  "Zustimmung steht aus · {ort}": "En attente d'accord · {ort}",
  "Zwei Antworten braucht es mindestens": "Il faut au moins deux réponses",
  "Zwei Farben, die ineinander übergehen": "Deux couleurs qui se fondent l'une dans l'autre",
  "Zweite Farbe": "Deuxième couleur",
};
